import type { AssembleExecutionDashboardPhoneBodyScopeInput } from './assembleExecutionDashboardPhoneBodyScope';

export function assemblePhoneBodyScopeTail(input: AssembleExecutionDashboardPhoneBodyScopeInput) {
    const {
        scope,
        local,
        handlers,
        removeJudicialCustodianEntry,
        propertyInlineSaveCtx,
        movableInlineSaveCtx,
        saveSeizedMovableInitForDecision,
        secondaryStageReady,
        tertiaryStageReady,
        quaternaryStageReady,
        liveExecutionData,
    } = input;
    return {
        setDossierActionModalType: scope.setDossierActionModalType,
        setDossierActionModalSaving: scope.setDossierActionModalSaving,
        handleDossierAction: scope.handleDossierAction,
        dossierActionModalSaving: scope.dossierActionModalSaving,
        creditorWorkspaceEntries: scope.creditorWorkspaceEntries,
        showExtraCreditors: scope.showExtraCreditors,
        setShowExtraCreditors: scope.setShowExtraCreditors,
        getExecutionPartyDisplayName: scope.getExecutionPartyDisplayName,
        viewExecutionData: scope.viewExecutionData,
        buildPartyHeirsRows: scope.buildPartyHeirsRows,
        openHeirsQuickView: scope.openHeirsQuickView,
        effectiveCreditors: scope.effectiveCreditors,
        executionAppealBanner: scope.executionAppealBanner,
        partyBadgesExecutionId: scope.partyBadgesExecutionId,
        activeCoerciveActions: scope.activeCoerciveActions,
        seizedAssets: scope.seizedAssets,
        activeTimelineEvents: scope.activeTimelineEvents,
        decisionsReloadEpoch: scope.decisionsReloadEpoch,
        isHistoricalMode: scope.isHistoricalMode,
        creditorDeathMenuLabel: scope.creditorDeathMenuLabel,
        handleCreditorDeathMenuAction: scope.handleCreditorDeathMenuAction,
        creditorExtraMinorNames: scope.creditorExtraMinorNames,
        creditorExtraMinorLabel: scope.creditorExtraMinorLabel,
        decisionsStorageExecutionId: scope.decisionsStorageExecutionId,
        debtorsSectionRef: scope.debtorsSectionRef,
        activeDebtorHeirsForNotification: scope.activeDebtorHeirsForNotification,
        activeDebtorIsDeceased: scope.activeDebtorIsDeceased,
        activeNoticeState: scope.activeNoticeState,
        activeTimelineEventsDebtorScoped: scope.activeTimelineEventsDebtorScoped,
        buildDebtorSummonsMarkerPatchForKey: scope.buildDebtorSummonsMarkerPatchForKey,
        buildEmployeeAssignmentPatchForDebtorKey: scope.buildEmployeeAssignmentPatchForDebtorKey,
        buildPublicationNoticePatchForDebtorKey: scope.buildPublicationNoticePatchForDebtorKey,
        claimType: scope.claimType,
        clearDebtorSummonsMarker: scope.clearDebtorSummonsMarker,
        completeEvictionResidentialGrace: scope.completeEvictionResidentialGrace,
        completePoliceAssistance: scope.completePoliceAssistance,
        computeTaklifDeadlineYmd: scope.computeTaklifDeadlineYmd,
        daysRemainingUntilDeadline: scope.daysRemainingUntilDeadline,
        debtorArrested: scope.debtorArrested,
        debtorAttendedVoluntarily: scope.debtorAttendedVoluntarily,
        debtorBrowserTabsMode: scope.debtorBrowserTabsMode,
        liabilityGroupTabsMode: scope.liabilityGroupTabsMode,
        debtorLiabilityGroups: scope.debtorLiabilityGroups,
        debtorDeathMenuLabel: scope.debtorDeathMenuLabel,
        debtorEmploymentToggleMenuLabel: scope.debtorEmploymentToggleMenuLabel,
        debtorForcedToAttend: scope.debtorForcedToAttend,
        debtorSummonsMarkerLocal: scope.debtorSummonsMarkerLocal,
        debtorSummonsProfile: scope.debtorSummonsProfile,
        debtorWorkspaceChipStripRef: scope.debtorWorkspaceChipStripRef,
        debtorWorkspaceEntries: scope.debtorWorkspaceEntries,
        dismissDebtorAbsenceBadge: scope.dismissDebtorAbsenceBadge,
        effectiveDebtors: scope.effectiveDebtors,
        evictionGraceBadgeInfo: scope.evictionGraceBadgeInfo,
        evictionGracePinned: scope.evictionGracePinned,
        executionDebtorTabIndex: scope.executionDebtorTabIndex,
        executionId: scope.executionId,
        executionMemoBadgePopoverOpen: scope.executionMemoBadgePopoverOpen,
        executionToolsTimelineLockedUi: scope.executionToolsTimelineLockedUi,
        forcedAttendanceIssued: scope.forcedAttendanceIssued,
        forcedPathAttendanceSecured: scope.forcedPathAttendanceSecured,
        getDebtorSummonsMarkerForKey: scope.getDebtorSummonsMarkerForKey,
        getDebtorSummonsProfile: scope.getDebtorSummonsProfile,
        getEmployeeAssignmentForDebtorKey: scope.getEmployeeAssignmentForDebtorKey,
        getPersonalCoerciveSubtypeOutcome: scope.getPersonalCoerciveSubtypeOutcome,
        getPublicationNoticeForDebtorKey: scope.getPublicationNoticeForDebtorKey,
        handleDebtorDeathMenuAction: scope.handleDebtorDeathMenuAction,
        isAssignmentDeadlinePassed: scope.isAssignmentDeadlinePassed,
        isDebtorGovernmentEmployee: scope.isDebtorGovernmentEmployee,
        isDebtorRowEmployee: scope.isDebtorRowEmployee,
        isNonFinancialClaim: scope.isNonFinancialClaim,
        isRepresentingDebtor: scope.isRepresentingDebtor,
        multiDebtorMode: scope.multiDebtorMode,
        nextTimelineId: scope.nextTimelineId,
        openEvictionResidentialGraceModal: scope.openEvictionResidentialGraceModal,
        openHeirsNotificationCenter: scope.openHeirsNotificationCenter,
        openPoliceAssistanceFromBadge: scope.openPoliceAssistanceFromBadge,
        financialLawyerFeesAmount: scope.financialLawyerFeesAmount,
        financialPrincipalAmount: scope.financialPrincipalAmount,
        publicationNoticeDeadlineYmd: scope.publicationNoticeDeadlineYmd,
        pushTimelineEvent: scope.pushTimelineEvent,
        realEstateSeizureAssets: scope.realEstateSeizureAssets,
        saveSummonsMarkerPurposeEdit: scope.saveSummonsMarkerPurposeEdit,
        setDebtorSummonsMarkerLocal: scope.setDebtorSummonsMarkerLocal,
        setEvictionGraceDecisionId: scope.setEvictionGraceDecisionId,
        setExecutionDebtorTabIndex: scope.setExecutionDebtorTabIndex,
        setExecutionMemoBadgePopoverOpen: scope.setExecutionMemoBadgePopoverOpen,
        setShowExtraDebtors: scope.setShowExtraDebtors,
        setSummonsMarkerPopoverOpen: scope.setSummonsMarkerPopoverOpen,
        setSummonsPurposeDraft: scope.setSummonsPurposeDraft,
        showDebtorSummonsAttendanceBadge: scope.showDebtorSummonsAttendanceBadge,
        showDebtorUnservedMemoBadge: scope.showDebtorUnservedMemoBadge,
        showExtraDebtors: scope.showExtraDebtors,
        standaloneExecutionMarks: scope.standaloneExecutionMarks,
        summonsMarkerPopoverOpen: scope.summonsMarkerPopoverOpen,
        summonsPurposeDraft: scope.summonsPurposeDraft,
        thirdPartySeizureAssets: scope.thirdPartySeizureAssets,
        thirdPartySeizuresUi: scope.thirdPartySeizuresUi,
        timelineDebtorMetadata: scope.timelineDebtorMetadata,
        toggleEvictionGracePinned: scope.toggleEvictionGracePinned,
        voluntaryAttendanceCount: scope.voluntaryAttendanceCount,
        noticeVoluntaryPeriodEndOptimistic: scope.noticeVoluntaryPeriodEndOptimistic,
        voluntaryEndOptimistic: scope.voluntaryEndOptimistic,
        persistGuarantorFollowupDetails: scope.persistGuarantorFollowupDetails,
        policeAssistanceBadgeInfo: scope.policeAssistanceBadgeInfo,
        primaryDebtorAbsenceBadge: scope.primaryDebtorAbsenceBadge,
        primaryDebtorKeyResolved: scope.primaryDebtorKeyResolved,
        primaryMemoNoticeBadge: scope.primaryMemoNoticeBadge,
        primaryDebtorWorkspaceKey: scope.primaryDebtorWorkspaceKey,
        handleMemoFollowupClick: scope.handleMemoFollowupClick,
        closeUnifiedSeizureLog: scope.closeUnifiedSeizureLog,
        showUnifiedSeizureLogModal: scope.showUnifiedSeizureLogModal,
        showExecutionTrashModal: scope.showExecutionTrashModal,
        setShowExecutionTrashModal:
            scope.setShowExecutionTrashModal ?? local.safeSetShowExecutionTrashModal,
        setMovableSeizureRequestModalOpen: scope.setMovableSeizureRequestModalOpen,
        setPropertySeizureRequestModalOpen: scope.setPropertySeizureRequestModalOpen,
        movableSeizureRequestModalOpen: scope.movableSeizureRequestModalOpen,
        propertySeizureRequestModalOpen: scope.propertySeizureRequestModalOpen,
        showExecutionFinancialHub: scope.showExecutionFinancialHub,
        setShowExecutionFinancialHub: scope.setShowExecutionFinancialHub,
        setShowUnifiedExecutionModal: scope.setShowUnifiedExecutionModal,
        subFiles: local.safeSubFiles,
    };
}
