import type { AssembleExecutionDashboardPhoneBodyScopeInput } from './assembleExecutionDashboardPhoneBodyScope';

export function assemblePhoneBodyScopeHead(input: AssembleExecutionDashboardPhoneBodyScopeInput) {
    const {
        scope,
        local,
        handlers,
        removeJudicialCustodianEntry,
        propertyInlineSaveCtx,
        movableInlineSaveCtx,
        saveSeizedMovableInitForDecision,
        secondaryStageReady,
        tertiaryStageReady,
        quaternaryStageReady,
        liveExecutionData,
    } = input;
    return {
        scopeRef: scope.scopeRef,
        props: scope.props,
        followupSpec: local.followupSpec,
        safeInabaTargets: local.safeInabaTargets,
        safeSubFiles: local.safeSubFiles,
        safeTrashedTimelineEvents: local.safeTrashedTimelineEvents,
        safeTrashedCaseNotes: local.safeTrashedCaseNotes,
        safeTrashedCaseTasks: local.safeTrashedCaseTasks,
        safeActiveGraceTasks: local.safeActiveGraceTasks,
        localDossierLifecyclePopoverRef: local.localDossierLifecyclePopoverRef,
        localDossierLifecyclePanelPortalRef: local.localDossierLifecyclePanelPortalRef,
        safeShouldShowGuarantorExternalHub: local.safeShouldShowGuarantorExternalHub,
        localDossierStatusDraft: local.localDossierStatusDraft,
        setLocalDossierStatusDraft: local.setLocalDossierStatusDraft,
        localDossierLifecyclePanelOpen: local.localDossierLifecyclePanelOpen,
        setLocalDossierLifecyclePanelOpen: local.setLocalDossierLifecyclePanelOpen,
        localDossierLifecyclePanelPhase: local.localDossierLifecyclePanelPhase,
        setLocalDossierLifecyclePanelPhase: local.setLocalDossierLifecyclePanelPhase,
        localDossierPendingStatus: local.localDossierPendingStatus,
        setLocalDossierPendingStatus: local.setLocalDossierPendingStatus,
        safeApplyDossierLifecycleToFileAndTimeline: local.safeApplyDossierLifecycleToFileAndTimeline,
        safeHandleDossierLifecyclePick: local.safeHandleDossierLifecyclePick,
        safeHandleDossierLifecycleConfirmDetails: local.safeHandleDossierLifecycleConfirmDetails,
        dossierLifecyclePopoverRef:
            scope.dossierLifecyclePopoverRef ?? local.localDossierLifecyclePopoverRef,
        dossierLifecyclePanelPortalRef:
            scope.dossierLifecyclePanelPortalRef ?? local.localDossierLifecyclePanelPortalRef,
        dossierLifecyclePanelOpen:
            scope.dossierLifecyclePanelOpen ?? local.localDossierLifecyclePanelOpen,
        dossierLifecyclePopStyle: scope.dossierLifecyclePopStyle ?? local.safeDossierLifecyclePopStyle,
        dossierLifecyclePanelPhase:
            scope.dossierLifecyclePanelPhase ?? local.localDossierLifecyclePanelPhase,
        dossierStatusDraft: scope.dossierStatusDraft ?? local.localDossierStatusDraft,
        dossierPendingStatus: scope.dossierPendingStatus ?? local.localDossierPendingStatus,
        dossierReasonDraft: scope.dossierReasonDraft ?? local.safeDossierReasonDraft,
        dossierDateDraft: scope.dossierDateDraft ?? local.safeDossierDateDraft,
        setDossierLifecyclePanelOpen:
            scope.setDossierLifecyclePanelOpen ?? local.setLocalDossierLifecyclePanelOpen,
        setDossierLifecyclePanelPhase:
            scope.setDossierLifecyclePanelPhase ?? local.setLocalDossierLifecyclePanelPhase,
        setDossierPendingStatus:
            scope.setDossierPendingStatus ?? local.setLocalDossierPendingStatus,
        setDossierReasonDraft: scope.setDossierReasonDraft ?? local.safeSetDossierReasonDraft,
        setDossierDateDraft: scope.setDossierDateDraft ?? local.safeSetDossierDateDraft,
        localDossierReasonSeed: local.localDossierReasonSeed,
        localDossierDateSeed: local.localDossierDateSeed,
        safeSetShowExecutionTrashModal: local.safeSetShowExecutionTrashModal,
        safeToggleHeaderExpanded: local.safeToggleHeaderExpanded,
        safeResolveCalendarUserId: local.safeResolveCalendarUserId,
        safeOpenEditDossierMeta: handlers.safeOpenEditDossierMeta,
        safeOpenParentDossierMetaEdit: handlers.safeOpenParentDossierMetaEdit,
        safeOpenEditParty: handlers.safeOpenEditParty,
        safeHandleDebtorEmploymentToggle: handlers.safeHandleDebtorEmploymentToggle,
        directHandleMemoFollowupClick: handlers.directHandleMemoFollowupClick,
        directOpenDecisionsModalWithBoot: handlers.directOpenDecisionsModalWithBoot,
        safeOpenAppointmentModal: handlers.safeOpenAppointmentModal,
        directOpenNotesModal: handlers.directOpenNotesModal,
        directOpenDocumentsModal: handlers.directOpenDocumentsModal,
        directOpenTimelineModal: handlers.directOpenTimelineModal,
        directOpenLedgerModal: handlers.directOpenLedgerModal,
        directOpenEvictionExpenseModal: handlers.directOpenEvictionExpenseModal,
        directOpenPaymentCalculator: handlers.directOpenPaymentCalculator,
        directOpenSettlementCalculator: handlers.directOpenSettlementCalculator,
        directOpenUnifiedSummonsHub: handlers.directOpenUnifiedSummonsHub,
        directOpenFinancialCenter: handlers.directOpenFinancialCenter,
        closeFinancialHubPortal: handlers.closeFinancialHubPortal,
        toggleFinancialCenterExpanded: handlers.toggleFinancialCenterExpanded,
        openGuarantorFollowupDetails: handlers.openGuarantorFollowupDetails,
        safeTimelineAccordionExpanded: handlers.safeTimelineAccordionExpanded,
        safeSetTimelineAccordionExpanded: handlers.safeSetTimelineAccordionExpanded,
        removeJudicialCustodianEntry,
        propertyInlineSaveCtx,
        movableInlineSaveCtx,
        saveSeizedMovableInitForDecision,
        secondaryStageReady,
        tertiaryStageReady,
        quaternaryStageReady,
        onClose: scope.onClose,
        stayOfExecutionActive: scope.stayOfExecutionActive,
        parentDossierId: scope.parentDossierId,
        file: scope.file,
        hasChildDossiers: scope.hasChildDossiers,
        isInabaActive: scope.isInabaActive,
        activeTabId: scope.activeTabId,
        currentFileId: scope.currentFileId,
        currentFile: scope.currentFile,
        childDossiers: scope.childDossiers,
        setActiveTabId: scope.setActiveTabId,
        setExecutionStorageTick: scope.setExecutionStorageTick,
        showToast: scope.showToast,
        statuteStatus: scope.statuteStatus,
        isAlimonyClaim: scope.isAlimonyClaim,
        executionPaused: scope.executionPaused,
        handleResumeExecution: scope.handleResumeExecution,
        executionData: liveExecutionData,
        handleLiftStayOfExecution: scope.handleLiftStayOfExecution,
        isHeaderExpanded: scope.isHeaderExpanded,
        headerFields: scope.headerFields,
        isEvictionExecutionModule: scope.isEvictionExecutionModule,
        classificationDisplay: scope.classificationDisplay,
        showJudgmentMeta: scope.showJudgmentMeta,
        docNumber: scope.docNumber,
        judgmentDateDisplay: scope.judgmentDateDisplay,
        claimTypeArabicDisplay: scope.claimTypeArabicDisplay,
        evictionPropertyNumber: scope.evictionPropertyNumber,
        evictionPropertyDistrict: scope.evictionPropertyDistrict,
        evictionPropertyTypeField: scope.evictionPropertyTypeField,
        evictionFullAddressField: scope.evictionFullAddressField,
        persistExecutionMerge: scope.persistExecutionMerge,
        isUnifiedTabActive: scope.isUnifiedTabActive,
        setLinkedDossierToView: scope.setLinkedDossierToView,
        setShowLinkedDossierTimeline: scope.setShowLinkedDossierTimeline,
        setShowTransferFileNumberChangeModal: scope.setShowTransferFileNumberChangeModal,
        activeSubFileId: scope.activeSubFileId,
        parentExecutionFile: scope.parentExecutionFile,
        parentHeaderFields: scope.parentHeaderFields,
        parentClassificationDisplay: scope.parentClassificationDisplay,
        parentClaimTypeArabicDisplay: scope.parentClaimTypeArabicDisplay,
        parentShowJudgmentMeta: scope.parentShowJudgmentMeta,
        parentJudgmentDateDisplay: scope.parentJudgmentDateDisplay,
        parentIsEvictionForExpandedHeader: scope.parentIsEvictionForExpandedHeader,
        dossierActionModalOpen: scope.dossierActionModalOpen,
        dossierActionModalType: scope.dossierActionModalType,
        setDossierActionModalOpen: scope.setDossierActionModalOpen,
    };
}
