// @ts-nocheck
/** مراجع lazy/prefetch لـ chunk scope — chunk execution-dashboard-core (لا static-scope) */
import {
    LazyActionGridSection,
    LazyCoerciveTab,
    LazyCommunicationsTab,
    LazyDashboardHeaderSection,
    LazyDebtorsSection,
    LazyDecisionsAndAppealsEngine,
    LazyDossierControlsTab,
    LazyDossierLifecyclePanel,
    LazyDossierMetaEditSection,
    LazyDocumentVault,
    LazyExecutionDecisionsModalContainer,
    LazyExecutionDebtorNotificationMemoModalContainer,
    LazyExecutionFinancialHubPortal,
    LazyExecutionFinancialLedgerPortalContainer,
    LazyExecutionFullTimelineModalContainer,
    LazyExecutionHeirsNotificationModalContainer,
    LazyExecutionModalsContainer,
    LazyExecutionNotesAndAppointmentModals,
    LazyExecutionPaymentModalContainer,
    LazyExecutionSeizedAssetsModalContainer,
    LazyExecutionSolidaryAndEvictionFollowupModalsContainer,
    LazyExecutorWorkflowPortalModals,
    LazyUnifiedSummonsModalContainer,
    LazyFinancialOperationsCenter,
    LazyFinancialTab,
    LazyGuarantorDetailsPostApprovalModal,
    LazyLawReferencePanel,
    LazyMaritalFurnitureModule,
    LazyModalSeizedAssetsManager,
    LazyOtherPartyTab,
    LazyPartiesSection,
    LazyPartyEditModal,
    LazyPermanentDeleteConfirmDialog,
    LazyPersonalTab,
    LazyRequestsTab,
    LazySeizureRequestsTab,
    LazyPartyDeathReportModal,
    LazyPaymentCalculator,
    LazyPoliceAssistanceDetailsModal,
    LazyPremiumTimelineAuditLog,
    LazyRealEstateSeizurePostApprovalModal,
    LazySettlementCalculator,
    LazySmartTimelineRadar,
    LazyStayOfExecutionModal,
    LazyTimelineSection,
    LazyUnifiedSummonsHub,
    LazyVisitationScheduleModule,
    LazyVisitationCalendarModal,
    LazyExecutorApprovedDateTimeModal,
    LazyExecutorBreakInventoryFurnitureModal,
    LazyExecutorJudicialCustodianModal,
    LazyExecutorWorkflowConfirmModal,
    LazyPersonalCoerciveFollowupPanel,
    LazyEmployeeAssignmentCoerciveFollowupBlock,
    LazyJudicialCustodianCardMenu,
    LazyEvictionFieldProceduresPanel,
    LazyOtherPartyActionsLog,
    prefetchExecutionDashboardShell,
    prefetchExecutionModalContainers,
    LazyExecutionCoerciveActionsModalContainer,
    LazyExecutionTrashModal,
    LazyTimelineEditModal,
    LazyExecutionHeirsQuickViewModal,
    LazyExecutionTransferFileNumberModal,
    LazyDossierActionsModal,
    LazyLinkedDossierTimelineModal,
    LazySeizureRequestSubjectModal,
    LazyAlimonyBeneficiaryDeathModal,
    prefetchExecutionOverlayModals,
} from '../executionDashboardLazyRegistry';
import { prefetchExecutionFollowupDefaultTab } from '../executionFollowupTabPrefetch';
import { SPECIAL_REQUEST_MANUAL_MODE } from '../components/requestsTabConstants';
import {
    prefetchExecutionFollowupModalPortal,
    LazyExecutionFollowupModalPortal,
} from '../executionFollowupModalLazy';
import * as LazyRegistryNamespace from '../executionDashboardLazyRegistry';
import * as FollowupModalLazyNamespace from '../executionFollowupModalLazy';

export const EXECUTION_DASHBOARD_LAZY_CHUNK_SCOPE = {
    LazyActionGridSection,
    LazyAlimonyBeneficiaryDeathModal,
    LazyCoerciveTab,
    LazyCommunicationsTab,
    LazyDashboardHeaderSection,
    LazyDebtorsSection,
    LazyDecisionsAndAppealsEngine,
    LazyDocumentVault,
    LazyDossierActionsModal,
    LazyDossierControlsTab,
    LazyDossierLifecyclePanel,
    LazyDossierMetaEditSection,
    LazyEmployeeAssignmentCoerciveFollowupBlock,
    LazyEvictionFieldProceduresPanel,
    LazyExecutionCoerciveActionsModalContainer,
    LazyExecutionDebtorNotificationMemoModalContainer,
    LazyExecutionDecisionsModalContainer,
    LazyExecutionFinancialHubPortal,
    LazyExecutionFinancialLedgerPortalContainer,
    LazyExecutionFollowupModalPortal,
    LazyExecutionFullTimelineModalContainer,
    LazyExecutionHeirsNotificationModalContainer,
    LazyExecutionHeirsQuickViewModal,
    LazyExecutionModalsContainer,
    LazyExecutionNotesAndAppointmentModals,
    LazyExecutionPaymentModalContainer,
    LazyExecutionSeizedAssetsModalContainer,
    LazyExecutionSolidaryAndEvictionFollowupModalsContainer,
    LazyExecutionTransferFileNumberModal,
    LazyExecutionTrashModal,
    LazyExecutorApprovedDateTimeModal,
    LazyExecutorBreakInventoryFurnitureModal,
    LazyExecutorJudicialCustodianModal,
    LazyExecutorWorkflowConfirmModal,
    LazyExecutorWorkflowPortalModals,
    LazyFinancialOperationsCenter,
    LazyFinancialTab,
    LazyGuarantorDetailsPostApprovalModal,
    LazyJudicialCustodianCardMenu,
    LazyLawReferencePanel,
    LazyLinkedDossierTimelineModal,
    LazyMaritalFurnitureModule,
    LazyModalSeizedAssetsManager,
    LazyOtherPartyActionsLog,
    LazyOtherPartyTab,
    LazyPartiesSection,
    LazyPartyDeathReportModal,
    LazyPartyEditModal,
    LazyPaymentCalculator,
    LazyPermanentDeleteConfirmDialog,
    LazyPersonalCoerciveFollowupPanel,
    LazyPersonalTab,
    LazyPoliceAssistanceDetailsModal,
    LazyPremiumTimelineAuditLog,
    LazyRealEstateSeizurePostApprovalModal,
    LazyRequestsTab,
    LazySeizureRequestSubjectModal,
    LazySeizureRequestsTab,
    LazySettlementCalculator,
    LazySmartTimelineRadar,
    LazyStayOfExecutionModal,
    LazyTimelineEditModal,
    LazyTimelineSection,
    LazyUnifiedSummonsHub,
    LazyUnifiedSummonsModalContainer,
    LazyVisitationCalendarModal,
    LazyVisitationScheduleModule,
    prefetchExecutionDashboardShell,
    prefetchExecutionFollowupDefaultTab,
    prefetchExecutionFollowupModalPortal,
    prefetchExecutionModalContainers,
    prefetchExecutionOverlayModals,
    SPECIAL_REQUEST_MANUAL_MODE,
} as const;

/** يُستدعى وقت التشغيل — يتجاوز مراجع lazy = undefined من circular chunks */
export function spreadExecutionDashboardLazyChunkScope(): Record<string, unknown> {
    const out: Record<string, unknown> = {
        ...(EXECUTION_DASHBOARD_LAZY_CHUNK_SCOPE as unknown as Record<string, unknown>),
    };
    for (const [key, value] of Object.entries(LazyRegistryNamespace)) {
        if (out[key] == null && value != null) {
            out[key] = value;
        }
    }
    for (const [key, value] of Object.entries(FollowupModalLazyNamespace)) {
        if (out[key] == null && value != null) {
            out[key] = value;
        }
    }
    return out;
}
