/** Lazy/prefetch للنوافذ والمالية والقانون — يُدمج عند overlay scope لا first-paint. */
import {
    LazyDecisionsAndAppealsEngine,
    LazyDossierMetaEditSection,
    LazyDocumentVault,
    LazyExecutionDecisionsModalContainer,
    LazyExecutionDebtorNotificationMemoModalContainer,
    LazyExecutionFinancialHubPortal,
    LazyExecutionFinancialLedgerPortalContainer,
    LazyExecutionFullTimelineModalContainer,
    LazyExecutionHeirsNotificationModalContainer,
    LazyExecutionModalsContainer,
    LazyExecutionNotesAndAppointmentModals,
    LazyExecutionPaymentModalContainer,
    LazyExecutionSeizedAssetsModalContainer,
    LazyExecutionSolidaryAndEvictionFollowupModalsContainer,
    LazyExecutorWorkflowPortalModals,
    LazyUnifiedSummonsModalContainer,
    LazyFinancialOperationsCenter,
    LazyGuarantorDetailsPostApprovalModal,
    LazyLawReferencePanel,
    LazyModalSeizedAssetsManager,
    LazyPartyEditModal,
    LazyPermanentDeleteConfirmDialog,
    LazyPartyDeathReportModal,
    LazyPaymentCalculator,
    LazyPoliceAssistanceDetailsModal,
    LazyPremiumTimelineAuditLog,
    LazyRealEstateSeizurePostApprovalModal,
    LazySettlementCalculator,
    LazySmartTimelineRadar,
    LazyStayOfExecutionModal,
    LazyUnifiedSummonsHub,
    LazyExecutorApprovedDateTimeModal,
    LazyExecutorBreakInventoryFurnitureModal,
    LazyExecutorJudicialCustodianModal,
    LazyExecutorWorkflowConfirmModal,
    LazyJudicialCustodianCardMenu,
    LazyEvictionFieldProceduresPanel,
    LazyOtherPartyActionsLog,
    prefetchExecutionModalContainers,
    LazyExecutionCoerciveActionsModalContainer,
    LazyExecutionTrashModal,
    LazyTimelineEditModal,
    LazyExecutionHeirsQuickViewModal,
    LazyExecutionTransferFileNumberModal,
    LazyDossierActionsModal,
    LazyLinkedDossierTimelineModal,
    LazySeizureRequestSubjectModal,
    LazyAlimonyBeneficiaryDeathModal,
    prefetchExecutionOverlayModals,
} from '../executionDashboardLazyRegistryOverlays';
import { prefetchExecutionFollowupDefaultTab } from '../executionFollowupTabPrefetch';
import * as LazyRegistryOverlaysNamespace from '../executionDashboardLazyRegistryOverlays';

export const EXECUTION_DASHBOARD_LAZY_CHUNK_SCOPE_OVERLAYS = {
    LazyAlimonyBeneficiaryDeathModal,
    LazyDecisionsAndAppealsEngine,
    LazyDocumentVault,
    LazyDossierActionsModal,
    LazyDossierMetaEditSection,
    LazyEvictionFieldProceduresPanel,
    LazyExecutionCoerciveActionsModalContainer,
    LazyExecutionDebtorNotificationMemoModalContainer,
    LazyExecutionDecisionsModalContainer,
    LazyExecutionFinancialHubPortal,
    LazyExecutionFinancialLedgerPortalContainer,
    LazyExecutionFullTimelineModalContainer,
    LazyExecutionHeirsNotificationModalContainer,
    LazyExecutionHeirsQuickViewModal,
    LazyExecutionModalsContainer,
    LazyExecutionNotesAndAppointmentModals,
    LazyExecutionPaymentModalContainer,
    LazyExecutionSeizedAssetsModalContainer,
    LazyExecutionSolidaryAndEvictionFollowupModalsContainer,
    LazyExecutionTransferFileNumberModal,
    LazyExecutionTrashModal,
    LazyExecutorApprovedDateTimeModal,
    LazyExecutorBreakInventoryFurnitureModal,
    LazyExecutorJudicialCustodianModal,
    LazyExecutorWorkflowConfirmModal,
    LazyExecutorWorkflowPortalModals,
    LazyFinancialOperationsCenter,
    LazyGuarantorDetailsPostApprovalModal,
    LazyJudicialCustodianCardMenu,
    LazyLawReferencePanel,
    LazyLinkedDossierTimelineModal,
    LazyModalSeizedAssetsManager,
    LazyOtherPartyActionsLog,
    LazyPartyDeathReportModal,
    LazyPartyEditModal,
    LazyPaymentCalculator,
    LazyPermanentDeleteConfirmDialog,
    LazyPoliceAssistanceDetailsModal,
    LazyPremiumTimelineAuditLog,
    LazyRealEstateSeizurePostApprovalModal,
    LazySeizureRequestSubjectModal,
    LazySettlementCalculator,
    LazySmartTimelineRadar,
    LazyStayOfExecutionModal,
    LazyTimelineEditModal,
    LazyUnifiedSummonsHub,
    LazyUnifiedSummonsModalContainer,
    prefetchExecutionFollowupDefaultTab,
    prefetchExecutionModalContainers,
    prefetchExecutionOverlayModals,
} as const;

export function spreadExecutionDashboardLazyChunkScopeOverlays(): Record<string, unknown> {
    const out: Record<string, unknown> = {
        ...(EXECUTION_DASHBOARD_LAZY_CHUNK_SCOPE_OVERLAYS as unknown as Record<string, unknown>),
    };
    for (const [key, value] of Object.entries(LazyRegistryOverlaysNamespace)) {
        if (out[key] == null && value != null) {
            out[key] = value;
        }
    }
    return out;
}
