/** Scope + safe handlers for ExecutionDashboardPhoneBody (orchestrator) */
import { useExecutionDashboardPhoneBodyMountStages } from './useExecutionDashboardPhoneBodyMountStages';
import { useExecutionDashboardJudicialCustodianRemove } from './executionDashboardCore/useExecutionDashboardJudicialCustodianRemove';
import { useExecutionDashboardPropertyInlineSaveContext } from './executionDashboardCore/useExecutionDashboardPropertyInlineSaveContext';
import { useExecutionDashboardPhoneBodyScopeRead } from './useExecutionDashboardPhoneBodyScopeRead';
import { useExecutionDashboardPhoneBodyLocalState } from './useExecutionDashboardPhoneBodyLocalState';
import { useExecutionDashboardPhoneBodySafeHandlers } from './useExecutionDashboardPhoneBodySafeHandlers';

export function useExecutionDashboardPhoneBodyScope(renderFingerprint?: string) {
    const scope = useExecutionDashboardPhoneBodyScopeRead(renderFingerprint);
    const local = useExecutionDashboardPhoneBodyLocalState(scope, scope.scopeRef);
    const handlers = useExecutionDashboardPhoneBodySafeHandlers({
        scopeRef: scope.scopeRef,
        debtorsSectionRef: scope.debtorsSectionRef,
        handleDebtorEmploymentToggle: scope.handleDebtorEmploymentToggle,
        handleMemoFollowupClick: scope.handleMemoFollowupClick,
        openDecisionsModalWithBoot: scope.openDecisionsModalWithBoot,
        openFinancialHubLedger: scope.openFinancialHubLedger,
        openGuarantorDetailsModal: scope.openGuarantorDetailsModal,
        primaryDebtorWorkspaceKey: scope.primaryDebtorWorkspaceKey,
        setExecutionDebtorTabIndex: scope.setExecutionDebtorTabIndex,
        setFinancialHubAutoOpenMode: scope.setFinancialHubAutoOpenMode,
        setFinancialHubSeizedMovableId: scope.setFinancialHubSeizedMovableId,
        setFinancialHubSeizedPropertyId: scope.setFinancialHubSeizedPropertyId,
        setIsFinancialCenterExpanded: scope.setIsFinancialCenterExpanded,
        setShowAppointmentModal: scope.setShowAppointmentModal,
        // المفتاح الحقيقي في الـ scope هو setShowDecisionsModal — الاسم بالشرطة السفلية
        // كان يشير لمفتاح غير موجود فيعطّل fallback فتح القرارات.
        _setShowDecisionsModal: scope.setShowDecisionsModal,
        setShowEvictionExpenseModal: scope.setShowEvictionExpenseModal,
        setShowExecutionFinancialHub: scope.setShowExecutionFinancialHub,
        setShowLedgerModal: scope.setShowLedgerModal,
        setShowNotesModal: scope.setShowNotesModal,
        setShowPaymentCalculator: scope.setShowPaymentCalculator,
        setShowSettlementCalculator: scope.setShowSettlementCalculator,
        setShowTimelineModal: scope.setShowTimelineModal,
        setShowUnifiedExecutionModal: scope.setShowUnifiedExecutionModal,
        setShowUnifiedSummonsModal: scope.setShowUnifiedSummonsModal,
        setSummonsContextDebtorKey: scope.setSummonsContextDebtorKey,
        setSummonsHubInitialMainTab: scope.setSummonsHubInitialMainTab,
        setTimelineAccordionExpanded: scope.setTimelineAccordionExpanded,
        showToast: scope.showToast,
        timelineAccordionExpanded: scope.timelineAccordionExpanded,
        createModalSetterFallback: local.createModalSetterFallback,
        safeSetShowAppointmentModal: local.safeSetShowAppointmentModal,
        safeSetShowNotesModal: local.safeSetShowNotesModal,
        safeSetShowDocumentsModal: local.safeSetShowDocumentsModal,
        timelineAccordionExpandedFallback: local.timelineAccordionExpandedFallback,
        setTimelineAccordionExpandedFallback: local.setTimelineAccordionExpandedFallback,
    });

    const removeJudicialCustodianEntry = useExecutionDashboardJudicialCustodianRemove({
        executionData: scope.executionData,
        persistExecutionMerge: scope.persistExecutionMerge,
        showToast: scope.showToast,
    });

    const propertyInlineSaveCtx = useExecutionDashboardPropertyInlineSaveContext({
        decisionsStorageExecutionId: scope.decisionsStorageExecutionId,
        executionDataId: scope.executionData?.id,
        executionId: scope.executionId,
        showToast: scope.showToast,
        persistExecutionMerge: scope.persistExecutionMerge,
        pushTimelineEvent: scope.pushTimelineEvent,
        nextTimelineId: scope.nextTimelineId,
        linkSeizureAuctionToAppointments: Boolean(scope.linkSeizureAuctionToAppointments),
        pushSeizureAuctionCalendarAppointment: scope.pushSeizureAuctionCalendarAppointment,
    });

    const { secondaryStageReady, tertiaryStageReady, quaternaryStageReady } =
        useExecutionDashboardPhoneBodyMountStages({
            movableSeizureRequestModalOpen: scope.movableSeizureRequestModalOpen,
            propertySeizureRequestModalOpen: scope.propertySeizureRequestModalOpen,
            showExecutionFinancialHub: scope.showExecutionFinancialHub,
            showUnifiedSeizureLogModal: scope.showUnifiedSeizureLogModal,
            showVisitationCalendarModal: scope.showVisitationCalendarModal,
        });

    return {
        props: scope.props,
        followupSpec: local.followupSpec,
        safeInabaTargets: local.safeInabaTargets,
        safeSubFiles: local.safeSubFiles,
        safeTrashedTimelineEvents: local.safeTrashedTimelineEvents,
        safeTrashedCaseNotes: local.safeTrashedCaseNotes,
        safeTrashedCaseTasks: local.safeTrashedCaseTasks,
        safeActiveGraceTasks: local.safeActiveGraceTasks,
        localDossierLifecyclePopoverRef: local.localDossierLifecyclePopoverRef,
        localDossierLifecyclePanelPortalRef: local.localDossierLifecyclePanelPortalRef,
        safeShouldShowGuarantorExternalHub: local.safeShouldShowGuarantorExternalHub,
        localDossierStatusDraft: local.localDossierStatusDraft,
        setLocalDossierStatusDraft: local.setLocalDossierStatusDraft,
        localDossierLifecyclePanelOpen: local.localDossierLifecyclePanelOpen,
        setLocalDossierLifecyclePanelOpen: local.setLocalDossierLifecyclePanelOpen,
        localDossierLifecyclePanelPhase: local.localDossierLifecyclePanelPhase,
        setLocalDossierLifecyclePanelPhase: local.setLocalDossierLifecyclePanelPhase,
        localDossierPendingStatus: local.localDossierPendingStatus,
        setLocalDossierPendingStatus: local.setLocalDossierPendingStatus,
        safeApplyDossierLifecycleToFileAndTimeline: local.safeApplyDossierLifecycleToFileAndTimeline,
        localDossierReasonSeed: local.localDossierReasonSeed,
        localDossierDateSeed: local.localDossierDateSeed,
        safeSetShowExecutionTrashModal: local.safeSetShowExecutionTrashModal,
        safeToggleHeaderExpanded: local.safeToggleHeaderExpanded,
        safeResolveCalendarUserId: local.safeResolveCalendarUserId,
        safeOpenEditDossierMeta: handlers.safeOpenEditDossierMeta,
        safeOpenParentDossierMetaEdit: handlers.safeOpenParentDossierMetaEdit,
        safeOpenEditParty: handlers.safeOpenEditParty,
        safeHandleDebtorEmploymentToggle: handlers.safeHandleDebtorEmploymentToggle,
        directHandleMemoFollowupClick: handlers.directHandleMemoFollowupClick,
        directOpenDecisionsModalWithBoot: handlers.directOpenDecisionsModalWithBoot,
        safeOpenAppointmentModal: handlers.safeOpenAppointmentModal,
        directOpenNotesModal: handlers.directOpenNotesModal,
        directOpenDocumentsModal: handlers.directOpenDocumentsModal,
        directOpenTimelineModal: handlers.directOpenTimelineModal,
        directOpenLedgerModal: handlers.directOpenLedgerModal,
        directOpenEvictionExpenseModal: handlers.directOpenEvictionExpenseModal,
        directOpenPaymentCalculator: handlers.directOpenPaymentCalculator,
        directOpenSettlementCalculator: handlers.directOpenSettlementCalculator,
        directOpenUnifiedSummonsHub: handlers.directOpenUnifiedSummonsHub,
        directOpenFinancialCenter: handlers.directOpenFinancialCenter,
        closeFinancialHubPortal: handlers.closeFinancialHubPortal,
        toggleFinancialCenterExpanded: handlers.toggleFinancialCenterExpanded,
        openGuarantorFollowupDetails: handlers.openGuarantorFollowupDetails,
        safeTimelineAccordionExpanded: handlers.safeTimelineAccordionExpanded,
        safeSetTimelineAccordionExpanded: handlers.safeSetTimelineAccordionExpanded,
        removeJudicialCustodianEntry,
        propertyInlineSaveCtx,
        secondaryStageReady,
        tertiaryStageReady,
        quaternaryStageReady,
        onClose: scope.onClose,
        stayOfExecutionActive: scope.stayOfExecutionActive,
        parentDossierId: scope.parentDossierId,
        file: scope.file,
        hasChildDossiers: scope.hasChildDossiers,
        isInabaActive: scope.isInabaActive,
        activeTabId: scope.activeTabId,
        currentFileId: scope.currentFileId,
        currentFile: scope.currentFile,
        childDossiers: scope.childDossiers,
        setActiveTabId: scope.setActiveTabId,
        setExecutionStorageTick: scope.setExecutionStorageTick,
        showToast: scope.showToast,
        statuteStatus: scope.statuteStatus,
        isAlimonyClaim: scope.isAlimonyClaim,
        executionPaused: scope.executionPaused,
        handleResumeExecution: scope.handleResumeExecution,
        executionData: scope.executionData,
        handleLiftStayOfExecution: scope.handleLiftStayOfExecution,
        isHeaderExpanded: scope.isHeaderExpanded,
        headerFields: scope.headerFields,
        isEvictionExecutionModule: scope.isEvictionExecutionModule,
        classificationDisplay: scope.classificationDisplay,
        showJudgmentMeta: scope.showJudgmentMeta,
        docNumber: scope.docNumber,
        judgmentDateDisplay: scope.judgmentDateDisplay,
        claimTypeArabicDisplay: scope.claimTypeArabicDisplay,
        evictionPropertyNumber: scope.evictionPropertyNumber,
        evictionPropertyDistrict: scope.evictionPropertyDistrict,
        evictionPropertyTypeField: scope.evictionPropertyTypeField,
        evictionFullAddressField: scope.evictionFullAddressField,
        persistExecutionMerge: scope.persistExecutionMerge,
        isUnifiedTabActive: scope.isUnifiedTabActive,
        setLinkedDossierToView: scope.setLinkedDossierToView,
        setShowLinkedDossierTimeline: scope.setShowLinkedDossierTimeline,
        setShowTransferFileNumberChangeModal: scope.setShowTransferFileNumberChangeModal,
        activeSubFileId: scope.activeSubFileId,
        parentExecutionFile: scope.parentExecutionFile,
        parentHeaderFields: scope.parentHeaderFields,
        parentClassificationDisplay: scope.parentClassificationDisplay,
        parentClaimTypeArabicDisplay: scope.parentClaimTypeArabicDisplay,
        parentShowJudgmentMeta: scope.parentShowJudgmentMeta,
        parentJudgmentDateDisplay: scope.parentJudgmentDateDisplay,
        parentIsEvictionForExpandedHeader: scope.parentIsEvictionForExpandedHeader,
        dossierActionModalOpen: scope.dossierActionModalOpen,
        dossierActionModalType: scope.dossierActionModalType,
        setDossierActionModalOpen: scope.setDossierActionModalOpen,
        setDossierActionModalType: scope.setDossierActionModalType,
        setDossierActionModalSaving: scope.setDossierActionModalSaving,
        handleDossierAction: scope.handleDossierAction,
        dossierActionModalSaving: scope.dossierActionModalSaving,
        creditorWorkspaceEntries: scope.creditorWorkspaceEntries,
        showExtraCreditors: scope.showExtraCreditors,
        setShowExtraCreditors: scope.setShowExtraCreditors,
        getExecutionPartyDisplayName: scope.getExecutionPartyDisplayName,
        viewExecutionData: scope.viewExecutionData,
        buildPartyHeirsRows: scope.buildPartyHeirsRows,
        openHeirsQuickView: scope.openHeirsQuickView,
        effectiveCreditors: scope.effectiveCreditors,
        executionAppealBanner: scope.executionAppealBanner,
        partyBadgesExecutionId: scope.partyBadgesExecutionId,
        activeCoerciveActions: scope.activeCoerciveActions,
        seizedAssets: scope.seizedAssets,
        activeTimelineEvents: scope.activeTimelineEvents,
        decisionsReloadEpoch: scope.decisionsReloadEpoch,
        isHistoricalMode: scope.isHistoricalMode,
        creditorDeathMenuLabel: scope.creditorDeathMenuLabel,
        handleCreditorDeathMenuAction: scope.handleCreditorDeathMenuAction,
        creditorExtraMinorNames: scope.creditorExtraMinorNames,
        creditorExtraMinorLabel: scope.creditorExtraMinorLabel,
        decisionsStorageExecutionId: scope.decisionsStorageExecutionId,
        debtorsSectionRef: scope.debtorsSectionRef,
        activeDebtorHeirsForNotification: scope.activeDebtorHeirsForNotification,
        activeDebtorIsDeceased: scope.activeDebtorIsDeceased,
        activeNoticeState: scope.activeNoticeState,
        activeTimelineEventsDebtorScoped: scope.activeTimelineEventsDebtorScoped,
        buildDebtorSummonsMarkerPatchForKey: scope.buildDebtorSummonsMarkerPatchForKey,
        buildEmployeeAssignmentPatchForDebtorKey: scope.buildEmployeeAssignmentPatchForDebtorKey,
        buildPublicationNoticePatchForDebtorKey: scope.buildPublicationNoticePatchForDebtorKey,
        claimType: scope.claimType,
        clearDebtorSummonsMarker: scope.clearDebtorSummonsMarker,
        completeEvictionResidentialGrace: scope.completeEvictionResidentialGrace,
        completePoliceAssistance: scope.completePoliceAssistance,
        computeTaklifDeadlineYmd: scope.computeTaklifDeadlineYmd,
        daysRemainingUntilDeadline: scope.daysRemainingUntilDeadline,
        debtorArrested: scope.debtorArrested,
        debtorAttendedVoluntarily: scope.debtorAttendedVoluntarily,
        debtorBrowserTabsMode: scope.debtorBrowserTabsMode,
        liabilityGroupTabsMode: scope.liabilityGroupTabsMode,
        debtorLiabilityGroups: scope.debtorLiabilityGroups,
        debtorDeathMenuLabel: scope.debtorDeathMenuLabel,
        debtorEmploymentToggleMenuLabel: scope.debtorEmploymentToggleMenuLabel,
        debtorForcedToAttend: scope.debtorForcedToAttend,
        debtorSummonsMarkerLocal: scope.debtorSummonsMarkerLocal,
        debtorSummonsProfile: scope.debtorSummonsProfile,
        debtorWorkspaceChipStripRef: scope.debtorWorkspaceChipStripRef,
        debtorWorkspaceEntries: scope.debtorWorkspaceEntries,
        dismissDebtorAbsenceBadge: scope.dismissDebtorAbsenceBadge,
        effectiveDebtors: scope.effectiveDebtors,
        evictionGraceBadgeInfo: scope.evictionGraceBadgeInfo,
        evictionGracePinned: scope.evictionGracePinned,
        executionDebtorTabIndex: scope.executionDebtorTabIndex,
        executionId: scope.executionId,
        executionMemoBadgePopoverOpen: scope.executionMemoBadgePopoverOpen,
        executionToolsTimelineLockedUi: scope.executionToolsTimelineLockedUi,
        forcedAttendanceIssued: scope.forcedAttendanceIssued,
        forcedPathAttendanceSecured: scope.forcedPathAttendanceSecured,
        getDebtorSummonsMarkerForKey: scope.getDebtorSummonsMarkerForKey,
        getDebtorSummonsProfile: scope.getDebtorSummonsProfile,
        getEmployeeAssignmentForDebtorKey: scope.getEmployeeAssignmentForDebtorKey,
        getPersonalCoerciveSubtypeOutcome: scope.getPersonalCoerciveSubtypeOutcome,
        getPublicationNoticeForDebtorKey: scope.getPublicationNoticeForDebtorKey,
        handleDebtorDeathMenuAction: scope.handleDebtorDeathMenuAction,
        isAssignmentDeadlinePassed: scope.isAssignmentDeadlinePassed,
        isDebtorGovernmentEmployee: scope.isDebtorGovernmentEmployee,
        isDebtorRowEmployee: scope.isDebtorRowEmployee,
        isNonFinancialClaim: scope.isNonFinancialClaim,
        isRepresentingDebtor: scope.isRepresentingDebtor,
        multiDebtorMode: scope.multiDebtorMode,
        nextTimelineId: scope.nextTimelineId,
        openEvictionResidentialGraceModal: scope.openEvictionResidentialGraceModal,
        openHeirsNotificationCenter: scope.openHeirsNotificationCenter,
        openPoliceAssistanceFromBadge: scope.openPoliceAssistanceFromBadge,
        financialLawyerFeesAmount: scope.financialLawyerFeesAmount,
        financialPrincipalAmount: scope.financialPrincipalAmount,
        publicationNoticeDeadlineYmd: scope.publicationNoticeDeadlineYmd,
        pushTimelineEvent: scope.pushTimelineEvent,
        realEstateSeizureAssets: scope.realEstateSeizureAssets,
        saveSummonsMarkerPurposeEdit: scope.saveSummonsMarkerPurposeEdit,
        setDebtorSummonsMarkerLocal: scope.setDebtorSummonsMarkerLocal,
        setEvictionGraceDecisionId: scope.setEvictionGraceDecisionId,
        setExecutionDebtorTabIndex: scope.setExecutionDebtorTabIndex,
        setExecutionMemoBadgePopoverOpen: scope.setExecutionMemoBadgePopoverOpen,
        setShowExtraDebtors: scope.setShowExtraDebtors,
        setSummonsMarkerPopoverOpen: scope.setSummonsMarkerPopoverOpen,
        setSummonsPurposeDraft: scope.setSummonsPurposeDraft,
        showDebtorSummonsAttendanceBadge: scope.showDebtorSummonsAttendanceBadge,
        showDebtorUnservedMemoBadge: scope.showDebtorUnservedMemoBadge,
        showExtraDebtors: scope.showExtraDebtors,
        standaloneExecutionMarks: scope.standaloneExecutionMarks,
        summonsMarkerPopoverOpen: scope.summonsMarkerPopoverOpen,
        summonsPurposeDraft: scope.summonsPurposeDraft,
        thirdPartySeizureAssets: scope.thirdPartySeizureAssets,
        thirdPartySeizuresUi: scope.thirdPartySeizuresUi,
        timelineDebtorMetadata: scope.timelineDebtorMetadata,
        toggleEvictionGracePinned: scope.toggleEvictionGracePinned,
        voluntaryAttendanceCount: scope.voluntaryAttendanceCount,
        noticeVoluntaryPeriodEndOptimistic: scope.noticeVoluntaryPeriodEndOptimistic,
        voluntaryEndOptimistic: scope.voluntaryEndOptimistic,
        persistGuarantorFollowupDetails: scope.persistGuarantorFollowupDetails,
        policeAssistanceBadgeInfo: scope.policeAssistanceBadgeInfo,
        primaryDebtorAbsenceBadge: scope.primaryDebtorAbsenceBadge,
        primaryDebtorKeyResolved: scope.primaryDebtorKeyResolved,
        primaryMemoNoticeBadge: scope.primaryMemoNoticeBadge,
    };
}
