import { useMemo } from 'react';
import type { Debtor, ExecutionFile } from '@/app/types/execution';
import type { DebtorSummonsProfile } from '@/app/utils/debtorSummonsProfile';
import { buildFollowupDerivedState } from '@/app/application/execution/followup/buildFollowupDerivedState';
import { buildSubsequentNoticePolicy } from '@/app/application/execution/followup/buildSubsequentNoticePolicy';
import { buildSubsequentNoticePresentation } from '@/app/application/execution/followup/buildSubsequentNoticePresentation';
import { readExecutorDecisionsArray } from '@/app/utils/executorSeizureDecisionQueue';

export function useSubsequentNoticeFlow(
    executionData: ExecutionFile | null | undefined,
    executionId: string | undefined,
    decisionsReloadEpoch: number,
    debtorSummonsProfile: DebtorSummonsProfile | string | null,
    followupDebtorSummonsProfile: DebtorSummonsProfile | string | null,
    isEvictionExecutionModule: boolean,
    isDebtorGovernmentEmployee: boolean,
    isDebtorRetired: boolean,
    followupIsDebtorGovernmentEmployee: boolean,
    followupIsDebtorRetired: boolean,
    unifiedCollectionApproved: boolean,
    notificationCount: number,
    forcedAttendanceIssued: boolean,
    summoningRound: number,
    isEvictionGraceExpiredNow: boolean,
    isGracePeriodExpiredNow: boolean,
    debtorAttendedVoluntarily: boolean,
    voluntaryAttendanceCount: number,
    debtorNotificationDate: string | null,
    manualGraceCalendarExtra: boolean,
    lawyerStartedPostNoticeExecution: boolean,
    noticeVoluntaryPeriodEndOptimistic: boolean,
    voluntaryEndOptimistic: boolean,
    isEvictionGraceEffectivelyExpired: boolean,
    effectiveDebtors: Debtor[],
    activeCoerciveActions: string[],
    forcedPathAttendanceSecured: boolean,
    debtorForcedToAttend: boolean,
    investigationMemoIssued: boolean,
    debtorArrested: boolean,
    activeDebtorNoticeScope: { absenceBadgeDismissed?: boolean; [key: string]: unknown },
    debtorSummonsMarkerLocal: { id?: string } | null,
    monetaryExecutionStrictPathFlag: boolean,
    isAlimonyClaim: boolean,
    debtorBrowserTabsMode: boolean,
    activeWorkspaceDebtorForFollowup: { d: Debtor; isPrimary?: boolean; key?: string } | null,
    executionExtras: { perDebtorGarnishments?: Record<string, unknown>; [key: string]: unknown },
    unifiedSummonsTargetDebtorKey: string | null,
    activeDebtorIsDeceased: boolean,
    primaryDebtorKeyResolved: string | null,
    debtorNotifiedForEvictionGrace: boolean,
) {
    const policy = useMemo(
        () =>
            buildSubsequentNoticePolicy({
                debtorSummonsProfile,
                followupDebtorSummonsProfile,
                isEvictionExecutionModule,
                isDebtorGovernmentEmployee,
                isDebtorRetired,
                followupIsDebtorGovernmentEmployee,
                followupIsDebtorRetired,
                unifiedCollectionApproved,
                notificationCount,
                forcedAttendanceIssued,
                summoningRound,
                isEvictionGraceExpiredNow,
                isGracePeriodExpiredNow,
                debtorAttendedVoluntarily,
                voluntaryAttendanceCount,
                forcedPathAttendanceSecured,
                debtorForcedToAttend,
                investigationMemoIssued,
                debtorArrested,
                executionExecutorCoerciveUnlock: executionData?.executor_coercive_unlock,
                executionNoticeVoluntaryPeriodEndDeclared:
                    executionData?.notice_voluntary_period_end_declared,
                executionEvictionVoluntaryPeriodEndDeclared:
                    executionData?.eviction_voluntary_period_end_declared,
                executionEvictionLastSummonsForCollection:
                    executionData?.eviction_last_summons_for_collection,
                executionEvictionLastCollectionSummonsBranch:
                    executionData?.eviction_last_collection_summons_branch,
                noticeVoluntaryPeriodEndOptimistic,
                voluntaryEndOptimistic,
                isEvictionGraceEffectivelyExpired,
                debtorNotifiedForEvictionGrace,
                activeCoerciveActions,
                monetaryExecutionStrictPathFlag,
                isAlimonyClaim,
                activeDebtorIsDeceased,
                debtorBrowserTabsMode,
                activeWorkspaceDebtorForFollowup,
                executionGarnishmentAmount: executionData?.garnishmentAmount,
                perDebtorGarnishments: executionExtras.perDebtorGarnishments,
            }),
        [
            debtorSummonsProfile,
            followupDebtorSummonsProfile,
            isEvictionExecutionModule,
            isDebtorGovernmentEmployee,
            isDebtorRetired,
            followupIsDebtorGovernmentEmployee,
            followupIsDebtorRetired,
            unifiedCollectionApproved,
            notificationCount,
            forcedAttendanceIssued,
            summoningRound,
            isEvictionGraceExpiredNow,
            isGracePeriodExpiredNow,
            debtorAttendedVoluntarily,
            voluntaryAttendanceCount,
            forcedPathAttendanceSecured,
            debtorForcedToAttend,
            investigationMemoIssued,
            debtorArrested,
            executionData?.executor_coercive_unlock,
            executionData?.notice_voluntary_period_end_declared,
            executionData?.eviction_voluntary_period_end_declared,
            executionData?.eviction_last_summons_for_collection,
            executionData?.eviction_last_collection_summons_branch,
            noticeVoluntaryPeriodEndOptimistic,
            voluntaryEndOptimistic,
            isEvictionGraceEffectivelyExpired,
            debtorNotifiedForEvictionGrace,
            activeCoerciveActions,
            monetaryExecutionStrictPathFlag,
            isAlimonyClaim,
            activeDebtorIsDeceased,
            debtorBrowserTabsMode,
            activeWorkspaceDebtorForFollowup,
            executionData?.garnishmentAmount,
            executionExtras.perDebtorGarnishments,
        ],
    );

    const followupDerivedState = useMemo(() => {
        const ex = executionData?.id ?? executionId;
        const executorDecisionRows = ex ? readExecutorDecisionsArray(ex) : [];
        return buildFollowupDerivedState({
            executionData: executionData ?? null,
            primaryDebtorKeyResolved,
            unifiedSummonsTargetDebtorKey,
            executorDecisionRows,
        });
    }, [
        executionData,
        executionData?.employee_summons_assignments_by_debtor,
        executionData?.employee_summons_assignment,
        executionId,
        decisionsReloadEpoch,
        primaryDebtorKeyResolved,
        unifiedSummonsTargetDebtorKey,
    ]);

    const {
        anyExecutorDecisionResolvedForMemoBadge,
        primaryDebtorTaklifActive,
        resolvedEmployeeSummonsAssignment,
        showEmployeeAssignmentCoerciveBlock,
    } = followupDerivedState;

    const presentation = useMemo(
        () =>
            buildSubsequentNoticePresentation({
                notificationCount,
                subsequentNoticeUnlocked: policy.subsequentNoticeUnlocked,
                isEvictionExecutionModule,
                executionDebtorNotificationDate: executionData?.debtorNotificationDate,
                executionMemoAnchorDate: executionData?.execution_memo_anchor_date,
                executionEvictionFirstNoticeDate: executionData?.eviction_first_notice_date,
                executionNoticeVoluntaryPeriodEndDeclared:
                    executionData?.notice_voluntary_period_end_declared,
                executionEvictionVoluntaryPeriodEndDeclared:
                    executionData?.eviction_voluntary_period_end_declared,
                debtorNotificationDate,
                manualGraceCalendarExtra,
                debtorAttendedVoluntarily,
                voluntaryAttendanceCount,
                lawyerStartedPostNoticeExecution,
                noticeVoluntaryPeriodEndOptimistic,
                voluntaryEndOptimistic,
                anyExecutorDecisionResolvedForMemoBadge,
                primaryDebtorTaklifActive,
                activeDebtorNoticeScope,
                executionDebtorSummonsMarkerId: executionData?.debtor_summons_marker?.id,
                debtorSummonsMarkerLocalId: debtorSummonsMarkerLocal?.id,
                effectiveDebtors,
                isEvictionGraceExpiredNow,
                isGracePeriodExpiredNow,
            }),
        [
            notificationCount,
            policy.subsequentNoticeUnlocked,
            isEvictionExecutionModule,
            executionData?.debtorNotificationDate,
            executionData?.execution_memo_anchor_date,
            executionData?.eviction_first_notice_date,
            executionData?.notice_voluntary_period_end_declared,
            executionData?.eviction_voluntary_period_end_declared,
            debtorNotificationDate,
            manualGraceCalendarExtra,
            debtorAttendedVoluntarily,
            voluntaryAttendanceCount,
            lawyerStartedPostNoticeExecution,
            noticeVoluntaryPeriodEndOptimistic,
            voluntaryEndOptimistic,
            anyExecutorDecisionResolvedForMemoBadge,
            primaryDebtorTaklifActive,
            activeDebtorNoticeScope,
            executionData?.debtor_summons_marker?.id,
            debtorSummonsMarkerLocal?.id,
            effectiveDebtors,
            isEvictionGraceExpiredNow,
            isGracePeriodExpiredNow,
        ],
    );

    return {
        earnerForcedActionUnlocked: policy.earnerForcedActionUnlocked,
        followupEarnerForcedActionUnlocked: policy.followupEarnerForcedActionUnlocked,
        baseSubsequentNoticeUnlocked: policy.baseSubsequentNoticeUnlocked,
        evictionSubsequentNoticeUnlocked: policy.evictionSubsequentNoticeUnlocked,
        subsequentNoticeUnlocked: policy.subsequentNoticeUnlocked,
        anyExecutorDecisionResolvedForMemoBadge,
        primaryDebtorTaklifActive,
        primaryMemoNoticeBadge: presentation.primaryMemoNoticeBadge,
        primaryDebtorNoticeYmdResolved: presentation.primaryDebtorNoticeYmdResolved,
        showDebtorUnservedMemoBadge: presentation.showDebtorUnservedMemoBadge,
        shouldWarnOnMemoClick: presentation.shouldWarnOnMemoClick,
        primaryDebtorAbsenceBadge: presentation.primaryDebtorAbsenceBadge,
        showDebtorSummonsAttendanceBadge: presentation.showDebtorSummonsAttendanceBadge,
        noticeKindGoalStrictBinding: policy.noticeKindGoalStrictBinding,
        employeeAssignmentTabEnabled: policy.employeeAssignmentTabEnabled,
        resolvedEmployeeSummonsAssignment,
        showEmployeeAssignmentCoerciveBlock,
        employeeFinancialSalaryOnlyCoercive: policy.employeeFinancialSalaryOnlyCoercive,
        monetaryCoerciveLimitedOnly: policy.monetaryCoerciveLimitedOnly,
        followupEmployeeFinancialSalaryOnlyCoercive: policy.followupEmployeeFinancialSalaryOnlyCoercive,
        followupMonetaryCoerciveLimitedOnly: policy.followupMonetaryCoerciveLimitedOnly,
        followupGarnishmentAmountPreview: policy.followupGarnishmentAmountPreview,
    };
}
