import type { Dispatch, SetStateAction } from 'react';
import type { CaseStage, IncidentalStatus, Task, TimelineEvent } from '../../../LawyerShared';
import type { SmartFileParentData } from '../../smartFile/parentDataInit';

export type SmartFileMainPanelProps = {
    file: Record<string, unknown>;
    status: string;
    isViewingArchived: boolean;
    /** دعوى مربوطة للاطلاع فقط — ليست الإضبارة الأصلية */
    isCaseLinkViewOnly?: boolean;
    isPaused: boolean;
    pauseReason: string;
    isInterrupted: boolean;
    interruptionData: Record<string, unknown> | null;
    linkedCaseNo: string;
    parentData: SmartFileParentData;
    displayStage: CaseStage;
    displayTimeline: TimelineEvent[];
    currentStage: CaseStage;
    stages: CaseStage[];
    activeStageIndex: number;
    viewingStageIndex: number;
    isPleadingsClosed: boolean | undefined;
    lastJudgmentType: string | undefined;
    onTouchStart: (e: React.TouchEvent) => void;
    onTouchMove: (e: React.TouchEvent) => void;
    onTouchEnd: (e: React.TouchEvent) => void;
    handleResumeAbandonment: (data?: { nextHearingDate?: string }) => void;
    handleResume: (data?: { nextHearingDate?: string }) => void;
    handleToggleClient: () => void;
    handleStageSelect: (stageId: string) => void;
    handleInterruptionToggle: () => void;
    handleAbandonment: () => void;
    handlePetitionVoidAppeal: () => void;
    handlePetitionVoidOutcome: (outcome: 'upheld' | 'quashed') => void;
    handleToggleNotification: () => void;
    handleCassationDecision: (decision: 'ratified' | 'quashed') => void;
    handleClosePleadings: () => void;
    handleReopenPleadings: () => void;
    handleOpenDefendantCassationAppeal: () => void;
    handleDefaultObjection: () => void;
    handleWaiveObjection: () => void;
    handleOpponentAppealWaived: () => void;
    handleOtherAppeals: () => void;
    onAbsentJudgmentNotification?: () => void;
    onOpponentAbsentObjection?: () => void;
    handleExportPDF: () => void;
    setShowAppealModal: (v: boolean) => void;
    setShowProvisionalOrderModal: (v: boolean) => void;
    handleResolveIncidentalCase: (id: string, status: IncidentalStatus) => void;
    handleUpdateIncidentalEntryDecision?: (id: string, decision: 'accepted' | 'rejected') => void;
    setShowIncidentalModal: (v: boolean) => void;
    setShowDocModal: (v: boolean) => void;
    setShowApptModal: (v: boolean) => void;
    setIsActionsMenuOpen: (v: boolean) => void;
    handleQuickAction: (action: string) => void;
    setShowPauseModal: (v: boolean) => void;
    setShowResumeInterruptionModal: (v: boolean) => void;
    setShowAbandonmentRenewalModal: (v: boolean) => void;
    setShowPauseResumeModal: (v: boolean) => void;
    setShowNotificationModal: (v: boolean) => void;
    setShowPaymentModal: (v: boolean) => void;
    setParentData: Dispatch<SetStateAction<SmartFileParentData>>;
    setShowTaskModal: (v: boolean) => void;
    handleToggleTask: (taskId: string) => void;
    handleAppealBriefFile?: (taskId: string, decisionNo: string, decisionDate: string) => void;
    handleAppealBriefOutcome?: (taskId: string, outcome: 'quashed' | 'upheld') => void;
    handleCorrespondenceResponse?: (taskId: string, received: boolean) => void;
    setEditingTask: (t: Task | null) => void;
    setEditingFastTrack: (v: Record<string, unknown> | null) => void;
    setShowFastTrackModal: (v: boolean) => void;
    setEditingAttachment: (v: Record<string, unknown> | null) => void;
    setShowAttachmentModal: (v: boolean) => void;
    handleDeleteEvent: (eventId: string) => void;
    handleEditEvent: (eventId: string) => void;
    handleAddAction: (data: Record<string, unknown>) => void;
    handleSaveFastTrack: (data: Record<string, unknown>) => void;
    editingEvent: TimelineEvent | null;
    setEditingEvent: (event: TimelineEvent | null) => void;
    setShowCrossAppealModal: (v: boolean) => void;
    setShowJudgmentModal: (v: boolean) => void;
    handleCancelCrossAppeal: () => void;
    handleAddCrossAppeal: () => void;
    stepperStages: unknown[];
    currentStageId: string;
    onOpenLinkedFile?: (linkedFileId: number, linkedCriminalId?: string) => void;
    onUnlinkCaseLink?: (peer: { peerFileId?: number; peerCriminalId?: string }) => void;
    lawsuitFiles?: import('../../../LawyerShared').FileData[];
};
