import type { LifecyclePanelProps } from '../layout/LifecyclePanelProps';
import type { CassationLifecyclePanelProps } from './CassationLifecyclePanelProps';
import type { GrievanceLifecyclePanelProps } from './GrievanceLifecyclePanelProps';
import type { JudgeDecisionLifecyclePanelProps } from './JudgeDecisionLifecyclePanelProps';

function pick<K extends keyof LifecyclePanelProps>(
    source: LifecyclePanelProps,
    keys: readonly K[],
): Pick<LifecyclePanelProps, K> {
    const out = {} as Pick<LifecyclePanelProps, K>;
    for (const key of keys) {
        out[key] = source[key];
    }
    return out;
}

const JUDGE_KEYS = [
    'activeLifecycleStep',
    'addHearing',
    'clearJudgeDecision',
    'defenderPhase1ReadOnly',
    'defenderStateOrderSummaryDate',
    'editJudge',
    'effectiveJudgeDecision',
    'effectiveJudgeDecisionDate',
    'fastForwardToGrievance',
    'fileStatus',
    'guaranteeDetails',
    'guaranteeSubmitted',
    'handleJudgeDecisionSubmit',
    'hasIntervention',
    'hasSessions',
    'hearingDraft',
    'hearingDraftAdjournReasonError',
    'hearingDraftNextSessionDateError',
    'hearingDraftSessionDateError',
    'hearingsError',
    'intakeFirstHearingDate',
    'isAdjourned',
    'isCaseTerminated',
    'isDefendantClient',
    'isFinalityTerminatedRequest',
    'isFinalized',
    'isIqrarContext',
    'isStateOrder',
    'judgeDecision',
    'judgeDecisionDateChronologyError',
    'judgeError',
    'phase1ActiveDate',
    'phase1JudgeDecisionMinYmd',
    'phase1NewSessionMinYmd',
    'phase1Sessions',
    'preDecisionHearingsSorted',
    'preDecisionTerminalKind',
    'registerOpponentIntervention',
    'setGuaranteeDetails',
    'setGuaranteeSubmitted',
    'setHearingDraft',
    'setJudgeDecision',
    'showGrievanceStep',
    'showJudgeDecisionBlock',
    'showJudgeDecisionFullForm',
    'showJudgeDecisionTerminateOnly',
    'showPreDecisionHearings',
    'toggleLifecycleStep',
] as const satisfies readonly (keyof JudgeDecisionLifecyclePanelProps)[];

const GRIEVANCE_KEYS = [
    'activeLifecycleStep',
    'addHearing',
    'caseData',
    'clearGrievance',
    'computedGrievanceFiledBy',
    'confirmGrievanceDetails',
    'confirmGrievanceTiming',
    'defenderPhase2ReadOnly',
    'defenderStateOrderSummaryDate',
    'editGrievance',
    'effectiveJudgeDecisionDate',
    'effectiveRejectionNotificationDate',
    'grievanceData',
    'grievanceDecision',
    'grievanceDecisionDateChronologyError',
    'grievanceDecisionError',
    'grievanceDecisionMinYmd',
    'grievanceDecisionNotificationConfirmed',
    'grievanceError',
    'grievanceExpiredCanClose',
    'grievanceExpiredConfirmed',
    'grievanceFilingDateChronologyError',
    'grievanceFilingMinYmd',
    'grievanceFinalGateRef',
    'grievanceFirstHearingDateChronologyError',
    'grievanceFirstHearingMinYmd',
    'grievanceHearingsGateRef',
    'grievanceHearingsSorted',
    'grievanceInHearings',
    'grievanceLegalEndDate',
    'grievanceLegalEndDateChronologyError',
    'grievanceLegalEndMinYmd',
    'grievanceLockedSummaryText',
    'grievanceOutcomeGateRef',
    'grievanceProceedingsClosed',
    'grievanceRef',
    'grievanceStepNumber',
    'grievanceTimingConfirmed',
    'grievanceTimingGateReady',
    'grievanceWizardInputsLocked',
    'handleGrievanceSubmit',
    'hasIntervention',
    'hearingDraft',
    'hearingDraftAdjournReasonError',
    'hearingDraftNextSessionDateError',
    'hearingDraftSessionDateError',
    'hearingsError',
    'isFinalityNoGrievance',
    'isFinalized',
    'partyLabel',
    'persistGrievanceOutcomeDraft',
    'phase2ActiveDate',
    'phase2FirstHearingDate',
    'phase2NewSessionMinYmd',
    'setActiveLifecycleStep',
    'setDecisionNotificationModalOpen',
    'setEditGrievance',
    'setGrievanceData',
    'setGrievanceDecision',
    'setGrievanceDetailsConfirmed',
    'setGrievanceExpiredConfirmed',
    'setGrievanceLegalEndDate',
    'setHearingDraft',
    'setPhase2FirstHearingDate',
    'showGrievanceDecisionForm',
    'showGrievanceDetailsForm',
    'showGrievanceDetailsSummary',
    'showGrievanceFinalizeButton',
    'showGrievanceOutcomeForm',
    'showGrievanceOutcomeSummary',
    'showGrievancePhase2AdjournBanner',
    'showGrievanceTimingForm',
    'showGrievanceTimingSummary',
    'toggleLifecycleStep',
    'updatePhase2FirstHearingDate',
] as const satisfies readonly (keyof GrievanceLifecyclePanelProps)[];

const CASSATION_KEYS = [
    'activeLifecycleStep',
    'addHearing',
    'caseData',
    'cassationData',
    'cassationDecision',
    'cassationDecisionDateError',
    'cassationDecisionError',
    'cassationDecisionGateRef',
    'cassationDecisionMinYmd',
    'cassationError',
    'cassationExpiredCanClose',
    'cassationExpiredConfirmed',
    'cassationFilingAfterDeadline',
    'cassationFilingDateChronologyError',
    'cassationFilingGateRef',
    'cassationFilingMinYmd',
    'cassationLegalEndDate',
    'cassationPhaseFinalizeReady',
    'cassationRef',
    'cassationStepNumber',
    'clearCassation',
    'computedCassationFiledBy',
    'defenderPhase2ReadOnly',
    'editCassation',
    'effectiveRejectionNotificationDate',
    'grievanceWizardInputsLocked',
    'handleCassationPhaseSubmit',
    'hasIntervention',
    'hearingDraft',
    'hearingDraftAdjournReasonError',
    'hearingDraftNextSessionDateError',
    'hearingDraftSessionDateError',
    'isFinalized',
    'partyLabel',
    'persistGrievanceOutcomeDraft',
    'phase2ActiveDate',
    'phase2NewSessionMinYmd',
    'setActiveLifecycleStep',
    'setCassationData',
    'setCassationDecision',
    'setCassationExpiredConfirmed',
    'setEditCassation',
    'setHearingDraft',
    'showCassationDecisionPanel',
    'showGrievanceStep',
    'toggleLifecycleStep',
] as const satisfies readonly (keyof CassationLifecyclePanelProps)[];

export function pickJudgeDecisionLifecyclePanelProps(
    props: LifecyclePanelProps,
): JudgeDecisionLifecyclePanelProps {
    return pick(props, JUDGE_KEYS);
}

export function pickGrievanceLifecyclePanelProps(props: LifecyclePanelProps): GrievanceLifecyclePanelProps {
    return pick(props, GRIEVANCE_KEYS);
}

export function pickCassationLifecyclePanelProps(props: LifecyclePanelProps): CassationLifecyclePanelProps {
    return pick(props, CASSATION_KEYS);
}
