export {
    BOOT_DEFAULT_SETTINGS,
    EnsureLawyerSettingsProvider,
    homeLayoutStableKey,
    LawyerSettingsProvider,
    loadInitialSettingsAsync,
    readProviderBootSettings,
    settingsHydrateEqual,
    stripWallpaperForStorage,
    useLawyerSettings,
    useLawyerSettingsActions,
    useLawyerSettingsAppearance,
    useLawyerSettingsData,
    useLawyerSettingsFromSlices,
    useLawyerSettingsHomeLayout,
    useLawyerSettingsOptional,
    useLawyerSettingsPerformance,
    useLawyerSettingsPushAllowed,
    useLawyerSettingsReset,
    useLawyerSettingsSecurity,
} from './lawyerSettings';
export type { LawyerSettingsActionsValue, LawyerSettingsContextValue } from './lawyerSettings';
