import type { CommunityScreenOverlayPropSlice } from './communityScreenPropBuilderContext';
import type { AssembleCommunityScreenPropContextParams } from './assembleCommunityScreenPropContext.types';

export function assembleCommunityScreenOverlayPropSlice(
    params: AssembleCommunityScreenPropContextParams,
): CommunityScreenOverlayPropSlice {
    const { activePostForComments, mutedIds, shell, socialGraph, groupsFeed, searchOverlay, addQuestion, postActions, postModeration, interactions } =
        params;
    return {
        openAddQuestion: addQuestion.openAddQuestion,
        activePostForComments,
        mutedIds,
        forumMentionCandidates: socialGraph.forumMentionCandidates,
        setCommentingPostId: shell.setCommentingPostId,
        handleAddComment: postActions.handleAddComment,
        handleToggleBestAnswer: postActions.handleToggleBestAnswer,
        handleDeleteComment: postActions.handleDeleteComment,
        handleEditComment: postActions.handleEditComment,
        handleToggleCommentUpvote: postActions.handleToggleCommentUpvote,
        handleReportComment: postActions.handleReportComment,
        isSearchOpen: searchOverlay.isSearchOpen,
        searchQuery: searchOverlay.searchQuery,
        setSearchQuery: searchOverlay.setSearchQuery,
        filterHasPdf: searchOverlay.filterHasPdf,
        setFilterHasPdf: searchOverlay.setFilterHasPdf,
        filterHasImage: searchOverlay.filterHasImage,
        setFilterHasImage: searchOverlay.setFilterHasImage,
        selectedTag: searchOverlay.selectedTag,
        setSelectedTag: searchOverlay.setSelectedTag,
        allSearchTags: searchOverlay.allSearchTags,
        filteredPosts: searchOverlay.filteredPosts,
        filteredRepositoryDocs: searchOverlay.filteredRepositoryDocs,
        handleSearchOpenPost: interactions.handleSearchOpenPost,
        handleSearchOpenDocument: interactions.handleSearchOpenDocument,
        isAddQuestionOpen: addQuestion.isAddQuestionOpen,
        newPostText: addQuestion.newPostText,
        setNewPostText: addQuestion.setNewPostText,
        newTagText: addQuestion.newTagText,
        setNewTagText: addQuestion.setNewTagText,
        newIsAnonymous: addQuestion.newIsAnonymous,
        setNewIsAnonymous: addQuestion.setNewIsAnonymous,
        newIsUrgent: addQuestion.newIsUrgent,
        setNewIsUrgent: addQuestion.setNewIsUrgent,
        newAttachment: addQuestion.newAttachment,
        removeAttachment: addQuestion.removeAttachment,
        submittingPost: addQuestion.submittingPost,
        isRecordingVoice: addQuestion.isRecordingVoice,
        voiceRecordingSec: addQuestion.voiceRecordingSec,
        imageInputRef: addQuestion.imageInputRef,
        docInputRef: addQuestion.docInputRef,
        toggleVoiceRecording: addQuestion.toggleVoiceRecording,
        handleUploadAttachment: addQuestion.handleUploadAttachment,
        handleAddPost: addQuestion.handleAddPost,
        closeAddQuestion: addQuestion.closeAddQuestion,
        isCreateGroupOpen: groupsFeed.isCreateGroupOpen,
        newGroupName: groupsFeed.newGroupName,
        newGroupDesc: groupsFeed.newGroupDesc,
        submittingGroup: groupsFeed.submittingGroup,
        setNewGroupName: groupsFeed.setNewGroupName,
        setNewGroupDesc: groupsFeed.setNewGroupDesc,
        handleCreateGroup: groupsFeed.handleCreateGroup,
        editingPostId: postModeration.editingPostId,
        editingText: postModeration.editingText,
        setEditingText: postModeration.setEditingText,
        handleSaveEdit: postModeration.handleSaveEdit,
        setEditingPostId: postModeration.setEditingPostId,
        savingEdit: postModeration.savingEdit,
        pendingDeletePostId: postActions.pendingDeletePostId,
        pendingDeletePost: postActions.pendingDeletePost,
        deletingPost: postActions.deletingPost,
        confirmDeletePost: postActions.confirmDeletePost,
        cancelDeletePostRequest: postActions.cancelDeletePostRequest,
        profileView: shell.profileView,
        closeForumProfile: interactions.closeForumProfile,
        followBusyUserId: socialGraph.followBusyUserId,
    };
}
