import type { CommunityScreenOverlaysProps } from '../components/CommunityScreenOverlays.types';
import type { CommunityScreenPropBuilderContext } from './communityScreenPropBuilderContext';

export function buildCommunityScreenOverlayProps(
    ctx: CommunityScreenPropBuilderContext,
): CommunityScreenOverlaysProps {
    return {
        activePostForComments: ctx.activePostForComments,
        currentUserId: ctx.currentUserId,
        isAdmin: ctx.isAdmin,
        followingIds: ctx.followingIds,
        userStats: ctx.userStats,
        mutedIds: ctx.mutedIds,
        forumMentionCandidates: ctx.forumMentionCandidates,
        onCloseComments: () => ctx.setCommentingPostId(null),
        onAddComment: ctx.handleAddComment,
        onToggleBestAnswer: ctx.handleToggleBestAnswer,
        onDeleteComment: ctx.handleDeleteComment,
        onEditComment: ctx.handleEditComment,
        onFollow: ctx.handleFollow,
        onToggleCommentUpvote: ctx.handleToggleCommentUpvote,
        onReportComment: ctx.handleReportComment,
        onMuteUser: ctx.handleMuteUser,
        onOpenProfile: ctx.openForumProfile,
        isSearchOpen: ctx.isSearchOpen,
        searchQuery: ctx.searchQuery,
        onSearchQueryChange: ctx.setSearchQuery,
        filterHasPdf: ctx.filterHasPdf,
        onFilterHasPdfChange: ctx.setFilterHasPdf,
        filterHasImage: ctx.filterHasImage,
        onFilterHasImageChange: ctx.setFilterHasImage,
        selectedTag: ctx.selectedTag,
        onSelectedTagChange: ctx.setSelectedTag,
        allSearchTags: ctx.allSearchTags,
        filteredPosts: ctx.filteredPosts,
        filteredRepositoryDocs: ctx.filteredRepositoryDocs,
        onCloseSearch: () => ctx.closeSearchOverlay(),
        onOpenPost: ctx.handleSearchOpenPost,
        onOpenDocument: ctx.handleSearchOpenDocument,
        isAddQuestionOpen: ctx.isAddQuestionOpen,
        newPostText: ctx.newPostText,
        onNewPostTextChange: ctx.setNewPostText,
        newTagText: ctx.newTagText,
        onNewTagTextChange: ctx.setNewTagText,
        newIsAnonymous: ctx.newIsAnonymous,
        onNewIsAnonymousChange: ctx.setNewIsAnonymous,
        newIsUrgent: ctx.newIsUrgent,
        onNewIsUrgentChange: ctx.setNewIsUrgent,
        newAttachment: ctx.newAttachment,
        onRemoveAttachment: ctx.removeAttachment,
        submittingPost: ctx.submittingPost,
        isRecordingVoice: ctx.isRecordingVoice,
        voiceRecordingSec: ctx.voiceRecordingSec,
        imageInputRef: ctx.imageInputRef,
        docInputRef: ctx.docInputRef,
        onToggleVoiceRecording: () => void ctx.toggleVoiceRecording(),
        onImageUpload: (file) => ctx.handleUploadAttachment(file, 'image'),
        onDocUpload: (file) => ctx.handleUploadAttachment(file, 'document'),
        onSubmitPost: () => void ctx.handleAddPost(),
        onCloseAddQuestion: ctx.closeAddQuestion,
        isCreateGroupOpen: ctx.isCreateGroupOpen,
        newGroupName: ctx.newGroupName,
        newGroupDesc: ctx.newGroupDesc,
        submittingGroup: ctx.submittingGroup,
        onNewGroupNameChange: ctx.setNewGroupName,
        onNewGroupDescChange: ctx.setNewGroupDesc,
        onSubmitCreateGroup: () => void ctx.handleCreateGroup(),
        onCloseCreateGroup: () => {
            if (ctx.submittingGroup) return;
            ctx.setIsCreateGroupOpen(false);
        },
        editingPostId: ctx.editingPostId,
        editingText: ctx.editingText,
        onEditingTextChange: ctx.setEditingText,
        onSaveEdit: () => void ctx.handleSaveEdit(),
        onCancelEdit: () => {
            ctx.setEditingPostId(null);
            ctx.setEditingText('');
        },
        savingEdit: ctx.savingEdit,
        pendingDeletePostId: ctx.pendingDeletePostId,
        pendingDeletePost: ctx.pendingDeletePost,
        deletingPost: ctx.deletingPost,
        onConfirmDeletePost: () => void ctx.confirmDeletePost(),
        onCancelDeletePost: () => {
            if (!ctx.deletingPost) ctx.cancelDeletePostRequest();
        },
        profileView: ctx.profileView,
        onCloseProfile: ctx.closeForumProfile,
        followBusyUserId: ctx.followBusyUserId,
    };
}
