import type { MutableRefObject, RefObject } from 'react';
import type { CommunityPost, RepositoryDocument } from '@/app/services/lawyer-cloud';
import type { ForumFollowRecord } from '@/app/services/forum/forumFollowTypes';
import type { ForumGroup } from '@/app/services/forum/forumGroupTypes';
import type { ForumParticipant } from '@/app/services/forum/forumMentionUtils';
import type { CommunitySection } from '../communitySectionState';
import type { CommunityScreenBodyProps } from '../components/CommunityScreenBody.types';
import type { CommunityScreenOverlaysProps } from '../components/CommunityScreenOverlays.types';

export type CommunityScreenChromePropSlice = {
    onBack?: () => void;
    forumSurfaceOpen: boolean;
    activeSection: CommunitySection;
    setActiveSection: (section: CommunitySection) => void;
    setIsSearchOpen: (open: boolean) => void;
    openSearchOverlay: () => void;
    closeSearchOverlay: () => void;
    handleNavigateToPost: (postId: string) => void;
    currentUserId: string | null;
    isBanned: boolean;
    selectedFilterIndex: number;
    setSelectedFilterIndex: (index: number) => void;
    repositorySearchTerm: string;
    setRepositorySearchTerm: (value: string) => void;
    repositorySortBy: CommunityScreenBodyProps['repositorySortBy'];
    setRepositorySortBy: CommunityScreenBodyProps['onRepositorySortChange'];
    repositorySelectedType: string;
    setRepositorySelectedType: (value: string) => void;
    repositorySelectedTag: string | null;
    setRepositorySelectedTag: (value: string | null) => void;
    followingRecords: ForumFollowRecord[];
    setShowFollowingPanel: (open: boolean) => void;
    forumFeedScope: 'all' | 'following';
    setForumFeedScope: (scope: 'all' | 'following') => void;
    forumStreamConnected: boolean;
    setForumAppBarDropdownOpen: (open: boolean) => void;
    closeAppBarDropdownsRef: MutableRefObject<(() => void) | null>;
    showFollowingPanel: boolean;
    followerRecords: Array<{ followerId: string; createdAt: string }>;
    followingAuthorNames: Record<string, string>;
    handleFollow: (id: string) => void;
    handleUpdateFollowPrefs: (
        id: string,
        prefs: Partial<Pick<ForumFollowRecord, 'notifyPosts' | 'notifyComments' | 'notifyReplies'>>,
    ) => void;
    openForumProfile: (userId: string, displayName?: string) => void;
};

export type CommunityScreenFeedPropSlice = {
    loadingPosts: boolean;
    hasMore: boolean;
    loadingMore: boolean;
    visiblePosts: CommunityPost[];
    isAdmin: boolean;
    handleToggleUpvote: (postId: string) => void;
    openCommentSheet: (postId: string) => void;
    requestDeletePost: (postId: string) => void;
    handleEditPost: (postId: string) => void;
    handleReportPost: (postId: string) => void;
    handleSharePost: (postId: string) => void;
    handleLoadMore: () => void;
    handleTogglePin: (postId: string) => void;
    followingIds: Set<string>;
    bookmarkedIds: Set<string>;
    handleToggleBookmark: (postId: string) => void;
    handleCopyPostText: (postId: string) => void;
    handleSavePostToVault: (postId: string) => void;
    handleSavePostToDevice: (postId: string) => void;
    handleToggleLock: (postId: string) => void;
    handleMuteUser: (userId: string) => void;
    userStats: Record<string, { followerCount: number; postCount: number }>;
    threadFollowingIds: Set<string>;
    handleToggleThreadFollow: (id: string) => void;
    activeGroupId: string | null;
    activeGroup: ForumGroup | null;
    handleLeaveGroup: () => void;
    leavingGroup: boolean;
    groupPostsLoading: boolean;
    groupPostsHasMore: boolean;
    groupPostsLoadingMore: boolean;
    groupVisiblePosts: CommunityPost[];
    handleLoadMoreGroupPosts: () => void;
    setActiveGroupId: (id: string | null) => void;
    groups: ForumGroup[];
    groupsLoading: boolean;
    groupsSearchQuery: string;
    setGroupsSearchQuery: (value: string) => void;
    handleJoinGroup: (groupId: string) => void;
    handleOpenGroup: (groupId: string) => void;
    setIsCreateGroupOpen: (open: boolean) => void;
    joiningGroupId: string | null;
};

export type CommunityScreenOverlayPropSlice = {
    openAddQuestion: () => void;
    activePostForComments: CommunityPost | null;
    mutedIds: Set<string>;
    forumMentionCandidates: ForumParticipant[];
    setCommentingPostId: (id: string | null) => void;
    handleAddComment: CommunityScreenOverlaysProps['onAddComment'];
    handleToggleBestAnswer: (postId: string, commentId: string) => void;
    handleDeleteComment: (postId: string, commentId: string) => void;
    handleEditComment: (postId: string, commentId: string, content: string) => void;
    handleToggleCommentUpvote: (commentId: string) => void;
    handleReportComment: (commentId: string) => void;
    isSearchOpen: boolean;
    searchQuery: string;
    setSearchQuery: (value: string) => void;
    filterHasPdf: boolean;
    setFilterHasPdf: (value: boolean) => void;
    filterHasImage: boolean;
    setFilterHasImage: (value: boolean) => void;
    selectedTag: string | null;
    setSelectedTag: (value: string | null) => void;
    allSearchTags: string[];
    filteredPosts: CommunityPost[];
    filteredRepositoryDocs: RepositoryDocument[];
    handleSearchOpenPost: (postId: string) => void;
    handleSearchOpenDocument: (doc: RepositoryDocument) => void;
    isAddQuestionOpen: boolean;
    newPostText: string;
    setNewPostText: (value: string) => void;
    newTagText: string;
    setNewTagText: (value: string) => void;
    newIsAnonymous: boolean;
    setNewIsAnonymous: (value: boolean) => void;
    newIsUrgent: boolean;
    setNewIsUrgent: (value: boolean) => void;
    newAttachment: CommunityPost['attachment'];
    removeAttachment: () => void;
    submittingPost: boolean;
    isRecordingVoice: boolean;
    voiceRecordingSec: number;
    imageInputRef: RefObject<HTMLInputElement | null>;
    docInputRef: RefObject<HTMLInputElement | null>;
    toggleVoiceRecording: () => void;
    handleUploadAttachment: (file: File, kind: 'image' | 'document') => void;
    handleAddPost: () => void;
    closeAddQuestion: () => void;
    isCreateGroupOpen: boolean;
    newGroupName: string;
    newGroupDesc: string;
    submittingGroup: boolean;
    setNewGroupName: (value: string) => void;
    setNewGroupDesc: (value: string) => void;
    handleCreateGroup: () => void;
    editingPostId: string | null;
    editingText: string;
    setEditingText: (value: string) => void;
    handleSaveEdit: () => void;
    setEditingPostId: (id: string | null) => void;
    savingEdit: boolean;
    pendingDeletePostId: string | null;
    pendingDeletePost: CommunityPost | null;
    deletingPost: boolean;
    confirmDeletePost: () => void;
    cancelDeletePostRequest: () => void;
    profileView: { userId: string; displayName?: string } | null;
    closeForumProfile: () => void;
    followBusyUserId: string | null;
};

export type CommunityScreenPropBuilderContext = CommunityScreenChromePropSlice &
    CommunityScreenFeedPropSlice &
    CommunityScreenOverlayPropSlice;
