// @ts-nocheck
/** Phase C Slice 21 — تجميع rest bundles لحقائب chunk scope */
import { FollowupModalContext } from '../../followupModalContext';
import {
    executionDashboardCoreQueueMicrotask,
    executionDashboardCoreStaticScopeFns,
} from './executionDashboardCoreStaticScopeFns';

export function buildExecutionDashboardCoreScopeRestBundles(input: Record<string, unknown>) {
    return {
        executionDashboardCoreStaticScopeFns,
        executionDashboardCoreQueueMicrotask,
        scopeRuntimeFnsBundle: {
            getMilestoneTimelineSnapshot: input.getMilestoneTimelineSnapshot,
            todayYmd: input.todayYmd,
        },
        evictionProceduresHandlers: {
            appendEvictionExecutorRequest: input.appendEvictionExecutorRequest,
            appendEvictionProcedure: input.appendEvictionProcedure,
        },
        summonsNoticeBundle: {
            setDebtorNotificationDate: input.setDebtorNotificationDate,
            setDebtorSummonsMarkerLocal: input.setDebtorSummonsMarkerLocal,
            debtorNotificationDate: input.debtorNotificationDate,
            debtorSummonsMarkerLocal: input.debtorSummonsMarkerLocal,
            setSummonsMarkerPopoverOpen: input.setSummonsMarkerPopoverOpen,
            setSummonsPurposeDraft: input.setSummonsPurposeDraft,
            summonsMarkerPopoverOpen: input.summonsMarkerPopoverOpen,
            summonsPurposeDraft: input.summonsPurposeDraft,
            notificationCount: input.notificationCount,
            noticeVoluntaryPeriodEndOptimistic: input.noticeVoluntaryPeriodEndOptimistic,
            voluntaryEndOptimistic: input.voluntaryEndOptimistic,
            dismissDebtorAbsenceBadge: input.dismissDebtorAbsenceBadge,
            syncRollingCalendarSessions: input.syncRollingCalendarSessions,
        },
        evictionGraceUiBundle: {
            evictionFullAddressField: input.evictionFullAddressField,
            evictionGraceBadgeInfo: input.evictionGraceBadgeInfo,
            evictionGraceHidden: input.evictionGraceHidden,
            evictionGracePinned: input.evictionGracePinned,
            evictionPremisesUseResolved: input.evictionPremisesUseResolved,
            evictionProcedureLockHint: input.evictionProcedureLockHint,
            evictionPropertyDistrict: input.evictionPropertyDistrict,
            evictionPropertyNumber: input.evictionPropertyNumber,
            evictionPropertyTypeField: input.evictionPropertyTypeField,
            graceHiddenKey: input.graceHiddenKey,
            gracePeriodEnded: input.gracePeriodEnded,
            residentialGraceAllowsFieldwork: input.residentialGraceAllowsFieldwork,
            residentialGracePeriodSaved: input.residentialGracePeriodSaved,
            residentialVacateDeadlineMaxIso: input.residentialVacateDeadlineMaxIso,
            showResidentialEvictionGraceControl: input.showResidentialEvictionGraceControl,
            showResidentialGraceEarlyEndRequest: input.showResidentialGraceEarlyEndRequest,
            toggleEvictionGracePinned: input.toggleEvictionGracePinned,
            setEvictionGraceHidden: input.setEvictionGraceHidden,
        },
        coerciveModalUiBundle: {
            activeCoerciveActions: input.activeCoerciveActions,
            setActiveCoerciveActions: input.setActiveCoerciveActions,
            saveCoerciveActionRef: input.saveCoerciveActionRef,
            setShowCoerciveActionForm: input.setShowCoerciveActionForm,
            setShowCoerciveModal: input.setShowCoerciveModal,
            showCoerciveModal: input.showCoerciveModal,
        },
        modalFlagsBundle: {
            showBreakInventoryRequest: input.showBreakInventoryRequest,
            showExecutionTrashModal: input.showExecutionTrashModal,
            showExtraCreditors: input.showExtraCreditors,
            showExtraDebtors: input.showExtraDebtors,
            showJudgmentMeta: input.showJudgmentMeta,
            showToast: input.showToast,
            setShowExecutionTrashModal: input.setShowExecutionTrashModal,
            setShowExtraCreditors: input.setShowExtraCreditors,
            setShowExtraDebtors: input.setShowExtraDebtors,
            setShowUnifiedSummonsModal: input.setShowUnifiedSummonsModal,
            setIsPaused: input.setIsPaused,
            setPauseReason: input.setPauseReason,
            setManualGraceCalendarExtra: input.setManualGraceCalendarExtra,
        },
        followupModalDerivedBundle: {
            followupModalDebtorIsDeceased: input.followupModalDebtorIsDeceased,
            followupModalDebtorIsEmployee: input.followupModalDebtorIsEmployee,
            followupModalSpecializationEffectiveWithEarnerGate:
                input.followupModalSpecializationEffectiveWithEarnerGate,
            followupSpecializationWithEarnerGate: input.followupSpecializationWithEarnerGate,
            modalKasabTerminationEmphasis: input.modalKasabTerminationEmphasis,
            modalResolvedEmployeeSummonsAssignment: input.modalResolvedEmployeeSummonsAssignment,
            modalShowEmployeeAssignmentCoerciveBlock: input.modalShowEmployeeAssignmentCoerciveBlock,
        },
        claimDisplayBundle: {
            claimType: input.claimType,
            claimTypeArabicDisplay: input.claimTypeArabicDisplay,
            classificationDisplay: input.classificationDisplay,
            headerFields: input.headerFields,
            judgmentDateDisplay: input.judgmentDateDisplay,
            parentClaimTypeArabicDisplay: input.parentClaimTypeArabicDisplay,
            parentClassificationDisplay: input.parentClassificationDisplay,
            parentHeaderFields: input.parentHeaderFields,
            parentJudgmentDateDisplay: input.parentJudgmentDateDisplay,
            parentShowJudgmentMeta: input.parentShowJudgmentMeta,
            parsedClientFees: input.parsedClientFees,
            parsedCourtFees: input.parsedCourtFees,
            parsedDirectorateFees: input.parsedDirectorateFees,
            parsedLawyerFees: input.parsedLawyerFees,
            partyBadgesExecutionId: input.partyBadgesExecutionId,
            initiator: input.initiator,
            appealPerspective: input.appealPerspective,
            isPersonalStatusExecutionClaim: input.isPersonalStatusExecutionClaim,
            isRepresentingDebtor: input.isRepresentingDebtor,
            isUnifiedTabActive: input.isUnifiedTabActive,
            hideCoerciveTabsForDebtorAgent: input.hideCoerciveTabsForDebtorAgent,
            hideExecutiveDetentionJudgeCard: input.hideExecutiveDetentionJudgeCard,
            shouldShowGuarantorExternalHub: input.shouldShowGuarantorExternalHub,
            kasabTerminationEmphasis: input.kasabTerminationEmphasis,
            firstActiveAppealDecisionId: input.firstActiveAppealDecisionId,
            daysRemainingUntilDeadline: input.daysRemainingUntilDeadline,
        },
        partyDeathLabelsBundle: {
            creditorDeathMenuLabel: input.creditorDeathMenuLabel,
            creditorExtraMinorLabel: input.creditorExtraMinorLabel,
            creditorExtraMinorNames: input.creditorExtraMinorNames,
            debtorDeathMenuLabel: input.debtorDeathMenuLabel,
            debtorEmploymentToggleMenuLabel: input.debtorEmploymentToggleMenuLabel,
        },
        debtorProfileBundle: {
            activeDebtorIsDeceased: input.activeDebtorIsDeceased,
            activeDebtorIsEmployee: input.activeDebtorIsEmployee,
            activeDebtorIsLegalEntity: input.activeDebtorIsLegalEntity,
            debtorEvaded: input.debtorEvaded,
            employeeForcedBringAwaitingPersonalOutcome: input.employeeForcedBringAwaitingPersonalOutcome,
            isDebtorRowEmployee: input.isDebtorRowEmployee,
        },
        masterStateBundle: {
            statusMetadata: input.statusMetadata,
            forcedBringDecisionState: input.forcedBringDecisionState,
            forcedAttendanceIssued: input.forcedAttendanceIssued,
            stayOfExecutionActive: input.stayOfExecutionActive,
            statuteStatus: input.statuteStatus,
            standaloneExecutionMarks: input.standaloneExecutionMarks,
            unifiedCollectionApproved: input.unifiedCollectionApproved,
            isPaused: input.isPaused,
            pauseReason: input.pauseReason,
            permanentDeleteTimelineId: input.permanentDeleteTimelineId,
            setPermanentDeleteTimelineId: input.setPermanentDeleteTimelineId,
            isHistoricalMode: input.isHistoricalMode,
            isAssignmentDeadlinePassed: input.isAssignmentDeadlinePassed,
            activeGraceTasks: input.activeGraceTasks,
            policeAssistanceBadgeInfo: input.policeAssistanceBadgeInfo,
            publicationNoticeDeadlineYmd: input.publicationNoticeDeadlineYmd,
        },
        inabaBundle: {
            inabaCorrespondenceLog: input.inabaCorrespondenceLog,
            inabaTargets: input.inabaTargets,
            isInabaActive: input.isInabaActive,
        },
        executorScheduleBundle: {
            executorScheduleContext: input.executorScheduleContext,
            executorScheduleModalOpen: input.executorScheduleModalOpen,
            setExecutorScheduleContext: input.setExecutorScheduleContext,
            setExecutorScheduleModalOpen: input.setExecutorScheduleModalOpen,
            setExecutionStorageTick: input.setExecutionStorageTick,
            setExecutionReportPrompt: input.setExecutionReportPrompt,
            setExecutionMemoBadgePopoverOpen: input.setExecutionMemoBadgePopoverOpen,
        },
        breakInventoryModalBundle: {
            breakInventoryFurnitureModalCtx: input.breakInventoryFurnitureModalCtx,
            breakInventoryFurnitureModalOpen: input.breakInventoryFurnitureModalOpen,
            setBreakInventoryFurnitureModalCtx: input.setBreakInventoryFurnitureModalCtx,
            setBreakInventoryFurnitureModalOpen: input.setBreakInventoryFurnitureModalOpen,
        },
        judicialCustodianModalBundle: {
            judicialCustodianModalCtx: input.judicialCustodianModalCtx,
            judicialCustodianModalOpen: input.judicialCustodianModalOpen,
            setJudicialCustodianModalCtx: input.setJudicialCustodianModalCtx,
            setJudicialCustodianModalOpen: input.setJudicialCustodianModalOpen,
        },
        financialAlimonyBundle: {
            guarantorFollowupAwaitingDetailsSave: input.guarantorFollowupAwaitingDetailsSave,
            lawyerFeePayoutApproved: input.lawyerFeePayoutApproved,
            lawyerStartedPostNoticeExecution: input.lawyerStartedPostNoticeExecution,
            specificDeliveryConvertedAmount: input.specificDeliveryConvertedAmount,
            specificDeliveryFinancialized: input.specificDeliveryFinancialized,
            accumulatedAlimony: input.accumulatedAlimony,
            monthlyAlimony: input.monthlyAlimony,
            alimonyBeneficiaryProfile: input.alimonyBeneficiaryProfile,
        },
        headerUiBundle: {
            toggleHeaderExpanded: input.toggleHeaderExpanded,
            isHeaderExpanded: input.isHeaderExpanded,
        },
        runtimeConstantsBundle: {
            useExecutionDashboardStore: input.useExecutionDashboardStore,
            voiceUserId: input.voiceUserId,
            FollowupModalContext,
            resolveCalendarUserId: input.resolveCalendarUserId,
        },
    };
}
