import {
    handlerClusterSourceBags,
    pickHandlerClusterKeys,
    type HandlerClusterContextSpreads,
} from './handlerClusterContextShared';

const FOUNDATION_HANDLER_CLUSTER_KEYS = [
    'decisionsStorageExecutionId',
    'decisionsReloadEpoch',
    'executionData',
    'executionDataRef',
    'executionId',
    'parentDossierId',
    'persistExecutionMerge',
    'showToast',
    'setTimelineEvents',
    'pushTimelineEventRef',
    'realEstateSeizureAssets',
    'realEstateSeizureModalDecisionId',
    'realEstateSeizureSnapshotRef',
    'nextTimelineId',
    'setRealEstateSeizureAssets',
    'setShowRealEstateSeizureModal',
    'getLocalTodayYmd',
    'setThirdPartySeizuresUi',
    'linkSeizureAuctionToAppointments',
    'pushSeizureAuctionCalendarAppointment',
] as const;

const SEIZURE_HEAVY_HANDLER_CLUSTER_KEYS = Array.from(
    new Set([
        ...FOUNDATION_HANDLER_CLUSTER_KEYS,
        'movableSeizureSubjectDraft',
        'openSeizureRequestsTabRef',
        'propertySeizureSubjectDraft',
        'publicationDateYmdDraft',
        'publicationModalEntityId',
        'publicationModalEntityKind',
        'publicationNewspaperNameDraft',
        'seizedPropertyAuctionDateDraft',
        'seizedPropertyAuctionDepositAmountDraft',
        'seizedPropertyAuctionResultAmountDraft',
        'seizedPropertyAuctionResultBuyerNameDraft',
        'seizedPropertyAuctionResultEntityKind',
        'seizedPropertyAuctionResultOutcome',
        'seizedPropertyAuctionResultPropertyId',
        'seizedPropertyAwardAmountDraft',
        'seizedPropertyBuyerNameDraft',
        'seizedPropertyExpertPriceDraft',
        'seizedPropertyExpertReportDateDraft',
        'seizedPropertyExpertsNamesDraft',
        'seizedPropertyStepDecisionId',
        'seizedPropertyStepEntityKind',
        'seizedPropertyStepKind',
        'seizedPropertyStepNotesDraft',
        'seizedPropertyStepPropertyId',
        'seizureMarkDateDraft',
        'seizureMarkEntityDraft',
        'seizureMarkLetterNumberDraft',
        'seizureMarkModalEntityId',
        'seizureMarkModalEntityKind',
        'seizureMatrixLedgerParamsRef',
        'setMovableSeizureRequestModalOpen',
        'setMovableSeizureSubjectDraft',
        'setPropertySeizureRequestModalOpen',
        'setPropertySeizureSubjectDraft',
        'setPublicationDateYmdDraft',
        'setPublicationModalEntityId',
        'setPublicationModalEntityKind',
        'setPublicationModalOpen',
        'setPublicationNewspaperNameDraft',
        'setSeizedPropertyAuctionDateDraft',
        'setSeizedPropertyAuctionDepositAmountDraft',
        'setSeizedPropertyAuctionResultAmountDraft',
        'setSeizedPropertyAuctionResultBuyerNameDraft',
        'setSeizedPropertyAuctionResultEntityKind',
        'setSeizedPropertyAuctionResultModalOpen',
        'setSeizedPropertyAuctionResultOutcome',
        'setSeizedPropertyAuctionResultPropertyId',
        'setSeizedPropertyAwardAmountDraft',
        'setSeizedPropertyBuyerNameDraft',
        'setSeizedPropertyExpertPriceDraft',
        'setSeizedPropertyExpertReportDateDraft',
        'setSeizedPropertyExpertsNamesDraft',
        'setSeizedPropertyStepDecisionId',
        'setSeizedPropertyStepEntityKind',
        'setSeizedPropertyStepKind',
        'setSeizedPropertyStepModalOpen',
        'setSeizedPropertyStepNotesDraft',
        'setSeizedPropertyStepPropertyId',
        'setSeizureDetailCompletion',
        'setSeizureMarkDateDraft',
        'setSeizureMarkEntityDraft',
        'setSeizureMarkLetterNumberDraft',
        'setSeizureMarkModalEntityId',
        'setSeizureMarkModalEntityKind',
        'setSeizureMarkModalOpen',
        'setShowCoerciveActionForm',
        'setShowUnifiedExecutionModal',
        'setUnifiedLedgerRevision',
        'saveCoerciveActionRef',
        'settlementGuarantorGate',
        'seizureDetailCompletion',
        'seizedAssets',
        'setSeizedAssets',
        'activeDebtorIsDeceased',
        'activeWorkspaceDebtorForFollowup',
        'timelineEvents',
        'seizureDraftsByDecisionId',
        'setSeizureDraftsByDecisionId',
        'seizureDraftsByDecisionIdRef',
        'coerciveSubjectRef',
        'setLastActionDate',
        'coerciveUiLocked',
        'activeDebtorIsEmployee',
        'allDebtorsUnified',
        'executionDebtorTabIndex',
        'isSolidaryLiability',
        'resolveDebtorSolidaryFlag',
        'effectiveDebtors',
        'activeCoerciveActions',
        'setActiveCoerciveActions',
        'thirdPartySeizureSnapshotRef',
        'setThirdPartySeizureAssets',
        'standaloneExecutionMarksSnapshotRef',
        'setStandaloneExecutionMarks',
        'focusSeizurePropertyInlineRef',
        'focusSeizureMovableInlineRef',
        'focusSeizureThirdPartyInlineRef',
        'focusSeizureNoticeInlineRef',
    ]),
) as string[];

export function collectSeizureHeavyHandlerClusterContext(
    spreads: HandlerClusterContextSpreads,
) {
    return pickHandlerClusterKeys(handlerClusterSourceBags(spreads), SEIZURE_HEAVY_HANDLER_CLUSTER_KEYS);
}
