// @ts-nocheck
/** Phase C Slice 23 — تجميع ctx لـ handler cluster من orchestrators + core */
export type HandlerClusterContextSpreads = {
    followupOrchestrator: Record<string, unknown>;
    seizureOrchestrator: Record<string, unknown>;
    coercionOrchestrator: Record<string, unknown>;
    dossierLifecyclePanel: Record<string, unknown>;
    claimFinancials: Record<string, unknown>;
    graceAndSummoning: Record<string, unknown>;
    debtorWorkspaceContext: Record<string, unknown>;
    subsequentNoticeFlow: Record<string, unknown>;
    followupTabAssembly: Record<string, unknown>;
    followupSeizureTabs: Record<string, unknown>;
    decisionsOrchestrator: Record<string, unknown>;
    core: Record<string, unknown>;
};

export function collectHandlerClusterContext(spreads: HandlerClusterContextSpreads) {
    return {
        ...spreads.core,
        ...spreads.followupOrchestrator,
        ...spreads.seizureOrchestrator,
        ...spreads.coercionOrchestrator,
        ...spreads.dossierLifecyclePanel,
        ...spreads.claimFinancials,
        ...spreads.graceAndSummoning,
        ...spreads.debtorWorkspaceContext,
        ...spreads.subsequentNoticeFlow,
        ...spreads.followupTabAssembly,
        ...spreads.followupSeizureTabs,
        ...spreads.decisionsOrchestrator,
    };
}

function pickHandlerClusterKeys(
    bags: ReadonlyArray<Record<string, unknown>>,
    keys: readonly string[],
): Record<string, unknown> {
    const out: Record<string, unknown> = {};
    for (const bag of bags) {
        for (const key of keys) {
            if (key in bag) out[key] = bag[key];
        }
    }
    return out;
}

const FOUNDATION_HANDLER_CLUSTER_KEYS = [
    'decisionsStorageExecutionId',
    'decisionsReloadEpoch',
    'executionData',
    'executionDataRef',
    'executionId',
    'parentDossierId',
    'persistExecutionMerge',
    'showToast',
    'setTimelineEvents',
    'pushTimelineEventRef',
    'realEstateSeizureAssets',
    'realEstateSeizureModalDecisionId',
    'realEstateSeizureSnapshotRef',
    'nextTimelineId',
    'setRealEstateSeizureAssets',
    'setShowRealEstateSeizureModal',
    'getLocalTodayYmd',
    'setThirdPartySeizuresUi',
    'linkSeizureAuctionToAppointments',
    'pushSeizureAuctionCalendarAppointment',
] as const;

const FOUNDATION_TIMELINE_HANDLER_CLUSTER_KEYS = [
    'executionDataRef',
    'executionId',
    'parentDossierId',
    'persistExecutionMerge',
    'setTimelineEvents',
    'pushTimelineEventRef',
] as const;

const FOLLOWUP_ADMIN_SPECIAL_HANDLER_CLUSTER_KEYS = Array.from(
    new Set([
        ...FOUNDATION_TIMELINE_HANDLER_CLUSTER_KEYS,
        'decisionsStorageExecutionId',
        'executionData',
        'nextTimelineId',
        'showToast',
        'specialRequestContent',
        'specialRequestDate',
        'specialRequestManualTitle',
        'setSpecialRequestContent',
        'setSpecialRequestDate',
        'setSpecialRequestManualTitle',
        'setSpecialRequestTemplatePick',
    ]),
) as string[];

const FOLLOWUP_DOSSIER_CONTROLS_HANDLER_CLUSTER_KEYS = Array.from(
    new Set([
        ...FOUNDATION_TIMELINE_HANDLER_CLUSTER_KEYS,
        'executionData',
        'decisionsStorageExecutionId',
        'isInabaActive',
        'isUnifiedTabActive',
        'parentExecutionFile',
        'setDossierActionModalOpen',
        'setDossierActionModalSaving',
        'setDossierActionModalType',
        'setExecutionStorageTick',
        'nextTimelineId',
        'persistExecutionMerge',
        'showToast',
    ]),
) as string[];

const FOLLOWUP_OTHER_PARTY_HANDLER_CLUSTER_KEYS = Array.from(
    new Set([
        ...FOUNDATION_TIMELINE_HANDLER_CLUSTER_KEYS,
        'executionData',
        'executionDataRef',
        'executionId',
        'decisionsStorageExecutionId',
        'isRepresentingDebtor',
        'openDecisionsModalWithBoot',
        'timelineEvents',
        'nextTimelineId',
        'persistExecutionMerge',
        'showToast',
    ]),
) as string[];

const DOSSIER_SUPPORT_HANDLER_CLUSTER_KEYS = Array.from(
    new Set([
        ...FOUNDATION_HANDLER_CLUSTER_KEYS,
        'classification',
        'closeDossierLifecyclePanel',
        'directorate',
        'docNumber',
        'dossierDateDraft',
        'dossierFileKey',
        'dossierPendingStatus',
        'dossierReasonDraft',
        'evictionFullAddressField',
        'evictionPremisesUseRaw',
        'evictionPropertyDistrict',
        'evictionPropertyNumber',
        'evictionPropertyTypeField',
        'fileNumber',
        'fileYear',
        'financialLedgerRef',
        'isEvictionExecutionModule',
        'judgmentDate',
        'onUpdate',
        'parentExecutionFile',
        'reconcileDossierLifecycle',
        'seizedAssetsSnapshotRef',
        'setDossierDateDraft',
        'setDossierLifecyclePanelPhase',
        'setDossierPendingStatus',
        'setDossierReasonDraft',
        'setExecutionStorageTick',
    ]),
) as string[];

const SEIZURE_HEAVY_HANDLER_CLUSTER_KEYS = Array.from(
    new Set([
        ...FOUNDATION_HANDLER_CLUSTER_KEYS,
        'movableSeizureSubjectDraft',
        'openSeizureRequestsTabRef',
        'propertySeizureSubjectDraft',
        'publicationDateYmdDraft',
        'publicationModalEntityId',
        'publicationModalEntityKind',
        'publicationNewspaperNameDraft',
        'seizedPropertyAuctionDateDraft',
        'seizedPropertyAuctionDepositAmountDraft',
        'seizedPropertyAuctionResultAmountDraft',
        'seizedPropertyAuctionResultBuyerNameDraft',
        'seizedPropertyAuctionResultEntityKind',
        'seizedPropertyAuctionResultOutcome',
        'seizedPropertyAuctionResultPropertyId',
        'seizedPropertyAwardAmountDraft',
        'seizedPropertyBuyerNameDraft',
        'seizedPropertyExpertPriceDraft',
        'seizedPropertyExpertReportDateDraft',
        'seizedPropertyExpertsNamesDraft',
        'seizedPropertyStepDecisionId',
        'seizedPropertyStepEntityKind',
        'seizedPropertyStepKind',
        'seizedPropertyStepNotesDraft',
        'seizedPropertyStepPropertyId',
        'seizureMarkDateDraft',
        'seizureMarkEntityDraft',
        'seizureMarkLetterNumberDraft',
        'seizureMarkModalEntityId',
        'seizureMarkModalEntityKind',
        'seizureMatrixLedgerParamsRef',
        'setMovableSeizureRequestModalOpen',
        'setMovableSeizureSubjectDraft',
        'setPropertySeizureRequestModalOpen',
        'setPropertySeizureSubjectDraft',
        'setPublicationDateYmdDraft',
        'setPublicationModalEntityId',
        'setPublicationModalEntityKind',
        'setPublicationModalOpen',
        'setPublicationNewspaperNameDraft',
        'setSeizedPropertyAuctionDateDraft',
        'setSeizedPropertyAuctionDepositAmountDraft',
        'setSeizedPropertyAuctionResultAmountDraft',
        'setSeizedPropertyAuctionResultBuyerNameDraft',
        'setSeizedPropertyAuctionResultEntityKind',
        'setSeizedPropertyAuctionResultModalOpen',
        'setSeizedPropertyAuctionResultOutcome',
        'setSeizedPropertyAuctionResultPropertyId',
        'setSeizedPropertyAwardAmountDraft',
        'setSeizedPropertyBuyerNameDraft',
        'setSeizedPropertyExpertPriceDraft',
        'setSeizedPropertyExpertReportDateDraft',
        'setSeizedPropertyExpertsNamesDraft',
        'setSeizedPropertyStepDecisionId',
        'setSeizedPropertyStepEntityKind',
        'setSeizedPropertyStepKind',
        'setSeizedPropertyStepModalOpen',
        'setSeizedPropertyStepNotesDraft',
        'setSeizedPropertyStepPropertyId',
        'setSeizureDetailCompletion',
        'setSeizureMarkDateDraft',
        'setSeizureMarkEntityDraft',
        'setSeizureMarkLetterNumberDraft',
        'setSeizureMarkModalEntityId',
        'setSeizureMarkModalEntityKind',
        'setSeizureMarkModalOpen',
        'setShowCoerciveActionForm',
        'setShowUnifiedExecutionModal',
        'setUnifiedLedgerRevision',
        'saveCoerciveActionRef',
        'settlementGuarantorGate',
        'seizureDetailCompletion',
        'seizedAssets',
        'setSeizedAssets',
        'activeDebtorIsDeceased',
        'activeWorkspaceDebtorForFollowup',
        'timelineEvents',
        'seizureDraftsByDecisionId',
        'setSeizureDraftsByDecisionId',
        'seizureDraftsByDecisionIdRef',
        'coerciveSubjectRef',
        'setLastActionDate',
        'coerciveUiLocked',
        'activeDebtorIsEmployee',
        'allDebtorsUnified',
        'executionDebtorTabIndex',
        'isSolidaryLiability',
        'resolveDebtorSolidaryFlag',
        'effectiveDebtors',
        'activeCoerciveActions',
        'setActiveCoerciveActions',
        'thirdPartySeizureSnapshotRef',
        'setThirdPartySeizureAssets',
        'standaloneExecutionMarksSnapshotRef',
        'setStandaloneExecutionMarks',
        'focusSeizurePropertyInlineRef',
        'focusSeizureMovableInlineRef',
        'focusSeizureThirdPartyInlineRef',
        'focusSeizureNoticeInlineRef',
    ]),
) as string[];

function handlerClusterSourceBags(spreads: HandlerClusterContextSpreads): ReadonlyArray<Record<string, unknown>> {
    return [
        spreads.core,
        spreads.followupOrchestrator,
        spreads.seizureOrchestrator,
        spreads.coercionOrchestrator,
        spreads.dossierLifecyclePanel,
        spreads.claimFinancials,
        spreads.graceAndSummoning,
        spreads.debtorWorkspaceContext,
        spreads.subsequentNoticeFlow,
        spreads.followupTabAssembly,
        spreads.followupSeizureTabs,
        spreads.decisionsOrchestrator,
    ];
}

export function collectFollowupAdminSpecialHandlerClusterContext(
    spreads: HandlerClusterContextSpreads,
): Record<string, unknown> {
    return pickHandlerClusterKeys(handlerClusterSourceBags(spreads), FOLLOWUP_ADMIN_SPECIAL_HANDLER_CLUSTER_KEYS);
}

export function collectFollowupDossierControlsHandlerClusterContext(
    spreads: HandlerClusterContextSpreads,
): Record<string, unknown> {
    return pickHandlerClusterKeys(
        handlerClusterSourceBags(spreads),
        FOLLOWUP_DOSSIER_CONTROLS_HANDLER_CLUSTER_KEYS,
    );
}

export function collectFollowupOtherPartyHandlerClusterContext(
    spreads: HandlerClusterContextSpreads,
): Record<string, unknown> {
    return pickHandlerClusterKeys(
        handlerClusterSourceBags(spreads),
        FOLLOWUP_OTHER_PARTY_HANDLER_CLUSTER_KEYS,
    );
}

export function collectSeizureHeavyHandlerClusterContext(
    spreads: HandlerClusterContextSpreads,
): Record<string, unknown> {
    return pickHandlerClusterKeys(handlerClusterSourceBags(spreads), SEIZURE_HEAVY_HANDLER_CLUSTER_KEYS);
}

export function collectDossierSupportHandlerClusterContext(
    spreads: HandlerClusterContextSpreads,
): Record<string, unknown> {
    return pickHandlerClusterKeys(handlerClusterSourceBags(spreads), DOSSIER_SUPPORT_HANDLER_CLUSTER_KEYS);
}

/** مفاتي core المتبقية (مرجع للتوليد — 179 key) */
export const HANDLER_CLUSTER_CORE_KEY_NAMES = [
    "EVICTION_WORKFLOW_BY_ACTION_ID",
    "READY_FOR_COERCIVE",
    "activeCoerciveActions",
    "activeDebtorIsDeceased",
    "activeDebtorIsEmployee",
    "activeDebtorNameResolved",
    "alimonyBeneficiaryProfile",
    "appendEvictionExecutorRequest",
    "appointmentDateOnly",
    "appointmentPurpose",
    "appointmentTimeOptional",
    "bindHorizontalWheelToScroll",
    "buildDebtorNoticePatchForKey",
    "caseNotesLogRef",
    "caseTasksPending",
    "caseTasksPendingRef",
    "claimType",
    "classification",
    "closeUnifiedSeizureLog",
    "coerciveUiLocked",
    "creditorDeathMarked",
    "creditors",
    "currentFileId",
    "daysRemaining",
    "debtorDeathMarked",
    "debtorNotificationDate",
    "debtorSummonsMarkerLocal",
    "debtors",
    "decisionsStorageExecutionId",
    "directorate",
    "docNumber",
    "dossierFileKey",
    "editingAppointmentId",
    "editingTaskId",
    "employeeForcedBringAwaitingPersonalOutcome",
    "evictionFullAddressField",
    "evictionPremisesUseRaw",
    "evictionPremisesUseResolved",
    "evictionProcedureLocked",
    "evictionPropertyDistrict",
    "evictionPropertyNumber",
    "evictionPropertyTypeField",
    "evictionWorkflowKey",
    "executionActionsGridLocked",
    "executionData",
    "executionDataId",
    "executionDataRef",
    "executionFeeInjected",
    "executionId",
    "executorApprovalActions",
    "file",
    "fileNumber",
    "fileYear",
    "financialLedger",
    "financialLedgerRef",
    "focusSeizureMovableInlineRef",
    "focusSeizureNoticeInlineRef",
    "focusSeizurePropertyInlineRef",
    "focusSeizureThirdPartyInlineRef",
    "forcedBringDecisionState",
    "getDebtorNoticeStateForKey",
    "getLocalTodayYmd",
    "gracePeriodStart",
    "hasActiveResidentialEvictionGrace",
    "heirSubstitutionAllowed",
    "isExecutorRowEffectivelyApproved",
    "isInabaActive",
    "isRepresentingDebtor",
    "isResidentialVacateGraceFinished",
    "isTask",
    "isUnifiedTabActive",
    "judgmentDate",
    "manualGraceCalendarExtra",
    "masterState",
    "moveCaseTaskToTrash",
    "nextTimelineId",
    "noteBody",
    "noteTitle",
    "noticeVoluntaryPeriodEndOptimistic",
    "notificationCount",
    "notificationPurpose",
    "onUpdate",
    "ongoingAlimonyClaim",
    "openBreakInventoryCompletion",
    "openFinancialHubLedger",
    "openJudicialCustodianCompletion",
    "paidClientFees",
    "paidCourtFees",
    "paidDebt",
    "paidDebtRef",
    "paidDirectorateFees",
    "parentDossierId",
    "parentExecutionFile",
    "parsedLawyerFees",
    "paymentAmount",
    "paymentDate",
    "persistExecutionMerge",
    "persistExecutionMergeRef",
    "pushSeizureAuctionCalendarAppointment",
    "pushTimelineEventRef",
    "readExecutorDecisionsArray",
    "realEstateSeizureAssets",
    "realEstateSeizureSnapshotRef",
    "reconcileDossierLifecycle",
    "residentialVacateDeadlineMaxIso",
    "resolveCalendarUserId",
    "saveCoerciveActionRef",
    "seizedAssets",
    "seizedAssetsSnapshotRef",
    "seizureDetailCompletion",
    "seizureDraftsByDecisionId",
    "seizureDraftsByDecisionIdRef",
    "seizureMatrixLedgerParamsRef",
    "setActiveCoerciveActions",
    "setAppointmentDateOnly",
    "setAppointmentPurpose",
    "setAppointmentTimeOptional",
    "setArrestWarrantUnlocked",
    "setCaseNotesLog",
    "setCaseTasksPending",
    "setDebtorEvaded",
    "setDebtorNotificationDate",
    "setDebtorSummonsMarkerLocal",
    "setEarnerFeeCollectionSm",
    "setEditingAppointmentId",
    "setEditingNoteId",
    "setEditingTaskId",
    "setExecutionFeeInjected",
    "setExecutionPaused",
    "setExecutionStorageTick",
    "setFinancialLedger",
    "setForcedAttendanceIssued",
    "setGracePeriodActive",
    "setGracePeriodEnded",
    "setIsTask",
    "setLastActionDate",
    "setNoteBody",
    "setNoteTitle",
    "setNoticeVoluntaryPeriodEndOptimistic",
    "setNotificationCount",
    "setNotificationPurpose",
    "setPaidDebt",
    "setPaymentAmount",
    "setPaymentDate",
    "setRealEstateSeizureAssets",
    "setSeizedAssets",
    "setSeizureDetailCompletion",
    "setSeizureDraftsByDecisionId",
    "setShowCoerciveActionForm",
    "setShowDecisionsModal",
    "setShowNotesModal",
    "setShowPaymentModal",
    "setStandaloneExecutionMarks",
    "setSummonsMarkerPopoverOpen",
    "setTaskDueDate",
    "setTaskStatus",
    "setThirdPartySeizureAssets",
    "setThirdPartySeizuresUi",
    "setTimelineEvents",
    "setVoluntaryEndOptimistic",
    "settlementGuarantorGate",
    "showDecisionsModal",
    "showToast",
    "standaloneExecutionMarksSnapshotRef",
    "status",
    "summonsPurposeDraft",
    "taskDueDate",
    "taskStatus",
    "thirdPartySeizureSnapshotRef",
    "timelineEvents",
    "timelineEventsRef",
    "vacateDeadline",
    "voluntaryEndOptimistic"
] as const;
