import type { Dispatch, MutableRefObject, SetStateAction } from 'react';
import type { ExecutionFile, TimelineEvent, SeizedAsset, RealEstateSeizureAsset } from '@/app/types/execution';
import type { ExecutionDashboardProps } from '../../types';
import type { DebtorWorkspaceEntry } from '../useDebtorWorkspaceEntries';
import type {
    BreakInventoryFurnitureSavePayload,
    JudicialCustodianSavePayload,
} from '@/app/utils/executorApprovalWorkflow';
import type { EvictionEarnerFeeCollectionSM } from '@/app/utils/evictionEarnerFeeCollectionMachine';
import type { ExecutionCoercionOrchestratorSlice } from '../../orchestrators/executionCoercionOrchestratorTypes';
import type { ExecutionFollowupOrchestratorSlice } from '../../orchestrators/executionFollowupOrchestratorTypes';
import type { OpenFollowupModalPersistedFn } from '../../utils/followupModalOpen';

/** Phase C Slice 29 — typed input for persist / save / summons pipeline */
export type ExecutionDashboardCorePersistHandlerPipelineInput = {
    effectiveDebtors: unknown[];
    financialPrincipalAmount: number;
    financialLawyerFeesAmount: number;
    claimType: string;
    isNonFinancialClaim: boolean;
    debtorBrowserTabsMode: boolean;
    effectiveFollowupDebtorEntry: DebtorWorkspaceEntry | null | undefined;
    activeWorkspaceDebtorForFollowup: DebtorWorkspaceEntry | null | undefined;
    executionData: ExecutionFile | null | undefined;
    executionId: string | undefined;
    decisionsReloadEpoch: number;
    isEvictionExecutionModule: boolean;
    unifiedCollectionApproved: boolean;
    notificationCount: number;
    forcedAttendanceIssued: boolean;
    coercionOrchestrator: ExecutionCoercionOrchestratorSlice;
    isEvictionGraceExpiredNow: boolean;
    isGracePeriodExpiredNow: boolean;
    debtorNotificationDate: string | null | undefined;
    manualGraceCalendarExtra: boolean;
    lawyerStartedPostNoticeExecution: boolean;
    noticeVoluntaryPeriodEndOptimistic: boolean;
    voluntaryEndOptimistic: boolean;
    isEvictionGraceEffectivelyExpired: boolean;
    activeCoerciveActions: unknown[];
    activeDebtorNoticeScope: unknown;
    debtorSummonsMarkerLocal: ExecutionFile['debtor_summons_marker'] | null;
    monetaryExecutionStrictPathFlag: boolean;
    isAlimonyClaim: boolean;
    executionExtras: Record<string, unknown>;
    unifiedSummonsTargetDebtorKey: string;
    activeDebtorIsDeceased: boolean;
    primaryDebtorKeyResolved: string;
    debtorNotifiedForEvictionGrace: boolean;
    remaining: number;
    daysSinceNoticeCalculated: number;
    executionFeeInjected: boolean;
    showToast: (msg: string, type?: string) => void;
    statuteStatus: unknown;
    showStatuteWarning: boolean;
    setShowStatuteWarning: (v: boolean) => void;
    lastActionDate: string | null;
    timelineEvents: TimelineEvent[];
    caseNotesLog: unknown[];
    caseTasksPending: unknown[];
    financialLedger: unknown;
    gracePeriodActive: boolean;
    gracePeriodEnded: boolean;
    seizedAssets: SeizedAsset[];
    seizureDraftsByDecisionId: Record<string, unknown>;
    realEstateSeizureAssets: RealEstateSeizureAsset[];
    debtorEvaded: boolean;
    arrestWarrantUnlocked: boolean;
    creditorAttended: boolean;
    executionPaused: boolean;
    paidDebt: number;
    paidCourtFees: number;
    paidDirectorateFees: number;
    paidClientFees: number;
    earnerFeeCollectionSm: EvictionEarnerFeeCollectionSM | unknown;
    followupOrchestrator: ExecutionFollowupOrchestratorSlice;
    openFollowupModalPersisted?: OpenFollowupModalPersistedFn;
    file: ExecutionDashboardProps['file'];
    currentFileId: string;
    isMaritalFurnitureClaim: boolean;
    nextTimelineId: () => string;
    timelineEventsRef: MutableRefObject<TimelineEvent[]>;
    persistExecutionMergeRef: MutableRefObject<((patch: Record<string, unknown>) => void) | null>;
    pushTimelineEventRef: MutableRefObject<
        | ((event: TimelineEvent, options?: { mergePatch?: Record<string, unknown> }) => void)
        | null
        | undefined
    >;
    executionFileSnapshotRef: MutableRefObject<ExecutionFile | null | undefined>;
    setShowDecisionsModal: (v: boolean) => void;
    showDecisionsModal: boolean;
    setCaseTasksPending: Dispatch<SetStateAction<unknown[]>>;
    setTimelineEvents: Dispatch<SetStateAction<TimelineEvent[]>>;
    setExecutionReportPrompt: Dispatch<SetStateAction<unknown>>;
    setJudicialCustodianModalCtx: Dispatch<SetStateAction<unknown>>;
    setJudicialCustodianModalOpen: (v: boolean) => void;
    setCaseNotesLog: Dispatch<SetStateAction<unknown[]>>;
    decisionsStorageExecutionId: string;
    openBreakInventoryCompletion: (payload: BreakInventoryFurnitureSavePayload) => void;
    openJudicialCustodianCompletion: (payload: JudicialCustodianSavePayload) => void;
    isUnifiedTabActive: boolean;
    unifiedTabId: string;
    onUpdate: ExecutionDashboardProps['onUpdate'];
    executionDataRef: MutableRefObject<ExecutionFile | null | undefined>;
    seizureDraftsByDecisionIdRef: MutableRefObject<Record<string, unknown>>;
    setExecutionStorageTick: Dispatch<SetStateAction<number>>;
    showExecutionTrashModal: boolean;
    setShowExecutionTrashModal: (v: boolean) => void;
    caseNotesLogRef: MutableRefObject<unknown[]>;
    caseTasksPendingRef: MutableRefObject<unknown[]>;
    setPermanentDeleteTimelineId: Dispatch<SetStateAction<string | null>>;
    viewExecutionData: ExecutionFile | null | undefined;
    isHistoricalMode: boolean;
    activeSubFileId: string | null;
    parentDossierId: string;
    setSeizureDraftsByDecisionId: Dispatch<SetStateAction<Record<string, unknown>>>;
    seizedAssetsSnapshotRef: MutableRefObject<SeizedAsset[]>;
    maritalFurnitureItemsForFollowup: unknown[];
    setActiveCoerciveActions: Dispatch<SetStateAction<unknown[]>>;
    isRepresentingDebtor?: boolean;
};
