// @ts-nocheck
import type { ExecutionFile, TimelineEvent } from '@/app/types/execution';
import type { DebtorWorkspaceEntry } from '../useDebtorWorkspaceEntries';

/** Phase C Slice 29 — typed input for grace / master / eviction pipeline */
export type ExecutionDashboardCoreGraceMasterEvictionPipelineInput = {
    executionData: ExecutionFile | null | undefined;
    executionId: string | undefined;
    debtorNotificationDate: string | null | undefined;
    debtors: unknown[];
    effectiveDebtors: unknown[];
    isEvictionExecutionModule: boolean;
    notificationCount: number;
    manualGraceCalendarExtra: boolean;
    voluntaryEndOptimistic: boolean;
    setVoluntaryEndOptimistic: (v: boolean) => void;
    noticeVoluntaryPeriodEndOptimistic: boolean;
    setNoticeVoluntaryPeriodEndOptimistic: (v: boolean) => void;
    debtorBrowserTabsMode: boolean;
    effectiveFollowupDebtorEntry: DebtorWorkspaceEntry | null | undefined;
    activeWorkspaceDebtorForFollowup: DebtorWorkspaceEntry | null | undefined;
    activeTimelineEventsDebtorScoped: TimelineEvent[];
    coercionOrchestrator: Record<string, unknown>;
    claimType: string;
    isAlimonyClaim: boolean;
    monetaryStrictForSummoningEngine: boolean;
    forcedAttendanceIssued: boolean;
    initiator: string;
    paidDebt: number;
    totalOwed: number;
    parsedCourtFees: number;
    financialPrincipalAmount: number;
    paidCourtFees: number;
    paidDirectorateFees: number;
    paidClientFees: number;
    activeDebtorIsEmployee: boolean;
    followupSpecializationEffective: unknown;
    followupModalSpecializationEffective: unknown;
    followupModalDebtorIsEmployee: boolean;
    decisionsReloadEpoch: number;
    isRepresentingDebtor: boolean;
    decisionsStorageExecutionId: string;
    followupSpecialization: unknown;
    showPersonalCoerciveFollowupTab: boolean;
    showGuarantorInSeizureFollowupTab: boolean;
    isPersonalStatusExecutionClaim: boolean;
    isAlimonyClaimType: boolean;
    custodyRemovalClaimActive: boolean;
    employeeCoerciveDetentionRestricted: boolean;
    remainingBalanceForSeizure: number;
    viewExecutionData: ExecutionFile | null | undefined;
    settlementGuarantorGate: unknown;
    activeDebtorIsDeceased: boolean;
    assignmentWorkspaceCtx: { activeDebtorKey?: string; [key: string]: unknown };
    primaryDebtorKeyResolved: string;
    personalTabLockedForEmployee: boolean;
    lastActionDate: string | null;
    dossierLifecycleRow: { lastActionDate?: string; dossierStatus?: string; [key: string]: unknown } | undefined;
    executionPaused: boolean;
    isPaused: boolean;
    pauseReason: string;
    executionFeeAdded: boolean;
    activeDebtorSolidary: boolean;
    allDebtorsUnified: unknown[];
    followupOrchestrator: Record<string, unknown>;
    isHistoricalMode: boolean;
    debtorNotifiedForEvictionGrace: boolean;
    evictionPremisesUseResolved: string;
    todayYmd: string;
    timelineEventsRef: { current: TimelineEvent[] };
    gracePeriodEnded: boolean;
    setGracePeriodEnded: (v: boolean) => void;
    setGracePeriodActive: (v: boolean) => void;
    showToastRef: { current: ((msg: string, type?: string) => void) | undefined };
    showToast: (msg: string, type?: string) => void;
};
