// @ts-nocheck
/** Phase C Slice 25 — assembly handlers من core (غير cluster) */
const CORE_ASSEMBLY_HANDLER_KEYS = [
    'followupTabAssembly',
    'notesTasksHandlers',
    'trashAndPinsHandlers',
    'claimFinancials',
    'graceAndSummoning',
    'ledgerSync',
    'coerciveUiState',
    'partyDeathHandlers',
    'employeeAssignmentHandlers',
    'heirsNotificationHandlers',
    'debtorSummonsCoerciveHandlers',
    'voluntaryPeriodHandlers',
    'publicationNoticeHandlers',
    'notifyDebtorHandler',
    'debtorEmploymentHandler',
    'gracePeriodEndHandler',
    'stayHandlers',
    'dossierFollowupHandlers',
    'paymentHandlers',
    'evictionResidentialGraceHandlers',
    'evictionHeirsMemoHandlers',
    'policeAssistanceHandlers',
    'breakInventoryHandlers',
    'guarantorFollowupHandlers',
    'evictionFinancialHandlers',
    'moduleExpenseHandlers',
    'followupSeizureHandlers',
    'seizureAssetModalHandlers',
    'thirdPartyReceiveHandlers',
    'coerciveActionBridge',
    'coerciveActionHandlers',
    'standaloneMarkHandlers',
    'salarySeizurePatch',
    'thirdPartySeizureHandlers',
    'realEstateSeizureHandlers',
    'seizureReleaseHandlers',
    'followupSeizureTabs',
    'persistExecutionMergeBinding',
    'pushTimelineEventBinding',
    'pendingExecutorOpeners',
    'appointmentHandler',
    'parentDossierPersistence',
    'removeJudicialCustodianEntry',
    'executorApprovalActions',
    'otherPartyCreditorMirrorProps',
    'propertyInlineSaveCtx',
    'salarySeizureTabRows',
    'followupOrchestrator',
    'seizureOrchestrator',
    'coercionOrchestrator',
    'debtorWorkspaceContext',
    'dossierLifecyclePanel',
    'decisionsOrchestrator',
    'financialOrchestrator',
    'partyEditWorkflow',
    'unifiedSeizureLog',
    'dossierLifecycleActions',
    'dossierMetaWorkflow',
    'debtorSummonsProfileBundle',
    'subsequentNoticeFlow',
] as const;

export function pickCoreAssemblyHandlers(bag: Record<string, unknown>) {
    const out: Record<string, unknown> = {};
    for (const key of CORE_ASSEMBLY_HANDLER_KEYS) {
        if (key in bag) out[key] = bag[key];
    }
    return out;
}
