import type { ExecutionDashboardProps } from '../../types';
import type { ExecutionDashboardCoreBootPipelineValue } from './executionDashboardCoreBootPipelineTypes';
import {
    buildExecutionDashboardCoreFollowupDebtorPipelineInput,
    buildExecutionDashboardCoreWorkspacePipelineInput,
} from './buildExecutionDashboardCorePipelinesChainInputs';
import { useExecutionDashboardCoreWorkspacePipeline } from './useExecutionDashboardCoreWorkspacePipeline';
import { useExecutionDashboardCoreFileMetadataBinding } from './useExecutionDashboardCoreFileMetadataBinding';
import { useExecutionDashboardCoreFollowupDebtorPipeline } from './useExecutionDashboardCoreFollowupDebtorPipeline';
import { useExecutionDashboardCoreClaimGracePersistSegment } from './useExecutionDashboardCoreClaimGracePersistSegment';

export function useExecutionDashboardCorePipelinesChain({
    boot,
    file,
    executionId,
    onUpdate,
}: {
    boot: ExecutionDashboardCoreBootPipelineValue;
    file: ExecutionDashboardProps['file'];
    executionId: string | undefined;
    onUpdate: ExecutionDashboardProps['onUpdate'];
}) {
    const {
        executionStorageTick,
        setExecutionStorageTick,
        activeSubFileId,
        parentDossierId,
        currentFileId,
        isInabaActive,
        inabaTargets,
        subFiles,
        activeTabId,
        setActiveTabId,
        currentFile,
        childDossiers,
        isHistoricalMode,
        isUnifiedTabActive,
        unifiedTabId,
        executionData,
        parentExecutionFile,
        inabaCorrespondenceLog,
        viewExecutionData,
        executionDataRef,
        partyBadgesExecutionId,
        decisionsStorageExecutionId,
        executionAppealBanner,
        dossierFileKey,
        executionFileKey,
        dossierLifecycleRow,
        debtorSummonsMarkerLocal,
        setDebtorSummonsMarkerLocal,
        isLoading,
        loadError,
        showExtraCreditors,
        setShowExtraCreditors,
        showExtraDebtors,
        setShowExtraDebtors,
        executionDashboardFileId,
        modals,
        setExecutionModal,
        isHeaderExpanded,
        toggleHeaderExpanded,
        setShowNotesModal,
        setShowDocumentsModal,
        setShowDecisionsModal,
        setShowTimelineModal,
        setShowNotificationModal,
        setShowCoerciveModal,
        setShowPaymentModal,
        setShowAppointmentModal,
        setShowSeizedAssetsModal,
        setShowPaymentCalculator,
        setShowSettlementCalculator,
        setShowPauseModal,
        showDecisionsModal,
        showLinkedDossierTimeline,
        setShowLinkedDossierTimeline,
        linkedDossierToView,
        setLinkedDossierToView,
        showTransferFileNumberChangeModal,
        setShowTransferFileNumberChangeModal,
        hasChildDossiers,
    } = boot;

    const workspacePipeline = useExecutionDashboardCoreWorkspacePipeline(
        buildExecutionDashboardCoreWorkspacePipelineInput({ boot, executionId }),
    );

    const {
        todayYmd,
        noteTitle, setNoteTitle, noteBody, setNoteBody, isTask, setIsTask,
        taskDueDate, setTaskDueDate, taskStatus, setTaskStatus,
        editingTaskId, setEditingTaskId, editingNoteId, setEditingNoteId,
        savedNotesView, setSavedNotesView, showUnifiedExecutionModal,
        followupOrchestrator, timelineAccordionExpanded, setTimelineAccordionExpanded,
        activeTimelineFilter, setActiveTimelineFilter, gracePeriodActive, setGracePeriodActive,
        gracePeriodEnded, setGracePeriodEnded, notificationCount, setNotificationCount,
        notificationPurpose, setNotificationPurpose, voluntaryEndOptimistic, setVoluntaryEndOptimistic,
        noticeVoluntaryPeriodEndOptimistic, setNoticeVoluntaryPeriodEndOptimistic,
        summonsMarkerPopoverOpen, setSummonsMarkerPopoverOpen, executionMemoBadgePopoverOpen,
        setExecutionMemoBadgePopoverOpen, summonsPurposeDraft, setSummonsPurposeDraft,
        forcedAttendanceIssued, setForcedAttendanceIssued, debtorEvaded, setDebtorEvaded,
        arrestWarrantUnlocked, setArrestWarrantUnlocked, creditorAttended, executionPaused,
        setExecutionPaused, showUnifiedSummonsModal, setShowUnifiedSummonsModal, coercionOrchestrator,
        lastActionDate, setLastActionDate, showStatuteWarning, setShowStatuteWarning,
        dossierLifecyclePanel, showExecutionTrashModal, setShowExecutionTrashModal,
        permanentDeleteTimelineId, setPermanentDeleteTimelineId, paidDebt, paidDebtRef,
        paidCourtFees, setPaidCourtFees, paidDirectorateFees, setPaidDirectorateFees,
        paidClientFees, setPaidClientFees, noteText, setNoteText, appointmentPurpose,
        setAppointmentPurpose, appointmentDateOnly, setAppointmentDateOnly, appointmentTimeOptional,
        setAppointmentTimeOptional, editingAppointmentId, setEditingAppointmentId, appointmentContext,
        setAppointmentContext, executorScheduleModalOpen, setExecutorScheduleModalOpen,
        executorScheduleContext, setExecutorScheduleContext, breakInventoryFurnitureModalOpen,
        setBreakInventoryFurnitureModalOpen, breakInventoryFurnitureModalCtx,
        setBreakInventoryFurnitureModalCtx, judicialCustodianModalOpen, setJudicialCustodianModalOpen,
        judicialCustodianModalCtx, setJudicialCustodianModalCtx, executionReportPrompt,
        setExecutionReportPrompt, financialLedger, financialLedgerRef, hasFinancialLedger,
        showLedgerModal, setShowLedgerModal, paymentAmount, setPaymentAmount, paymentDate,
        setPaymentDate, debtorNotificationDate, setDebtorNotificationDate, manualGraceCalendarExtra,
        setManualGraceCalendarExtra,         timelineEvents, setTimelineEvents, timelineEventsRef,
        persistExecutionMergeRef, pushTimelineEventRef, executionFileSnapshotRef,
        earnerFeeCollectionSm, setEarnerFeeCollectionSm, caseNotesLog, setCaseNotesLog,
        caseNotesLogRef, caseTasksPending, setCaseTasksPending, caseTasksPendingRef,
        evictionGracePinned, setEvictionGracePinned, evictionGraceHidden, setEvictionGraceHidden,
        toggleEvictionGracePinned, gracePinnedKey, graceHiddenKey, activeTimelineEvents,
        showOnlyActiveFileTimeline, setShowOnlyActiveFileTimeline, mergedTimelineEvents,
        completedTaskTitles, savedNotesSplit, activeCaseTasksPendingAll, activeGraceTasks,
        activeCaseTasksPending, trashedTimelineEvents, trashedCaseNotes, trashedCaseTasks,
        dockPinnedNotes, dockPinnedTasks, nextTimelineId, seizedAssets, setSeizedAssets,
        seizedAssetsSnapshotRef, realEstateSeizureAssets, setRealEstateSeizureAssets,
        realEstateSeizureSnapshotRef, thirdPartySeizureAssets, setThirdPartySeizureAssets,
        thirdPartySeizureSnapshotRef, standaloneExecutionMarks, setStandaloneExecutionMarks,
        standaloneExecutionMarksSnapshotRef, getMilestoneTimelineSnapshot, seizureDraftsByDecisionId,
        setSeizureDraftsByDecisionId, seizureDraftsByDecisionIdRef, activeCoerciveActions,
        setActiveCoerciveActions, showCoerciveActionForm, setShowCoerciveActionForm,
        seizureDetailCompletion, setSeizureDetailCompletion, saveCoerciveActionRef,
        focusSeizurePropertyInlineRef, focusSeizureMovableInlineRef, focusSeizureThirdPartyInlineRef,
        focusSeizureNoticeInlineRef, seizureOrchestrator, approvedSeizedAssets,
        movableSeizureRegistryAssets, salarySeizureRegistryAssets, realEstateSeizureRegistryAssets,
        thirdPartySeizureRegistryAssets, salarySeizureTabRows, isPaused, setIsPaused, pauseReason,
        setPauseReason, executionFeeAdded, toastVisible, toastMessage, toastType, toastEpoch,
        showToast, hideToast, showToastRef, decisionsOrchestrator, decisionsReloadEpoch,
        setDecisionsReloadEpoch, decisionsModalBootHubTab, setDecisionsModalBootHubTab,
        decisionsModalBootListTab, setDecisionsModalBootListTab, decisionsModalScrollToDecisionId,
        setDecisionsModalScrollToDecisionId, appealsModalScrollToDecisionId,
        setAppealsModalScrollToDecisionId, clearDecisionsModalBootState, openDecisionsModalWithBoot,
        forcedBringDecisionState, employeeForcedBringAwaitingPersonalOutcome, executionFeeInjected,
        setExecutionFeeInjected, financialOrchestrator, isFinancialCenterExpanded,
        setIsFinancialCenterExpanded, activeFinancialTab, setActiveFinancialTab,
        showExecutionFinancialHub, setShowExecutionFinancialHub, financialHubAutoOpenMode,
        setFinancialHubAutoOpenMode, financialHubSeizedMovableId, setFinancialHubSeizedMovableId,
        financialHubSeizedPropertyId, setFinancialHubSeizedPropertyId, openFinancialHubLedger,
        thirdPartySeizuresUi, setThirdPartySeizuresUi, applyThirdPartySeizuresFromPatch,
    } = workspacePipeline;

    const fileMetadataBinding = useExecutionDashboardCoreFileMetadataBinding({
        executionData,
        viewExecutionData,
        parentExecutionFile,
        followupOrchestrator,
        activeCoerciveActions,
        activeTimelineEvents,
    });
    const {
        directorate,
        fileNumber,
        fileYear,
        executionNumber,
        executionYear,
        executionType,
        docType,
        docNumber,
        claimType,
        judgmentDate,
        classification,
        creditors,
        debtors,
        totalAmount,
        debtAmount,
        lawyerFeesAmount,
        executionFee,
        clientFeesAmount,
        courtFees,
        directorateFees,
        monthlyAlimony,
        alimony,
        accumulatedAlimony,
        initiator,
        representedParty,
        daysSinceNotice,
        isAlimonyCase,
        lastPaymentDate,
        shariaDeedNumber,
        shariaRegisterNumber,
        shariaIssueDate,
        shariaIssuingCourt,
        chequeBankName,
        chequeIssueDate,
        chequeNumber,
        status,
        createdAt,
        includesSleepover,
        visitationChildrenNames,
        custodyWardNames,
        evictionPropertyNumber,
        evictionPropertyDistrict,
        evictionPropertyTypeField,
        evictionFullAddressField,
        evictionPremisesUseRaw,
        visitChildNames,
        custodyWardNamesList,
        evictionPremisesUseResolved,
        evictionCaseExpensesSum,
        creditorExtraMinorNames,
        creditorExtraMinorLabel,
        classificationDisplay,
        claimTypeArabicDisplay,
        lawyerStartedPostNoticeExecution,
        judgmentDateDisplay,
        headerFields,
        showJudgmentMeta,
        parentHeaderFields,
        parentClassificationDisplay,
        parentClaimTypeArabicDisplay,
        parentJudgmentDateDisplay,
        parentShowJudgmentMeta,
    } = fileMetadataBinding;

    // ===========================
    // Financial debug logging removed from render path for performance
    
    const followupDebtor = useExecutionDashboardCoreFollowupDebtorPipeline(
        buildExecutionDashboardCoreFollowupDebtorPipelineInput({
            executionData,
            viewExecutionData,
            executionId,
            decisionsStorageExecutionId,
            decisionsReloadEpoch: Number(decisionsReloadEpoch ?? 0),
            claimType,
            creditors,
            debtors,
            showToast,
            dossierFileKey,
            executionFileKey,
            setShowDecisionsModal,
            showDecisionsModal,
            setShowExtraCreditors,
            setShowExtraDebtors,
            setDebtorSummonsMarkerLocal,
            workspacePipeline,
        }) ,
    );

    const {
        debtorWorkspaceContext,
        effectiveCreditors,
        effectiveDebtors,
        allDebtorsUnified,
        resolveDebtorSolidaryFlag,
        allDebtorsSolidary,
        isSolidaryLiability,
        debtorWorkspaceEntries,
        creditorWorkspaceEntries,
        creditorNamesTextList,
        perDebtorSolidarySplitMode,
        debtorLiabilityGroups,
        liabilityGroupTabsMode,
        multiDebtorMode,
        debtorBrowserTabsMode,
        activeLiabilityGroup,
        activeGroupEntries,
        activeLiabilityGroupId,
        allDebtorRowsForLiability,
        activeDebtorSolidary,
        activeWorkspaceDebtorForFollowup,
        primaryDebtorWorkspaceKey,
        primaryDebtorKeyResolved,
        showFollowupSolidaryDebtorTabs,
        effectiveFollowupDebtorEntry,
        followupAssignmentWorkspaceCtx,
        mergedTimelineEventsDebtorScoped,
        mergedTimelineRadarPreviewLimit,
        assignmentWorkspaceCtx,
        unifiedSummonsTargetDebtorKey,
        activeDebtorNoticeScope,
        scopedNotificationCount,
        scopedSummonsMarker,
        followupActiveDebtorNoticeScope,
        modalActiveDebtorNoticeScope,
        activeDebtorIsEmployee,
        activeDebtorIsDeceased,
        followupModalDebtorIsEmployee,
        followupModalDebtorIsDeceased,
        modalKasabTerminationEmphasis,
        modalResolvedEmployeeSummonsAssignment,
        modalShowEmployeeAssignmentCoerciveBlock,
        employeeAssignmentPhaseForCoercive,
        employeeUnlocksPersonalCoerciveFromAssignment,
        followupModalEntityKind,
        followupModalSpecialization,
        followupModalSpecializationEffective,
        seizedPropertiesForSeizureLog,
        seizedMovablesForSeizureLog,
        seizureLogExecutorDecisions,
        unifiedSeizureLog,
        showUnifiedSeizureLogModal,
        closeUnifiedSeizureLog,
        unifiedSeizureLogTab,
        setUnifiedSeizureLogTab,
        unifiedSeizureLogEntries,
        unifiedSeizureTabCounts,
        hasUnifiedSeizureLogContent,
        openUnifiedSeizureLog,
        thirdPartyFundsDraftById,
        setThirdPartyFundsDraftById,
        clearThirdPartyFundsDraft,
        activeDebtorNameResolved,
        activeDebtorInitialWasEmployee,
        activeTimelineEventsDebtorScoped,
        timelineRadarPreviewLimit,
        kasabTerminationEmphasis,
        activeDebtorEntityKind,
        activeDebtorIsLegalEntity,
        isRepresentingDebtor,
        appealPerspective,
        hideCoerciveTabsForDebtorAgent,
        followupTabAssembly,
        executionDomainContext,
        followupSpecialization,
        followupSpecializationEffective,
        showPersonalCoerciveFollowupTab,
        showSalarySeizureInFollowupModal,
        followupSalarySeizureLabel,
        showEmployeeCompulsoryProceduresBanner,
        activeFollowupDebtorKey,
        personalTabUnlockByDebtor,
        setPersonalTabUnlockByDebtor,
        employeePersonalTabUnlockStorageKey,
        custodyRemovalClaimActive,
        employeeCoerciveDetentionRestricted,
        modalEmployeeCoerciveDetentionRestricted,
        modalShowPersonalCoerciveFollowupTab,
        personalTabLockedForEmployee,
        modalPersonalTabLockedForEmployee,
        followupTabsRestricted,
        followupSectionTabOrder,
        followupModalTabs,
        isFollowupTabActive,
        openFollowupModalPersisted,
        closeFollowupModalPersisted,
        persistFollowupModalViewport,
        goFollowupSectionTabByDelta,
        timelineFilterOptions,
    } = followupDebtor;

    const {
        claimFinancialLedger,
        graceMasterPipeline,
        persistHandlerPipeline,
        financialStatus,
        specificDeliveryConvertedAmount,
        specificDeliveryFinancialized,
    } = useExecutionDashboardCoreClaimGracePersistSegment({
        boot,
        file,
        executionId,
        onUpdate,
        executionData,
        viewExecutionData,
        executionDataRef,
        workspacePipeline,
        fileMetadataBinding,
        followupDebtor,
        showToast,
        gracePeriodEnded,
        setShowStatuteWarning,
    });

    return {
        workspacePipeline,
        fileMetadataBinding,
        followupDebtor,
        claimFinancialLedger,
        graceMasterPipeline,
        persistHandlerPipeline,
        financialStatus,
        specificDeliveryConvertedAmount,
        specificDeliveryFinancialized,
    };
}
