// @ts-nocheck
/** Phase C Slice 32 — workspace → persist pipeline chain */
import { useMemo } from 'react';
import type { ExecutionFile } from '@/app/types/execution';
import { openBreakInventoryCompletion, openJudicialCustodianCompletion } from '@/app/utils/executorApprovalWorkflow';
import type { ExecutionDashboardProps } from '../../types';
import { useExecutionDashboardCoreWorkspacePipeline } from './useExecutionDashboardCoreWorkspacePipeline';
import { useExecutionDashboardCoreFileMetadataBinding } from './useExecutionDashboardCoreFileMetadataBinding';
import { useExecutionDashboardCoreFollowupDebtorPipeline } from './useExecutionDashboardCoreFollowupDebtorPipeline';
import { useExecutionDashboardCoreClaimFinancialLedgerPipeline } from './useExecutionDashboardCoreClaimFinancialLedgerPipeline';
import { useExecutionDashboardCoreGraceMasterEvictionPipeline } from './useExecutionDashboardCoreGraceMasterEvictionPipeline';
import { useExecutionDashboardCorePersistHandlerPipeline } from './useExecutionDashboardCorePersistHandlerPipeline';

export function useExecutionDashboardCorePipelinesChain({
    boot,
    file,
    executionId,
    onUpdate,
}: {
    boot: Record<string, unknown>;
    file: ExecutionDashboardProps['file'];
    executionId: string | undefined;
    onUpdate: ExecutionDashboardProps['onUpdate'];
}) {
    const {
        executionStorageTick,
        setExecutionStorageTick,
        activeSubFileId,
        parentDossierId,
        currentFileId,
        isInabaActive,
        inabaTargets,
        subFiles,
        activeTabId,
        setActiveTabId,
        currentFile,
        childDossiers,
        isHistoricalMode,
        isUnifiedTabActive,
        unifiedTabId,
        executionData,
        parentExecutionFile,
        inabaCorrespondenceLog,
        viewExecutionData,
        executionDataRef,
        partyBadgesExecutionId,
        decisionsStorageExecutionId,
        executionAppealBanner,
        dossierFileKey,
        executionFileKey,
        dossierLifecycleRow,
        debtorSummonsMarkerLocal,
        setDebtorSummonsMarkerLocal,
        isLoading,
        loadError,
        showExtraCreditors,
        setShowExtraCreditors,
        showExtraDebtors,
        setShowExtraDebtors,
        executionDashboardFileId,
        modals,
        setExecutionModal,
        isHeaderExpanded,
        toggleHeaderExpanded,
        setShowNotesModal,
        setShowDocumentsModal,
        setShowDecisionsModal,
        setShowTimelineModal,
        setShowNotificationModal,
        setShowCoerciveModal,
        setShowPaymentModal,
        setShowAppointmentModal,
        setShowSeizedAssetsModal,
        setShowPaymentCalculator,
        setShowSettlementCalculator,
        setShowPauseModal,
        showDecisionsModal,
        showLinkedDossierTimeline,
        setShowLinkedDossierTimeline,
        linkedDossierToView,
        setLinkedDossierToView,
        showTransferFileNumberChangeModal,
        setShowTransferFileNumberChangeModal,
        hasChildDossiers,
    } = boot;

    const workspacePipeline = useExecutionDashboardCoreWorkspacePipeline({
        modals,
        executionData,
        executionDataRef,
        executionFileKey,
        executionDashboardFileId,
        executionId,
        decisionsStorageExecutionId,
        executionStorageTick,
        setExecutionModal,
        showDecisionsModal,
        setShowDecisionsModal,
        setShowNotesModal,
        setShowDocumentsModal,
        setShowAppointmentModal,
        setShowTimelineModal,
        setShowNotificationModal,
        setShowCoerciveModal,
        subFiles,
        activeSubFileId,
        isInabaActive,
        parentDossierId,
    });

    const {
        todayYmd,
        noteTitle, setNoteTitle, noteBody, setNoteBody, isTask, setIsTask,
        taskDueDate, setTaskDueDate, taskStatus, setTaskStatus,
        editingTaskId, setEditingTaskId, editingNoteId, setEditingNoteId,
        savedNotesView, setSavedNotesView, showUnifiedExecutionModal,
        followupOrchestrator, timelineAccordionExpanded, setTimelineAccordionExpanded,
        activeTimelineFilter, setActiveTimelineFilter, gracePeriodActive, setGracePeriodActive,
        gracePeriodEnded, setGracePeriodEnded, notificationCount, setNotificationCount,
        notificationPurpose, setNotificationPurpose, voluntaryEndOptimistic, setVoluntaryEndOptimistic,
        noticeVoluntaryPeriodEndOptimistic, setNoticeVoluntaryPeriodEndOptimistic,
        summonsMarkerPopoverOpen, setSummonsMarkerPopoverOpen, executionMemoBadgePopoverOpen,
        setExecutionMemoBadgePopoverOpen, summonsPurposeDraft, setSummonsPurposeDraft,
        forcedAttendanceIssued, setForcedAttendanceIssued, debtorEvaded, setDebtorEvaded,
        arrestWarrantUnlocked, setArrestWarrantUnlocked, creditorAttended, executionPaused,
        setExecutionPaused, showUnifiedSummonsModal, setShowUnifiedSummonsModal, coercionOrchestrator,
        lastActionDate, setLastActionDate, showStatuteWarning, setShowStatuteWarning,
        dossierLifecyclePanel, showExecutionTrashModal, setShowExecutionTrashModal,
        permanentDeleteTimelineId, setPermanentDeleteTimelineId, paidDebt, paidDebtRef,
        paidCourtFees, setPaidCourtFees, paidDirectorateFees, setPaidDirectorateFees,
        paidClientFees, setPaidClientFees, noteText, setNoteText, appointmentPurpose,
        setAppointmentPurpose, appointmentDateOnly, setAppointmentDateOnly, appointmentTimeOptional,
        setAppointmentTimeOptional, editingAppointmentId, setEditingAppointmentId, appointmentContext,
        setAppointmentContext, executorScheduleModalOpen, setExecutorScheduleModalOpen,
        executorScheduleContext, setExecutorScheduleContext, breakInventoryFurnitureModalOpen,
        setBreakInventoryFurnitureModalOpen, breakInventoryFurnitureModalCtx,
        setBreakInventoryFurnitureModalCtx, judicialCustodianModalOpen, setJudicialCustodianModalOpen,
        judicialCustodianModalCtx, setJudicialCustodianModalCtx, executionReportPrompt,
        setExecutionReportPrompt, financialLedger, financialLedgerRef, hasFinancialLedger,
        showLedgerModal, setShowLedgerModal, paymentAmount, setPaymentAmount, paymentDate,
        setPaymentDate, debtorNotificationDate, setDebtorNotificationDate, manualGraceCalendarExtra,
        setManualGraceCalendarExtra,         timelineEvents, setTimelineEvents, timelineEventsRef,
        persistExecutionMergeRef, pushTimelineEventRef, executionFileSnapshotRef,
        earnerFeeCollectionSm, setEarnerFeeCollectionSm, caseNotesLog, setCaseNotesLog,
        caseNotesLogRef, caseTasksPending, setCaseTasksPending, caseTasksPendingRef,
        evictionGracePinned, setEvictionGracePinned, evictionGraceHidden, setEvictionGraceHidden,
        toggleEvictionGracePinned, gracePinnedKey, graceHiddenKey, activeTimelineEvents,
        showOnlyActiveFileTimeline, setShowOnlyActiveFileTimeline, mergedTimelineEvents,
        completedTaskTitles, savedNotesSplit, activeCaseTasksPendingAll, activeGraceTasks,
        activeCaseTasksPending, trashedTimelineEvents, trashedCaseNotes, trashedCaseTasks,
        dockPinnedNotes, dockPinnedTasks, nextTimelineId, seizedAssets, setSeizedAssets,
        seizedAssetsSnapshotRef, realEstateSeizureAssets, setRealEstateSeizureAssets,
        realEstateSeizureSnapshotRef, thirdPartySeizureAssets, setThirdPartySeizureAssets,
        thirdPartySeizureSnapshotRef, standaloneExecutionMarks, setStandaloneExecutionMarks,
        standaloneExecutionMarksSnapshotRef, getMilestoneTimelineSnapshot, seizureDraftsByDecisionId,
        setSeizureDraftsByDecisionId, seizureDraftsByDecisionIdRef, activeCoerciveActions,
        setActiveCoerciveActions, showCoerciveActionForm, setShowCoerciveActionForm,
        seizureDetailCompletion, setSeizureDetailCompletion, saveCoerciveActionRef,
        focusSeizurePropertyInlineRef, focusSeizureMovableInlineRef, focusSeizureThirdPartyInlineRef,
        focusSeizureNoticeInlineRef, seizureOrchestrator, approvedSeizedAssets,
        movableSeizureRegistryAssets, salarySeizureRegistryAssets, realEstateSeizureRegistryAssets,
        thirdPartySeizureRegistryAssets, salarySeizureTabRows, isPaused, setIsPaused, pauseReason,
        setPauseReason, executionFeeAdded, toastVisible, toastMessage, toastType, toastEpoch,
        showToast, hideToast, showToastRef, decisionsOrchestrator, decisionsReloadEpoch,
        setDecisionsReloadEpoch, decisionsModalBootHubTab, setDecisionsModalBootHubTab,
        decisionsModalBootListTab, setDecisionsModalBootListTab, decisionsModalScrollToDecisionId,
        setDecisionsModalScrollToDecisionId, appealsModalScrollToDecisionId,
        setAppealsModalScrollToDecisionId, clearDecisionsModalBootState, openDecisionsModalWithBoot,
        forcedBringDecisionState, employeeForcedBringAwaitingPersonalOutcome, executionFeeInjected,
        setExecutionFeeInjected, financialOrchestrator, isFinancialCenterExpanded,
        setIsFinancialCenterExpanded, activeFinancialTab, setActiveFinancialTab,
        showExecutionFinancialHub, setShowExecutionFinancialHub, financialHubAutoOpenMode,
        setFinancialHubAutoOpenMode, financialHubSeizedMovableId, setFinancialHubSeizedMovableId,
        financialHubSeizedPropertyId, setFinancialHubSeizedPropertyId, openFinancialHubLedger,
        thirdPartySeizuresUi, setThirdPartySeizuresUi, applyThirdPartySeizuresFromPatch,
    } = workspacePipeline;

    const fileMetadataBinding = useExecutionDashboardCoreFileMetadataBinding({
        executionData,
        viewExecutionData,
        parentExecutionFile,
        followupOrchestrator,
        activeCoerciveActions,
        activeTimelineEvents,
    });

    const {
        directorate,
        fileNumber,
        fileYear,
        executionNumber,
        executionYear,
        executionType,
        docType,
        docNumber,
        claimType,
        judgmentDate,
        classification,
        creditors,
        debtors,
        totalAmount,
        debtAmount,
        lawyerFeesAmount,
        executionFee,
        clientFeesAmount,
        courtFees,
        directorateFees,
        monthlyAlimony,
        alimony,
        accumulatedAlimony,
        initiator,
        representedParty,
        daysSinceNotice,
        isAlimonyCase,
        lastPaymentDate,
        shariaDeedNumber,
        shariaRegisterNumber,
        shariaIssueDate,
        shariaIssuingCourt,
        chequeBankName,
        chequeIssueDate,
        chequeNumber,
        status,
        createdAt,
        includesSleepover,
        visitationChildrenNames,
        custodyWardNames,
        evictionPropertyNumber,
        evictionPropertyDistrict,
        evictionPropertyTypeField,
        evictionFullAddressField,
        evictionPremisesUseRaw,
        visitChildNames,
        custodyWardNamesList,
        evictionPremisesUseResolved,
        evictionCaseExpensesSum,
        creditorExtraMinorNames,
        creditorExtraMinorLabel,
        classificationDisplay,
        claimTypeArabicDisplay,
        lawyerStartedPostNoticeExecution,
        judgmentDateDisplay,
        headerFields,
        showJudgmentMeta,
        parentHeaderFields,
        parentClassificationDisplay,
        parentClaimTypeArabicDisplay,
        parentJudgmentDateDisplay,
        parentShowJudgmentMeta,
    } = fileMetadataBinding;

    // ===========================
    // Financial debug logging removed from render path for performance
    
    const followupDebtor = useExecutionDashboardCoreFollowupDebtorPipeline({
        executionData,
        viewExecutionData,
        executionId,
        decisionsStorageExecutionId,
        decisionsReloadEpoch,
        claimType,
        creditors,
        debtors,
        mergedTimelineEvents,
        activeTimelineEvents,
        activeCoerciveActions,
        realEstateSeizureRegistryAssets,
        salarySeizureRegistryAssets,
        movableSeizureRegistryAssets,
        thirdPartySeizureRegistryAssets,
        thirdPartySeizuresUi,
        showToast,
        showUnifiedExecutionModal,
        dossierFileKey,
        executionFileKey,
        setShowDecisionsModal,
        showDecisionsModal,
        setActiveTimelineFilter,
        setShowExtraCreditors,
        setShowExtraDebtors,
        caseTasksPendingRef,
        setCaseTasksPending,
        setTimelineEvents,
        persistExecutionMergeRef,
        setNotificationCount,
        setDebtorSummonsMarkerLocal,
        pushTimelineEventRef,
        nextTimelineId,
        followupOrchestrator,
    });

    const {
        debtorWorkspaceContext,
        effectiveCreditors,
        effectiveDebtors,
        allDebtorsUnified,
        resolveDebtorSolidaryFlag,
        allDebtorsSolidary,
        isSolidaryLiability,
        debtorWorkspaceEntries,
        creditorWorkspaceEntries,
        creditorNamesTextList,
        perDebtorSolidarySplitMode,
        debtorLiabilityGroups,
        liabilityGroupTabsMode,
        multiDebtorMode,
        debtorBrowserTabsMode,
        activeLiabilityGroup,
        activeGroupEntries,
        activeLiabilityGroupId,
        allDebtorRowsForLiability,
        activeDebtorSolidary,
        activeWorkspaceDebtorForFollowup,
        primaryDebtorWorkspaceKey,
        primaryDebtorKeyResolved,
        showFollowupSolidaryDebtorTabs,
        effectiveFollowupDebtorEntry,
        followupAssignmentWorkspaceCtx,
        mergedTimelineEventsDebtorScoped,
        mergedTimelineRadarPreviewLimit,
        assignmentWorkspaceCtx,
        unifiedSummonsTargetDebtorKey,
        activeDebtorNoticeScope,
        scopedNotificationCount,
        scopedSummonsMarker,
        followupActiveDebtorNoticeScope,
        modalActiveDebtorNoticeScope,
        activeDebtorIsEmployee,
        activeDebtorIsDeceased,
        followupModalDebtorIsEmployee,
        followupModalDebtorIsDeceased,
        modalKasabTerminationEmphasis,
        modalResolvedEmployeeSummonsAssignment,
        modalShowEmployeeAssignmentCoerciveBlock,
        employeeAssignmentPhaseForCoercive,
        employeeUnlocksPersonalCoerciveFromAssignment,
        followupModalEntityKind,
        followupModalSpecialization,
        followupModalSpecializationEffective,
        seizedPropertiesForSeizureLog,
        seizedMovablesForSeizureLog,
        seizureLogExecutorDecisions,
        unifiedSeizureLog,
        showUnifiedSeizureLogModal,
        closeUnifiedSeizureLog,
        unifiedSeizureLogTab,
        setUnifiedSeizureLogTab,
        unifiedSeizureLogEntries,
        unifiedSeizureTabCounts,
        hasUnifiedSeizureLogContent,
        openUnifiedSeizureLog,
        thirdPartyFundsDraftById,
        setThirdPartyFundsDraftById,
        clearThirdPartyFundsDraft,
        activeDebtorNameResolved,
        activeDebtorInitialWasEmployee,
        activeTimelineEventsDebtorScoped,
        timelineRadarPreviewLimit,
        kasabTerminationEmphasis,
        activeDebtorEntityKind,
        activeDebtorIsLegalEntity,
        isRepresentingDebtor,
        appealPerspective,
        hideCoerciveTabsForDebtorAgent,
        followupTabAssembly,
        executionDomainContext,
        followupSpecialization,
        followupSpecializationEffective,
        showPersonalCoerciveFollowupTab,
        showSalarySeizureInFollowupModal,
        followupSalarySeizureLabel,
        showEmployeeCompulsoryProceduresBanner,
        activeFollowupDebtorKey,
        personalTabUnlockByDebtor,
        setPersonalTabUnlockByDebtor,
        employeePersonalTabUnlockStorageKey,
        custodyRemovalClaimActive,
        employeeCoerciveDetentionRestricted,
        modalEmployeeCoerciveDetentionRestricted,
        modalShowPersonalCoerciveFollowupTab,
        personalTabLockedForEmployee,
        modalPersonalTabLockedForEmployee,
        followupTabsRestricted,
        followupSectionTabOrder,
        followupModalTabs,
        isFollowupTabActive,
        openFollowupModalPersisted,
        closeFollowupModalPersisted,
        persistFollowupModalViewport,
        goFollowupSectionTabByDelta,
        timelineFilterOptions,
    } = followupDebtor;

    const restrictedFollowupTabIds = useMemo(
        () => new Set(['correspondences', 'admin', 'dossier_controls', 'other_party']),
        [],
    );

    const executionExtras = (executionData || ({} as ExecutionFile)) as ExecutionFile & {
        perDebtorSalaries?: Record<string, string>;
        perDebtorGarnishments?: Record<string, string>;
    };
    
    // ⚖️ COURT-ORDERED LAWYER FEES (يتحملها المدين)
    const claimFinancialLedger = useExecutionDashboardCoreClaimFinancialLedgerPipeline({
        executionData,
        viewExecutionData,
        executionId,
        claimType,
        totalAmount,
        debtAmount,
        lawyerFeesAmount,
        executionFee,
        clientFeesAmount,
        courtFees,
        directorateFees,
        evictionCaseExpensesSum,
        liabilityGroupTabsMode,
        activeLiabilityGroup,
        allDebtorRowsForLiability,
        activeTimelineEvents,
        decisionsStorageExecutionId,
        debtorNotificationDate,
        effectiveDebtors,
        executionFileKey,
        decisionsReloadEpoch,
        persistExecutionMergeRef,
        executionDataRef,
        setThirdPartySeizuresUi,
        clearThirdPartyFundsDraft,
        setTimelineEvents,
        nextTimelineId,
        showToast,
        applyThirdPartySeizuresFromPatch,
        pushTimelineEventRef,
        focusSeizurePropertyInlineRef,
        focusSeizureMovableInlineRef,
        focusSeizureThirdPartyInlineRef,
        focusSeizureNoticeInlineRef,
        openSeizureRequestsTabRef: followupOrchestrator.openSeizureRequestsTabRef,
        setShowCoerciveActionForm,
        setSeizureDetailCompletion,
        setShowUnifiedExecutionModal: followupOrchestrator.setShowUnifiedExecutionModal,
        setEvictionAssetsTabUnlocked: followupOrchestrator.setEvictionAssetsTabUnlocked,
        seizedAssetsSnapshotRef,
        setSeizedAssets,
        setFinancialHubAutoOpenMode,
        setFinancialHubSeizedMovableId,
        setFinancialHubSeizedPropertyId,
        openFinancialHubLedger,
        debtorBrowserTabsMode,
        activeWorkspaceDebtorForFollowup,
        activeDebtorIsEmployee,
        docType,
        classification,
        activeDebtorEntityKind,
        activeDebtorIsDeceased,
        followupSpecialization,
        followupSectionTabOrder,
        followupModalTabs,
        followupTabsRestricted,
        restrictedFollowupTabIds,
        setUnifiedModalTab: followupOrchestrator.setUnifiedModalTab,
        showUnifiedExecutionModal,
        unifiedModalTab: followupOrchestrator.unifiedModalTab,
        hideCoerciveTabsForDebtorAgent,
        showPersonalCoerciveFollowupTab,
        setShowSolidaryCoerciveTargetModal: followupOrchestrator.setShowSolidaryCoerciveTargetModal,
        setSolidaryCoerciveActionPending: followupOrchestrator.setSolidaryCoerciveActionPending,
        followupModalChipTablistRef: followupOrchestrator.followupModalChipTablistRef,
        followupModalDebtorTabsRef: followupOrchestrator.followupModalDebtorTabsRef,
        isSolidaryLiability,
        allDebtorsUnified,
        seizureMatrixRef: followupOrchestrator.seizureMatrixRef,
    });

    const {
        parsedDebtAmount,
        parsedLawyerFees,
        parsedExecutionFee,
        parsedClientFees,
        parsedCourtFees,
        parsedDirectorateFees,
        total_execution_expenses,
        claimFinancials,
        isNonFinancialClaim,
        isVisitationClaim,
        isMaritalFurnitureClaim,
        maritalFurnitureItemsForFollowup,
        isAlimonyClaimType,
        principalDebtAmount,
        financialPrincipalAmount,
        financialLawyerFeesAmount,
        claimTypeForExecutionModule,
        executionModuleStrategy,
        hasEvictionSignals,
        hasEvictionTimelineSignals,
        isEvictionExecutionModule,
        judicialCustodiansResolved,
        judicialCustodianSalariesExpenseIqd,
        evictionCaseExpensesTotalForFinancial,
        evictionLawyerFeesInTotals,
        totalOwed,
        unifiedLedgerRevision,
        setUnifiedLedgerRevision,
        seizureMatrixLedgerParams,
        seizureMatrixLedgerParamsRef,
        debtorNotifiedForEvictionGrace,
        isAlimonyClaim,
        isHybridFeesNonMonetary,
        monetaryExecutionStrictPathFlag,
        monetaryStrictForSummoningEngine,
        ledgerSync,
        remainingBalanceForSeizure,
        settlementGuarantorGate,
        seizureMatrix,
        isPersonalStatusExecutionClaim,
        followupSeizureTabs,
        showGuarantorInSeizureFollowupTab,
        effectiveFollowupSectionTabOrder,
        effectiveFollowupModalTabs,
        openSeizureRequestsTab,
    } = claimFinancialLedger;

    const graceMasterPipeline = useExecutionDashboardCoreGraceMasterEvictionPipeline({
        executionData,
        executionId,
        debtorNotificationDate,
        debtors,
        effectiveDebtors,
        isEvictionExecutionModule,
        notificationCount,
        manualGraceCalendarExtra,
        voluntaryEndOptimistic,
        setVoluntaryEndOptimistic,
        noticeVoluntaryPeriodEndOptimistic,
        setNoticeVoluntaryPeriodEndOptimistic,
        debtorBrowserTabsMode,
        effectiveFollowupDebtorEntry,
        activeWorkspaceDebtorForFollowup,
        activeTimelineEventsDebtorScoped,
        coercionOrchestrator,
        claimType,
        isAlimonyClaim,
        monetaryStrictForSummoningEngine,
        forcedAttendanceIssued,
        initiator,
        paidDebt,
        totalOwed,
        parsedCourtFees,
        financialPrincipalAmount,
        paidCourtFees,
        paidDirectorateFees,
        paidClientFees,
        activeDebtorIsEmployee,
        followupSpecializationEffective,
        followupModalSpecializationEffective,
        followupModalDebtorIsEmployee,
        decisionsReloadEpoch,
        isRepresentingDebtor,
        decisionsStorageExecutionId,
        followupSpecialization,
        showPersonalCoerciveFollowupTab,
        showGuarantorInSeizureFollowupTab,
        isPersonalStatusExecutionClaim,
        isAlimonyClaimType,
        custodyRemovalClaimActive,
        employeeCoerciveDetentionRestricted,
        remainingBalanceForSeizure,
        viewExecutionData,
        settlementGuarantorGate,
        activeDebtorIsDeceased,
        assignmentWorkspaceCtx,
        primaryDebtorKeyResolved,
        personalTabLockedForEmployee,
        lastActionDate,
        dossierLifecycleRow,
        executionPaused,
        isPaused,
        pauseReason,
        executionFeeAdded,
        activeDebtorSolidary,
        allDebtorsUnified,
        followupOrchestrator,
        isHistoricalMode,
        debtorNotifiedForEvictionGrace,
        evictionPremisesUseResolved,
        todayYmd,
        timelineEventsRef,
        gracePeriodEnded,
        setGracePeriodEnded,
        setGracePeriodActive,
        showToastRef,
        showToast,
    });

    const {
        graceAndSummoning,
        generalMemoGraceAnchor,
        daysSinceNoticeCalculated,
        daysRemainingInGracePeriod,
        isGracePeriodExpiredNow,
        evictionGraceAnchorDate,
        isEvictionGraceExpiredCalendar,
        isEvictionGraceEffectivelyExpired,
        daysRemainingInEvictionGrace,
        isEvictionGraceExpiredNow,
        forcedSummoningAnalysis,
        shouldCalculateExecutionFee,
        calculatedExecutionFee,
        totalWithExecutionFee,
        remaining,
        isInBreach,
        earnerFinancialPersonalCoerciveActive,
        hideExecutiveDetentionJudgeCard,
        followupSpecializationWithEarnerGate,
        followupModalSpecializationEffectiveWithEarnerGate,
        unifiedCollectionApproved,
        otherPartyCreditorMirrorProps,
        statuteStatus,
        masterState,
        executionStatusRaw,
        executionStatus,
        statusMetadata,
        stayOfExecutionActive,
        coerciveUiState,
        coerciveUiLocked,
        dividedActiveDebtorCleared,
        executionCoerciveButtonDisabled,
        dossierStatusUi,
        coerciveDossierLocked,
        executionActionsGridLocked,
        executionToolsTimelineLockedUi,
        evictionProcedureLocked,
        isDebtorDeceasedForEvictionHeirs,
        creditorDeathMarked,
        debtorDeathMarked,
        creditorDeathMenuLabel,
        debtorDeathMenuLabel,
        heirSubstitutionAllowed,
        ongoingAlimonyClaim,
        alimonyBeneficiaryProfile,
        lawyerFeePayoutApproved,
        notifDateForEvictionVacate,
        residentialVacateDeadlineMaxIso,
        notificationLayerOkEviction,
        isResidentialVacateGraceFinished,
        evictionVacateLayerOk,
        evictionProcedureLockHint,
        evictionGraceBadgeInfo,
        policeAssistanceBadgeInfo,
    } = graceMasterPipeline;

    // ===========================
    // FINANCIAL CENTER ACCORDION & TABS STATE
    // ===========================
    // ✅ V10.8: Moved to top with other useState (lines 190-192)
    
    // ===========================
    // DOCUMENT DETAILS ACCORDION STATE
    // ===========================
    // ✅ V10.8: Moved to top with other useState (line 192)
    
    const financialStatus = useMemo(() => {
        if (remaining <= 0) {
            return { label: 'منتظم', color: 'emerald', pulse: false };
        }
        if (!gracePeriodEnded && daysSinceNoticeCalculated <= 7) {
            return { label: 'فترة الإمهال القانوني', color: 'amber', pulse: false };
        }
        if (gracePeriodEnded || daysSinceNoticeCalculated > 7) {
            return { label: 'جاهز للتنفيذ الجبري', color: 'rose', pulse: true };
        }
        return { label: 'إخلال - جاهز للتنفيذ', color: 'rose', pulse: true };
    }, [remaining, gracePeriodEnded, daysSinceNoticeCalculated]);
    
    const persistHandlerPipeline = useExecutionDashboardCorePersistHandlerPipeline({
        effectiveDebtors,
        financialPrincipalAmount,
        financialLawyerFeesAmount,
        claimType,
        isNonFinancialClaim,
        debtorBrowserTabsMode,
        effectiveFollowupDebtorEntry,
        activeWorkspaceDebtorForFollowup,
        executionData,
        executionId,
        decisionsReloadEpoch,
        isEvictionExecutionModule,
        unifiedCollectionApproved,
        notificationCount,
        forcedAttendanceIssued,
        coercionOrchestrator,
        isEvictionGraceExpiredNow,
        isGracePeriodExpiredNow,
        debtorNotificationDate,
        manualGraceCalendarExtra,
        lawyerStartedPostNoticeExecution,
        noticeVoluntaryPeriodEndOptimistic,
        voluntaryEndOptimistic,
        isEvictionGraceEffectivelyExpired,
        activeCoerciveActions,
        activeDebtorNoticeScope,
        debtorSummonsMarkerLocal,
        monetaryExecutionStrictPathFlag,
        isAlimonyClaim,
        executionExtras,
        unifiedSummonsTargetDebtorKey,
        activeDebtorIsDeceased,
        primaryDebtorKeyResolved,
        debtorNotifiedForEvictionGrace,
        remaining,
        daysSinceNoticeCalculated,
        executionFeeInjected,
        showToast,
        statuteStatus,
        showStatuteWarning,
        setShowStatuteWarning,
        lastActionDate,
        timelineEvents,
        caseNotesLog,
        caseTasksPending,
        financialLedger,
        gracePeriodActive,
        gracePeriodEnded,
        seizedAssets,
        seizureDraftsByDecisionId,
        realEstateSeizureAssets,
        debtorEvaded,
        arrestWarrantUnlocked,
        creditorAttended,
        executionPaused,
        paidDebt,
        paidCourtFees,
        paidDirectorateFees,
        paidClientFees,
        earnerFeeCollectionSm,
        followupOrchestrator,
        file,
        currentFileId,
        isMaritalFurnitureClaim,
        nextTimelineId,
        timelineEventsRef,
        persistExecutionMergeRef,
        pushTimelineEventRef,
        executionFileSnapshotRef,
        setShowDecisionsModal,
        showDecisionsModal,
        setCaseTasksPending,
        setTimelineEvents,
        setExecutionReportPrompt,
        setJudicialCustodianModalCtx,
        setJudicialCustodianModalOpen,
        setCaseNotesLog,
        decisionsStorageExecutionId,
        openBreakInventoryCompletion,
        openJudicialCustodianCompletion,
        isUnifiedTabActive,
        unifiedTabId,
        onUpdate,
        executionDataRef,
        seizureDraftsByDecisionIdRef,
        setExecutionStorageTick,
        showExecutionTrashModal,
        setShowExecutionTrashModal,
        caseNotesLogRef,
        caseTasksPendingRef,
        setPermanentDeleteTimelineId,
        viewExecutionData,
        isHistoricalMode,
        activeSubFileId,
        parentDossierId,
        setSeizureDraftsByDecisionId,
        seizedAssetsSnapshotRef,
        maritalFurnitureItemsForFollowup,
        setActiveCoerciveActions,
    });

    const {
        debtorSummonsProfileBundle,
        debtorOccupation,
        isDebtorGovernmentEmployee,
        isDebtorFreelancer,
        isDebtorRetired,
        debtorSummonsProfile,
        followupDebtorSummonsProfile,
        followupIsDebtorGovernmentEmployee,
        followupIsDebtorRetired,
        showSalaryCaptureForEmployee,
        subsequentNoticeFlow,
        earnerForcedActionUnlocked,
        followupEarnerForcedActionUnlocked,
        baseSubsequentNoticeUnlocked,
        evictionSubsequentNoticeUnlocked,
        subsequentNoticeUnlocked,
        anyExecutorDecisionResolvedForMemoBadge,
        primaryDebtorTaklifActive,
        primaryMemoNoticeBadge,
        primaryDebtorNoticeYmdResolved,
        showDebtorUnservedMemoBadge,
        primaryDebtorAbsenceBadge,
        showDebtorSummonsAttendanceBadge,
        noticeKindGoalStrictBinding,
        employeeAssignmentTabEnabled,
        resolvedEmployeeSummonsAssignment,
        showEmployeeAssignmentCoerciveBlock,
        employeeFinancialSalaryOnlyCoercive,
        monetaryCoerciveLimitedOnly,
        followupEmployeeFinancialSalaryOnlyCoercive,
        followupMonetaryCoerciveLimitedOnly,
        followupGarnishmentAmountPreview,
        saveExecutionData,
        executorApprovalActions,
        pushSeizureAuctionCalendarAppointment,
        pendingExecutorOpeners,
        tryOpenPendingBreakInventoryLedger,
        tryOpenPendingCustodianDetails,
        persistExecutionMergeBinding,
        persistExecutionMerge,
        trashAndPinsHandlers,
        timelineEditDraft,
        setTimelineEditDraft,
        moveTimelineEventToTrash,
        toggleTimelineEventPin,
        requestEditTimelineEvent,
        restoreTimelineEventFromTrash,
        permanentlyDeleteTimelineEvent,
        moveCaseNoteToTrash,
        moveCaseTaskToTrash,
        toggleCaseNotePin,
        toggleCaseTaskPin,
        saveTimelineEditDraft,
        restoreCaseNoteFromTrash,
        permanentlyDeleteCaseNote,
        restoreCaseTaskFromTrash,
        permanentlyDeleteCaseTask,
        partyEditWorkflow,
        editPartyTarget,
        setEditPartyTarget,
        partyEditDraft,
        setPartyEditDraft,
        partyEditHeirDeleteConfirmIdx,
        setPartyEditHeirDeleteConfirmIdx,
        heirsQuickView,
        setHeirsQuickView,
        openEditParty,
        buildPartyHeirsRows,
        openHeirsQuickView,
        savePartyEditDraft,
        removeHeirFromPartyEditDraftAtIndex,
        togglePartyEditHeirClient,
    } = persistHandlerPipeline;

    const specificDeliveryConvertedAmount =
        (executionData as { specificDeliveryConvertedAmount?: number | null } | null | undefined)
            ?.specificDeliveryConvertedAmount ?? null;
    const specificDeliveryFinancialized = Boolean(
        (executionData as { specificDeliveryFinancialized?: boolean } | null | undefined)
            ?.specificDeliveryFinancialized,
    );
    return {
        workspacePipeline,
        fileMetadataBinding,
        followupDebtor,
        claimFinancialLedger,
        graceMasterPipeline,
        persistHandlerPipeline,
        financialStatus,
        specificDeliveryConvertedAmount,
        specificDeliveryFinancialized,
    };
}
