import type { Dispatch, SetStateAction } from 'react';
import type { ExecutionFile } from '@/app/types/execution';
import type { ExecutionFollowupOrchestratorSlice } from '../../orchestrators/executionFollowupOrchestratorTypes';
import type { ExecutionDashboardCoreWorkspacePipelineValue } from './executionDashboardCoreWorkspacePipelineTypes';
import type { ExecutionDashboardCoreBootPipelineValue } from './executionDashboardCoreBootPipelineTypes';

export type UseExecutionDashboardCoreFollowupDebtorPipelineInput = {
    executionData: ExecutionFile | null | undefined;
    viewExecutionData: ExecutionFile | null | undefined;
    executionId: string | undefined;
    decisionsStorageExecutionId: string;
    decisionsReloadEpoch: number;
    claimType: string;
    creditors: ExecutionFile['creditors'];
    debtors: ExecutionFile['debtors'];
    mergedTimelineEvents: ExecutionDashboardCoreWorkspacePipelineValue['mergedTimelineEvents'];
    activeTimelineEvents: ExecutionDashboardCoreWorkspacePipelineValue['activeTimelineEvents'];
    activeCoerciveActions: ExecutionDashboardCoreWorkspacePipelineValue['activeCoerciveActions'];
    realEstateSeizureRegistryAssets: ExecutionDashboardCoreWorkspacePipelineValue['realEstateSeizureRegistryAssets'];
    salarySeizureRegistryAssets: ExecutionDashboardCoreWorkspacePipelineValue['salarySeizureRegistryAssets'];
    movableSeizureRegistryAssets: ExecutionDashboardCoreWorkspacePipelineValue['movableSeizureRegistryAssets'];
    thirdPartySeizureRegistryAssets: ExecutionDashboardCoreWorkspacePipelineValue['thirdPartySeizureRegistryAssets'];
    thirdPartySeizuresUi: ExecutionDashboardCoreWorkspacePipelineValue['thirdPartySeizuresUi'];
    showToast: ExecutionDashboardCoreWorkspacePipelineValue['showToast'];
    showUnifiedExecutionModal: boolean;
    dossierFileKey: string;
    executionFileKey: string;
    setShowDecisionsModal: (show: boolean) => void;
    showDecisionsModal: boolean;
    setActiveTimelineFilter: Dispatch<SetStateAction<string>>;
    setShowExtraCreditors: (v: boolean) => void;
    setShowExtraDebtors: (v: boolean) => void;
    caseTasksPendingRef: ExecutionDashboardCoreWorkspacePipelineValue['caseTasksPendingRef'];
    setCaseTasksPending: ExecutionDashboardCoreWorkspacePipelineValue['setCaseTasksPending'];
    setTimelineEvents: ExecutionDashboardCoreWorkspacePipelineValue['setTimelineEvents'];
    persistExecutionMergeRef: ExecutionDashboardCoreWorkspacePipelineValue['persistExecutionMergeRef'];
    setNotificationCount: React.Dispatch<React.SetStateAction<number>>;
    setDebtorSummonsMarkerLocal: ExecutionDashboardCoreBootPipelineValue['setDebtorSummonsMarkerLocal'];
    pushTimelineEventRef: ExecutionDashboardCoreWorkspacePipelineValue['pushTimelineEventRef'];
    nextTimelineId: ExecutionDashboardCoreWorkspacePipelineValue['nextTimelineId'];
    followupOrchestrator: ExecutionFollowupOrchestratorSlice;
};
