// @ts-nocheck
/** Phase B — handler cluster seizureFollowup */
import { useExecutionDashboardFollowupSeizureHandlers } from './useExecutionDashboardFollowupSeizureHandlers';
import { useExecutionDashboardSeizureAssetModalHandlers } from './useExecutionDashboardSeizureAssetModalHandlers';
import type { ExecutionDashboardCoreHandlerClusterInput } from './executionDashboardCoreHandlerClusterTypes';
import type { HandlerClusterPushTimelineDeps } from './executionDashboardCoreHandlerClusterTypes';

export function useExecutionDashboardCoreHandlerClusterSeizureFollowup(
    c: ExecutionDashboardCoreHandlerClusterInput,
    deps: HandlerClusterPushTimelineDeps,
) {
    const { pushTimelineEvent } = deps;

    const {
        decisionsStorageExecutionId,
        executionDataRef,
        executionId,
        linkSeizureAuctionToAppointments,
        movableSeizureSubjectDraft,
        nextTimelineId,
        openSeizureRequestsTabRef,
        persistExecutionMerge,
        propertySeizureSubjectDraft,
        publicationDateYmdDraft,
        publicationModalEntityId,
        publicationModalEntityKind,
        publicationNewspaperNameDraft,
        pushSeizureAuctionCalendarAppointment,
        seizedPropertyAuctionDateDraft,
        seizedPropertyAuctionDepositAmountDraft,
        seizedPropertyAuctionResultAmountDraft,
        seizedPropertyAuctionResultBuyerNameDraft,
        seizedPropertyAuctionResultEntityKind,
        seizedPropertyAuctionResultOutcome,
        seizedPropertyAuctionResultPropertyId,
        seizedPropertyAwardAmountDraft,
        seizedPropertyBuyerNameDraft,
        seizedPropertyExpertPriceDraft,
        seizedPropertyExpertReportDateDraft,
        seizedPropertyExpertsNamesDraft,
        seizedPropertyStepDecisionId,
        seizedPropertyStepEntityKind,
        seizedPropertyStepKind,
        seizedPropertyStepNotesDraft,
        seizedPropertyStepPropertyId,
        seizureMarkDateDraft,
        seizureMarkEntityDraft,
        seizureMarkLetterNumberDraft,
        seizureMarkModalEntityId,
        seizureMarkModalEntityKind,
        seizureMatrixLedgerParamsRef,
        setMovableSeizureRequestModalOpen,
        setMovableSeizureSubjectDraft,
        setPropertySeizureRequestModalOpen,
        setPropertySeizureSubjectDraft,
        setPublicationDateYmdDraft,
        setPublicationModalEntityId,
        setPublicationModalEntityKind,
        setPublicationModalOpen,
        setPublicationNewspaperNameDraft,
        setSeizedPropertyAuctionDateDraft,
        setSeizedPropertyAuctionDepositAmountDraft,
        setSeizedPropertyAuctionResultAmountDraft,
        setSeizedPropertyAuctionResultBuyerNameDraft,
        setSeizedPropertyAuctionResultEntityKind,
        setSeizedPropertyAuctionResultModalOpen,
        setSeizedPropertyAuctionResultOutcome,
        setSeizedPropertyAuctionResultPropertyId,
        setSeizedPropertyAwardAmountDraft,
        setSeizedPropertyBuyerNameDraft,
        setSeizedPropertyExpertPriceDraft,
        setSeizedPropertyExpertReportDateDraft,
        setSeizedPropertyExpertsNamesDraft,
        setSeizedPropertyStepDecisionId,
        setSeizedPropertyStepEntityKind,
        setSeizedPropertyStepKind,
        setSeizedPropertyStepModalOpen,
        setSeizedPropertyStepNotesDraft,
        setSeizedPropertyStepPropertyId,
        setSeizureDetailCompletion,
        setSeizureMarkDateDraft,
        setSeizureMarkEntityDraft,
        setSeizureMarkLetterNumberDraft,
        setSeizureMarkModalEntityId,
        setSeizureMarkModalEntityKind,
        setSeizureMarkModalOpen,
        setShowCoerciveActionForm,
        setShowUnifiedExecutionModal,
        setUnifiedLedgerRevision,
        showToast,
    } = c as any;

    const followupSeizureHandlers = useExecutionDashboardFollowupSeizureHandlers({
        decisionsStorageExecutionId,
        executionDataRef,
        nextTimelineId,
        persistExecutionMerge,
        pushTimelineEvent,
        showToast,
        propertySeizureSubjectDraft,
        setPropertySeizureRequestModalOpen,
        setPropertySeizureSubjectDraft,
        movableSeizureSubjectDraft,
        setMovableSeizureRequestModalOpen,
        setMovableSeizureSubjectDraft,
    });

const {
        submitPropertySeizureRequest,
        submitMovableSeizureRequest,
        saveSeizedPropertyInitForDecision,
        saveSeizedMovableInitForDecision,
    } = followupSeizureHandlers;



    const seizureAssetModalHandlers = useExecutionDashboardSeizureAssetModalHandlers({
        decisionsStorageExecutionId,
        executionId,
        executionDataRef,
        openSeizureRequestsTabRef,
        nextTimelineId,
        persistExecutionMerge,
        pushTimelineEvent,
        showToast,
        linkSeizureAuctionToAppointments,
        pushSeizureAuctionCalendarAppointment,
        seizureMatrixLedgerParamsRef,
        setUnifiedLedgerRevision,
        setShowCoerciveActionForm,
        setSeizureDetailCompletion,
        setShowUnifiedExecutionModal,
        seizureMarkModalEntityId,
        seizureMarkModalEntityKind,
        seizureMarkLetterNumberDraft,
        seizureMarkDateDraft,
        seizureMarkEntityDraft,
        setSeizureMarkModalOpen,
        setSeizureMarkModalEntityId,
        setSeizureMarkModalEntityKind,
        setSeizureMarkLetterNumberDraft,
        setSeizureMarkDateDraft,
        setSeizureMarkEntityDraft,
        publicationModalEntityId,
        publicationModalEntityKind,
        publicationNewspaperNameDraft,
        publicationDateYmdDraft,
        setPublicationModalOpen,
        setPublicationModalEntityId,
        setPublicationModalEntityKind,
        setPublicationNewspaperNameDraft,
        setPublicationDateYmdDraft,
        seizedPropertyAuctionResultPropertyId,
        seizedPropertyAuctionResultEntityKind,
        seizedPropertyAuctionResultOutcome,
        seizedPropertyAuctionResultBuyerNameDraft,
        seizedPropertyAuctionResultAmountDraft,
        seizedPropertyAuctionDepositAmountDraft,
        setSeizedPropertyAuctionResultModalOpen,
        setSeizedPropertyAuctionResultPropertyId,
        setSeizedPropertyAuctionResultEntityKind,
        setSeizedPropertyAuctionResultOutcome,
        setSeizedPropertyAuctionResultBuyerNameDraft,
        setSeizedPropertyAuctionResultAmountDraft,
        setSeizedPropertyAuctionDepositAmountDraft,
        seizedPropertyStepDecisionId,
        seizedPropertyStepEntityKind,
        seizedPropertyStepPropertyId,
        seizedPropertyStepKind,
        seizedPropertyExpertsNamesDraft,
        seizedPropertyExpertReportDateDraft,
        seizedPropertyExpertPriceDraft,
        seizedPropertyAuctionDateDraft,
        seizedPropertyBuyerNameDraft,
        seizedPropertyAwardAmountDraft,
        seizedPropertyStepNotesDraft,
        setSeizedPropertyStepModalOpen,
        setSeizedPropertyStepDecisionId,
        setSeizedPropertyStepPropertyId,
        setSeizedPropertyStepEntityKind,
        setSeizedPropertyStepKind,
        setSeizedPropertyExpertsNamesDraft,
        setSeizedPropertyExpertReportDateDraft,
        setSeizedPropertyExpertPriceDraft,
        setSeizedPropertyAuctionDateDraft,
        setSeizedPropertyBuyerNameDraft,
        setSeizedPropertyAwardAmountDraft,
        setSeizedPropertyStepNotesDraft,
    });

const {
        focusSeizurePropertyInlineCompletion,
        focusSeizureMovableInlineCompletion,
        focusSeizureThirdPartyInlineCompletion,
        focusSeizureNoticeInlineCompletion,
        openSeizureMarkModal,
        openPublicationModal,
        openAuctionResultModal,
        saveSeizureMarkConfirmation,
        savePublicationDetails,
        saveSeizedPropertyStepDetails,
        saveSeizedPropertyAuctionSessionResult,
    } = seizureAssetModalHandlers;
    return {
        followupSeizureHandlers,
        seizureAssetModalHandlers,
        focusSeizurePropertyInlineCompletion,
        focusSeizureMovableInlineCompletion,
        focusSeizureThirdPartyInlineCompletion,
        focusSeizureNoticeInlineCompletion,
    };
}
