import { useExecutionDashboardSeizureAssetModalHandlers } from './useExecutionDashboardSeizureAssetModalHandlers';
import type {
    ExecutionDashboardCoreHandlerClusterInput,
    HandlerClusterPushTimelineDeps,
} from './executionDashboardCoreHandlerClusterTypes';

function bindFocusRef(target: unknown, value: unknown): void {
    if (!target || typeof target !== 'object' || !('current' in target)) return;
    (target as { current?: unknown }).current = value;
}

export function useExecutionDashboardCoreHandlerClusterSeizureAssetModal(
    c: ExecutionDashboardCoreHandlerClusterInput,
    deps: HandlerClusterPushTimelineDeps,
) {
    const { pushTimelineEvent } = deps;
    const resolved = c;

    const {
        decisionsStorageExecutionId,
        executionId,
        executionDataRef,
        openSeizureRequestsTabRef,
        nextTimelineId,
        persistExecutionMerge,
        showToast,
        linkSeizureAuctionToAppointments,
        pushSeizureAuctionCalendarAppointment,
        seizureMatrixLedgerParamsRef,
        setUnifiedLedgerRevision,
        setShowCoerciveActionForm,
        setSeizureDetailCompletion,
        setShowUnifiedExecutionModal,
        seizureMarkModalEntityId,
        seizureMarkModalEntityKind,
        seizureMarkLetterNumberDraft,
        seizureMarkDateDraft,
        seizureMarkEntityDraft,
        setSeizureMarkModalOpen,
        setSeizureMarkModalEntityId,
        setSeizureMarkModalEntityKind,
        setSeizureMarkLetterNumberDraft,
        setSeizureMarkDateDraft,
        setSeizureMarkEntityDraft,
        publicationModalEntityId,
        publicationModalEntityKind,
        publicationNewspaperNameDraft,
        publicationDateYmdDraft,
        setPublicationModalOpen,
        setPublicationModalEntityId,
        setPublicationModalEntityKind,
        setPublicationNewspaperNameDraft,
        setPublicationDateYmdDraft,
        seizedPropertyAuctionResultPropertyId,
        seizedPropertyAuctionResultEntityKind,
        seizedPropertyAuctionResultOutcome,
        seizedPropertyAuctionResultBuyerNameDraft,
        seizedPropertyAuctionResultAmountDraft,
        seizedPropertyAuctionDepositAmountDraft,
        setSeizedPropertyAuctionResultModalOpen,
        setSeizedPropertyAuctionResultPropertyId,
        setSeizedPropertyAuctionResultEntityKind,
        setSeizedPropertyAuctionResultOutcome,
        setSeizedPropertyAuctionResultBuyerNameDraft,
        setSeizedPropertyAuctionResultAmountDraft,
        setSeizedPropertyAuctionDepositAmountDraft,
        seizedPropertyStepDecisionId,
        seizedPropertyStepEntityKind,
        seizedPropertyStepPropertyId,
        seizedPropertyStepKind,
        seizedPropertyExpertsNamesDraft,
        seizedPropertyExpertReportDateDraft,
        seizedPropertyExpertPriceDraft,
        seizedPropertyAuctionDateDraft,
        seizedPropertyBuyerNameDraft,
        seizedPropertyAwardAmountDraft,
        seizedPropertyStepNotesDraft,
        setSeizedPropertyStepModalOpen,
        setSeizedPropertyStepDecisionId,
        setSeizedPropertyStepPropertyId,
        setSeizedPropertyStepEntityKind,
        setSeizedPropertyStepKind,
        setSeizedPropertyExpertsNamesDraft,
        setSeizedPropertyExpertReportDateDraft,
        setSeizedPropertyExpertPriceDraft,
        setSeizedPropertyAuctionDateDraft,
        setSeizedPropertyBuyerNameDraft,
        setSeizedPropertyAwardAmountDraft,
        setSeizedPropertyStepNotesDraft,
        focusSeizurePropertyInlineRef,
        focusSeizureMovableInlineRef,
        focusSeizureThirdPartyInlineRef,
        focusSeizureNoticeInlineRef,
    } = resolved;

    const seizureAssetModalHandlers = useExecutionDashboardSeizureAssetModalHandlers({
        decisionsStorageExecutionId,
        executionId,
        executionDataRef,
        openSeizureRequestsTabRef,
        nextTimelineId,
        persistExecutionMerge,
        pushTimelineEvent,
        showToast,
        linkSeizureAuctionToAppointments,
        pushSeizureAuctionCalendarAppointment,
        seizureMatrixLedgerParamsRef,
        setUnifiedLedgerRevision,
        setShowCoerciveActionForm,
        setSeizureDetailCompletion,
        openFollowupModalPersisted: resolved.openFollowupModalPersisted,
        setShowUnifiedExecutionModal,
        seizureMarkModalEntityId,
        seizureMarkModalEntityKind,
        seizureMarkLetterNumberDraft,
        seizureMarkDateDraft,
        seizureMarkEntityDraft,
        setSeizureMarkModalOpen,
        setSeizureMarkModalEntityId,
        setSeizureMarkModalEntityKind,
        setSeizureMarkLetterNumberDraft,
        setSeizureMarkDateDraft,
        setSeizureMarkEntityDraft,
        publicationModalEntityId,
        publicationModalEntityKind,
        publicationNewspaperNameDraft,
        publicationDateYmdDraft,
        setPublicationModalOpen,
        setPublicationModalEntityId,
        setPublicationModalEntityKind,
        setPublicationNewspaperNameDraft,
        setPublicationDateYmdDraft,
        seizedPropertyAuctionResultPropertyId,
        seizedPropertyAuctionResultEntityKind,
        seizedPropertyAuctionResultOutcome,
        seizedPropertyAuctionResultBuyerNameDraft,
        seizedPropertyAuctionResultAmountDraft,
        seizedPropertyAuctionDepositAmountDraft,
        setSeizedPropertyAuctionResultModalOpen,
        setSeizedPropertyAuctionResultPropertyId,
        setSeizedPropertyAuctionResultEntityKind,
        setSeizedPropertyAuctionResultOutcome,
        setSeizedPropertyAuctionResultBuyerNameDraft,
        setSeizedPropertyAuctionResultAmountDraft,
        setSeizedPropertyAuctionDepositAmountDraft,
        seizedPropertyStepDecisionId,
        seizedPropertyStepEntityKind,
        seizedPropertyStepPropertyId,
        seizedPropertyStepKind,
        seizedPropertyExpertsNamesDraft,
        seizedPropertyExpertReportDateDraft,
        seizedPropertyExpertPriceDraft,
        seizedPropertyAuctionDateDraft,
        seizedPropertyBuyerNameDraft,
        seizedPropertyAwardAmountDraft,
        seizedPropertyStepNotesDraft,
        setSeizedPropertyStepModalOpen,
        setSeizedPropertyStepDecisionId,
        setSeizedPropertyStepPropertyId,
        setSeizedPropertyStepEntityKind,
        setSeizedPropertyStepKind,
        setSeizedPropertyExpertsNamesDraft,
        setSeizedPropertyExpertReportDateDraft,
        setSeizedPropertyExpertPriceDraft,
        setSeizedPropertyAuctionDateDraft,
        setSeizedPropertyBuyerNameDraft,
        setSeizedPropertyAwardAmountDraft,
        setSeizedPropertyStepNotesDraft,
    });

    const {
        focusSeizurePropertyInlineCompletion,
        focusSeizureMovableInlineCompletion,
        focusSeizureThirdPartyInlineCompletion,
        focusSeizureNoticeInlineCompletion,
    } = seizureAssetModalHandlers;

    bindFocusRef(focusSeizurePropertyInlineRef, focusSeizurePropertyInlineCompletion);
    bindFocusRef(focusSeizureMovableInlineRef, focusSeizureMovableInlineCompletion);
    bindFocusRef(focusSeizureThirdPartyInlineRef, focusSeizureThirdPartyInlineCompletion);
    bindFocusRef(focusSeizureNoticeInlineRef, focusSeizureNoticeInlineCompletion);

    return {
        seizureAssetModalHandlers,
        focusSeizurePropertyInlineCompletion,
        focusSeizureMovableInlineCompletion,
        focusSeizureThirdPartyInlineCompletion,
        focusSeizureNoticeInlineCompletion,
    };
}
