import { useCallback } from 'react';
import { saveSeizedPropertyAuctionSessionResult as runSaveSeizedPropertyAuctionSessionResult } from './executionDashboardAuctionSessionResult';
import {
    savePublicationDetails as runSavePublicationDetails,
    saveSeizedPropertyStepDetails as runSaveSeizedPropertyStepDetails,
    saveSeizureMarkConfirmation as runSaveSeizureMarkConfirmation,
} from './executionDashboardSeizedPropertyModals';
import type { UseExecutionDashboardSeizureAssetModalHandlersParams } from './useExecutionDashboardSeizureAssetModalHandlers.types';

export function useExecutionDashboardSeizureAssetModalSaveHandlers(
    params: UseExecutionDashboardSeizureAssetModalHandlersParams,
) {
    const {
        decisionsStorageExecutionId,
        executionDataRef,
        nextTimelineId,
        persistExecutionMerge,
        pushTimelineEvent,
        showToast,
        linkSeizureAuctionToAppointments,
        pushSeizureAuctionCalendarAppointment,
        seizureMatrixLedgerParamsRef,
        setUnifiedLedgerRevision,
        seizureMarkModalEntityId,
        seizureMarkModalEntityKind,
        seizureMarkLetterNumberDraft,
        seizureMarkDateDraft,
        seizureMarkEntityDraft,
        setSeizureMarkModalOpen,
        setSeizureMarkModalEntityId,
        setSeizureMarkLetterNumberDraft,
        setSeizureMarkDateDraft,
        setSeizureMarkEntityDraft,
        publicationModalEntityId,
        publicationModalEntityKind,
        publicationNewspaperNameDraft,
        publicationDateYmdDraft,
        setPublicationModalOpen,
        setPublicationModalEntityId,
        setPublicationNewspaperNameDraft,
        setPublicationDateYmdDraft,
        seizedPropertyAuctionResultPropertyId,
        seizedPropertyAuctionResultEntityKind,
        seizedPropertyAuctionResultOutcome,
        seizedPropertyAuctionResultBuyerNameDraft,
        seizedPropertyAuctionResultAmountDraft,
        seizedPropertyAuctionDepositAmountDraft,
        setSeizedPropertyAuctionResultModalOpen,
        setSeizedPropertyAuctionResultPropertyId,
        setSeizedPropertyAuctionResultEntityKind,
        setSeizedPropertyAuctionResultOutcome,
        setSeizedPropertyAuctionResultBuyerNameDraft,
        setSeizedPropertyAuctionResultAmountDraft,
        setSeizedPropertyAuctionDepositAmountDraft,
        seizedPropertyStepDecisionId,
        seizedPropertyStepEntityKind,
        seizedPropertyStepPropertyId,
        seizedPropertyStepKind,
        seizedPropertyExpertsNamesDraft,
        seizedPropertyExpertReportDateDraft,
        seizedPropertyExpertPriceDraft,
        seizedPropertyAuctionDateDraft,
        seizedPropertyBuyerNameDraft,
        seizedPropertyAwardAmountDraft,
        seizedPropertyStepNotesDraft,
        setSeizedPropertyStepModalOpen,
        setSeizedPropertyStepDecisionId,
        setSeizedPropertyStepPropertyId,
        setSeizedPropertyStepEntityKind,
        setSeizedPropertyStepKind,
        setSeizedPropertyExpertsNamesDraft,
        setSeizedPropertyExpertReportDateDraft,
        setSeizedPropertyExpertPriceDraft,
        setSeizedPropertyAuctionDateDraft,
        setSeizedPropertyBuyerNameDraft,
        setSeizedPropertyAwardAmountDraft,
        setSeizedPropertyStepNotesDraft,
    } = params;

    const saveSeizureMarkConfirmation = useCallback(() => {
        runSaveSeizureMarkConfirmation({
            seizureMarkModalEntityId,
            seizureMarkModalEntityKind,
            seizureMarkLetterNumberDraft,
            seizureMarkDateDraft,
            seizureMarkEntityDraft,
            executionDataRef,
            persistExecutionMerge,
            pushTimelineEvent,
            nextTimelineId,
            setSeizureMarkModalOpen,
            setSeizureMarkModalEntityId,
            setSeizureMarkLetterNumberDraft,
            setSeizureMarkDateDraft,
            setSeizureMarkEntityDraft,
            showToast,
        });
    }, [
        executionDataRef,
        nextTimelineId,
        persistExecutionMerge,
        pushTimelineEvent,
        seizureMarkDateDraft,
        seizureMarkEntityDraft,
        seizureMarkLetterNumberDraft,
        seizureMarkModalEntityId,
        seizureMarkModalEntityKind,
        showToast,
        setSeizureMarkModalEntityId,
        setSeizureMarkDateDraft,
        setSeizureMarkEntityDraft,
        setSeizureMarkLetterNumberDraft,
        setSeizureMarkModalOpen,
    ]);

    const savePublicationDetails = useCallback(() => {
        runSavePublicationDetails({
            publicationModalEntityId,
            publicationModalEntityKind,
            publicationNewspaperNameDraft,
            publicationDateYmdDraft,
            executionDataRef,
            persistExecutionMerge,
            pushTimelineEvent,
            nextTimelineId,
            setPublicationModalOpen,
            setPublicationModalEntityId,
            setPublicationNewspaperNameDraft,
            setPublicationDateYmdDraft,
            showToast,
        });
    }, [
        executionDataRef,
        nextTimelineId,
        persistExecutionMerge,
        publicationDateYmdDraft,
        publicationModalEntityId,
        publicationModalEntityKind,
        publicationNewspaperNameDraft,
        pushTimelineEvent,
        showToast,
        setPublicationDateYmdDraft,
        setPublicationModalEntityId,
        setPublicationModalOpen,
        setPublicationNewspaperNameDraft,
    ]);

    const saveSeizedPropertyStepDetails = useCallback(() => {
        runSaveSeizedPropertyStepDetails({
            decisionsStorageExecutionId,
            seizedPropertyStepDecisionId,
            seizedPropertyStepEntityKind,
            seizedPropertyStepPropertyId,
            seizedPropertyStepKind,
            seizedPropertyExpertsNamesDraft,
            seizedPropertyExpertReportDateDraft,
            seizedPropertyExpertPriceDraft,
            seizedPropertyAuctionDateDraft,
            seizedPropertyBuyerNameDraft,
            seizedPropertyAwardAmountDraft,
            seizedPropertyStepNotesDraft,
            linkSeizureAuctionToAppointments,
            executionDataRef,
            seizureMatrixLedgerParamsRef,
            setUnifiedLedgerRevision,
            persistExecutionMerge,
            pushTimelineEvent,
            nextTimelineId,
            pushSeizureAuctionCalendarAppointment,
            setSeizedPropertyStepModalOpen,
            setSeizedPropertyStepDecisionId,
            setSeizedPropertyStepPropertyId,
            setSeizedPropertyStepEntityKind,
            setSeizedPropertyStepKind,
            setSeizedPropertyExpertsNamesDraft,
            setSeizedPropertyExpertReportDateDraft,
            setSeizedPropertyExpertPriceDraft,
            setSeizedPropertyAuctionDateDraft,
            setSeizedPropertyBuyerNameDraft,
            setSeizedPropertyAwardAmountDraft,
            setSeizedPropertyStepNotesDraft,
            showToast,
        });
    }, [
        decisionsStorageExecutionId,
        executionDataRef,
        linkSeizureAuctionToAppointments,
        nextTimelineId,
        persistExecutionMerge,
        pushSeizureAuctionCalendarAppointment,
        pushTimelineEvent,
        seizureMatrixLedgerParamsRef,
        seizedPropertyAuctionDateDraft,
        seizedPropertyAwardAmountDraft,
        seizedPropertyBuyerNameDraft,
        seizedPropertyExpertPriceDraft,
        seizedPropertyExpertReportDateDraft,
        seizedPropertyExpertsNamesDraft,
        seizedPropertyStepDecisionId,
        seizedPropertyStepEntityKind,
        seizedPropertyStepKind,
        seizedPropertyStepNotesDraft,
        seizedPropertyStepPropertyId,
        setUnifiedLedgerRevision,
        showToast,
        setSeizedPropertyAuctionDateDraft,
        setSeizedPropertyAwardAmountDraft,
        setSeizedPropertyBuyerNameDraft,
        setSeizedPropertyExpertPriceDraft,
        setSeizedPropertyExpertReportDateDraft,
        setSeizedPropertyExpertsNamesDraft,
        setSeizedPropertyStepDecisionId,
        setSeizedPropertyStepEntityKind,
        setSeizedPropertyStepKind,
        setSeizedPropertyStepModalOpen,
        setSeizedPropertyStepNotesDraft,
        setSeizedPropertyStepPropertyId,
    ]);

    const saveSeizedPropertyAuctionSessionResult = useCallback(() => {
        runSaveSeizedPropertyAuctionSessionResult({
            seizedPropertyAuctionResultPropertyId,
            seizedPropertyAuctionResultEntityKind,
            seizedPropertyAuctionResultOutcome,
            seizedPropertyAuctionResultBuyerNameDraft,
            seizedPropertyAuctionResultAmountDraft,
            seizedPropertyAuctionDepositAmountDraft,
            executionDataRef,
            persistExecutionMerge,
            pushTimelineEvent,
            nextTimelineId,
            setSeizedPropertyAuctionResultModalOpen,
            setSeizedPropertyAuctionResultPropertyId,
            setSeizedPropertyAuctionResultEntityKind,
            setSeizedPropertyAuctionResultOutcome,
            setSeizedPropertyAuctionResultBuyerNameDraft,
            setSeizedPropertyAuctionResultAmountDraft,
            setSeizedPropertyAuctionDepositAmountDraft,
            showToast,
        });
    }, [
        executionDataRef,
        nextTimelineId,
        persistExecutionMerge,
        pushTimelineEvent,
        seizedPropertyAuctionDepositAmountDraft,
        seizedPropertyAuctionResultAmountDraft,
        seizedPropertyAuctionResultBuyerNameDraft,
        seizedPropertyAuctionResultEntityKind,
        seizedPropertyAuctionResultOutcome,
        seizedPropertyAuctionResultPropertyId,
        showToast,
        setSeizedPropertyAuctionDepositAmountDraft,
        setSeizedPropertyAuctionResultAmountDraft,
        setSeizedPropertyAuctionResultBuyerNameDraft,
        setSeizedPropertyAuctionResultEntityKind,
        setSeizedPropertyAuctionResultModalOpen,
        setSeizedPropertyAuctionResultOutcome,
        setSeizedPropertyAuctionResultPropertyId,
    ]);

    return {
        saveSeizureMarkConfirmation,
        savePublicationDetails,
        saveSeizedPropertyStepDetails,
        saveSeizedPropertyAuctionSessionResult,
    };
}
