import type { Dispatch, MutableRefObject, SetStateAction } from 'react';
import type { ExecutionFile, TimelineEvent } from '@/app/types/execution';
import type { UnifiedLedgerTotalParams } from '@/app/slices/financial/ledgerPublic';
import type { OpenFollowupModalPersistedFn } from '../../utils/followupModalOpen';

export type UseExecutionDashboardSeizureAssetModalHandlersParams = {
    decisionsStorageExecutionId: string | undefined;
    executionId: string | undefined;
    executionDataRef: MutableRefObject<ExecutionFile | null | undefined>;
    openSeizureRequestsTabRef: MutableRefObject<(() => void) | null>;
    nextTimelineId: () => string;
    persistExecutionMerge: (patch: Record<string, unknown>) => void;
    pushTimelineEvent: (ev: TimelineEvent) => void;
    showToast: (message: string, type?: string) => void;
    linkSeizureAuctionToAppointments: boolean;
    pushSeizureAuctionCalendarAppointment: (input: Record<string, unknown>) => void;
    seizureMatrixLedgerParamsRef: MutableRefObject<UnifiedLedgerTotalParams | null>;
    setUnifiedLedgerRevision: Dispatch<SetStateAction<number>>;
    setShowCoerciveActionForm: Dispatch<SetStateAction<string | null>>;
    setSeizureDetailCompletion: Dispatch<SetStateAction<unknown>>;
    setShowUnifiedExecutionModal: (show: boolean) => void;
    openFollowupModalPersisted?: OpenFollowupModalPersistedFn;
    seizureMarkModalEntityId: string | null;
    seizureMarkModalEntityKind: 'property' | 'movable';
    seizureMarkLetterNumberDraft: string;
    seizureMarkDateDraft: string;
    seizureMarkEntityDraft: string;
    setSeizureMarkModalOpen: (open: boolean) => void;
    setSeizureMarkModalEntityId: (id: string | null) => void;
    setSeizureMarkModalEntityKind: Dispatch<SetStateAction<'property' | 'movable'>>;
    setSeizureMarkLetterNumberDraft: Dispatch<SetStateAction<string>>;
    setSeizureMarkDateDraft: Dispatch<SetStateAction<string>>;
    setSeizureMarkEntityDraft: Dispatch<SetStateAction<string>>;
    publicationModalEntityId: string | null;
    publicationModalEntityKind: 'property' | 'movable';
    publicationNewspaperNameDraft: string;
    publicationDateYmdDraft: string;
    setPublicationModalOpen: (open: boolean) => void;
    setPublicationModalEntityId: (id: string | null) => void;
    setPublicationModalEntityKind: Dispatch<SetStateAction<'property' | 'movable'>>;
    setPublicationNewspaperNameDraft: Dispatch<SetStateAction<string>>;
    setPublicationDateYmdDraft: Dispatch<SetStateAction<string>>;
    seizedPropertyAuctionResultPropertyId: string | null;
    seizedPropertyAuctionResultEntityKind: 'property' | 'movable';
    seizedPropertyAuctionResultOutcome: string;
    seizedPropertyAuctionResultBuyerNameDraft: string;
    seizedPropertyAuctionResultAmountDraft: string;
    seizedPropertyAuctionDepositAmountDraft: string;
    setSeizedPropertyAuctionResultModalOpen: (open: boolean) => void;
    setSeizedPropertyAuctionResultPropertyId: (id: string | null) => void;
    setSeizedPropertyAuctionResultEntityKind: Dispatch<SetStateAction<'property' | 'movable'>>;
    setSeizedPropertyAuctionResultOutcome: Dispatch<SetStateAction<string>>;
    setSeizedPropertyAuctionResultBuyerNameDraft: Dispatch<SetStateAction<string>>;
    setSeizedPropertyAuctionResultAmountDraft: Dispatch<SetStateAction<string>>;
    setSeizedPropertyAuctionDepositAmountDraft: Dispatch<SetStateAction<string>>;
    seizedPropertyStepDecisionId: string | null;
    seizedPropertyStepEntityKind: 'property' | 'movable';
    seizedPropertyStepPropertyId: string | null;
    seizedPropertyStepKind: string;
    seizedPropertyExpertsNamesDraft: string;
    seizedPropertyExpertReportDateDraft: string;
    seizedPropertyExpertPriceDraft: string;
    seizedPropertyAuctionDateDraft: string;
    seizedPropertyBuyerNameDraft: string;
    seizedPropertyAwardAmountDraft: string;
    seizedPropertyStepNotesDraft: string;
    setSeizedPropertyStepModalOpen: (open: boolean) => void;
    setSeizedPropertyStepDecisionId: (id: string | null) => void;
    setSeizedPropertyStepPropertyId: (id: string | null) => void;
    setSeizedPropertyStepEntityKind: Dispatch<SetStateAction<'property' | 'movable'>>;
    setSeizedPropertyStepKind: Dispatch<SetStateAction<string>>;
    setSeizedPropertyExpertsNamesDraft: Dispatch<SetStateAction<string>>;
    setSeizedPropertyExpertReportDateDraft: Dispatch<SetStateAction<string>>;
    setSeizedPropertyExpertPriceDraft: Dispatch<SetStateAction<string>>;
    setSeizedPropertyAuctionDateDraft: Dispatch<SetStateAction<string>>;
    setSeizedPropertyBuyerNameDraft: Dispatch<SetStateAction<string>>;
    setSeizedPropertyAwardAmountDraft: Dispatch<SetStateAction<string>>;
    setSeizedPropertyStepNotesDraft: Dispatch<SetStateAction<string>>;
};
