import React from 'react';
import { BTN_BASE } from './personalCoerciveStyles';
import { PersonalCoerciveFollowUpPortal } from './chrome/PersonalCoerciveFollowUpPortal';
import {
    PersonalCoerciveConfirmPortals,
    PersonalCoerciveOptionalRemainingEntry,
} from './chrome/PersonalCoerciveConfirmPortals';
import type { PersonalCoerciveFollowupPanelProps } from './types';
import { ForcedBringSection } from './sections/ForcedBringSection';
import { InvestigationCourtSection } from './sections/InvestigationCourtSection';
import { TravelBanSection } from './sections/TravelBanSection';
import { DossierPresentationSection } from './sections/DossierPresentationSection';
import { ExecutiveDetentionJudgeSection } from './sections/ExecutiveDetentionJudgeSection';
import { GuarantorFollowupStrip } from './sections/GuarantorFollowupStrip';
import { usePersonalCoercivePanelModel } from './hooks/usePersonalCoercivePanelModel';

export const PersonalCoerciveFollowupPanel: React.FC<PersonalCoerciveFollowupPanelProps> = (props) => {
    const {
        activateDossierAbsentiaPath,
        allDecisionRows,
        arrest,
        arrestSync,
        canActivateDossierAbsentiaPath,
        canSubmitTravelBan,
        coerciveWriteLocked,
        confirmReleaseDetention,
        debtorNotified,
        detentionActive,
        detentionPeriodActivePanel,
        detentionRejectionOpen,
        detentionRejectionReason,
        detentionRejectionSaving,
        detentionUntil,
        dossier,
        dossierAbsentiaPathOpen,
        dossierAwaitingJudge,
        dossierButtonDisabled,
        dossierEffective,
        dossierGoverningRow,
        dossierHandedToJudgeStalled,
        dossierHasExpandablePanel,
        dossierIdle,
        dossierPhaseEffective,
        dossierShowStartPeriod,
        dossierSync,
        exId,
        findGoverningDossierDecisionId,
        findLatestDecisionIdForSubtype,
        findLatestDecisionRowForSubtype,
        findLatestGuarantorDecisionId,
        findLatestGuarantorDecisionRow,
        forcedBringWithdrawBusy,
        forcedBringWithdrawConfirmOpen,
        forcedButtonDisabled,
        forcedButtonLabel,
        forcedByExecutorOrder,
        forcedEffective,
        forcedFlowStep,
        forcedHasExpandablePanel,
        forcedOutcomePick,
        forcedShowStartStrip,
        forcedSync,
        guarantorAwaitingSave,
        guarantorDec,
        guarantorFollowupBlock,
        guardSummonsGate,
        handleApproveExecutiveDetention,
        handleDossierHeaderClick,
        handleExecutorInlineResolved,
        handleForcedBringHeaderClick,
        hasOpenCardForSubtype,
        investigationButtonDisabled,
        investigationButtonLabel,
        investigationCompletionActive,
        investigationFlowStep,
        investigationHasExpandablePanel,
        investigationPostApprovalActive,
        investigationSessionOpen,
        judgeApprovedAwaitingDetentionStart,
        judgeCassationOverturnVisible,
        judgeDecisionIdStored,
        judgeDetailsOpen,
        judgeDetention,
        judgeDetentionStored,
        judgeHasActionablePanel,
        judgeRejectedResubmitVisible,
        judgeSync,
        liftTravelBanEnforcement,
        localDecisionsTick,
        markWarrantIssued,
        notifyDebtorFirstToast,
        optimisticForcedOutcome,
        optimisticPersistPatch,
        optionalRemainingProceduresOpen,
        optionalRemainingProceduresUnlocked,
        outcome,
        recordExecutiveDetentionJudgeOutcome,
        recordForcedOutcome,
        recordInvestigationDebtorAttended,
        recordSecuredBringAfterWarrant,
        relaxedPersonal,
        releaseConfirmBusy,
        releaseConfirmOpen,
        releaseReason,
        releaseReasonOpen,
        renderAppealSyncFollowup,
        renderInlineGate,
        renderJudgeRejectedResubmitBlock,
        renderRejectedExecutorAppealSection,
        renderWaiveInitialAppeal,
        runArrestInvestigationSubmit,
        runDossierPresentationSubmit,
        runForcedBringSubmit,
        runTravelBanSubmit,
        scopedRequestTitle,
        sendingKey,
        setConfirmingKey,
        setDetentionRejectionOpen,
        setDetentionRejectionReason,
        setDetentionRejectionSaving,
        setDossierInlineResolved,
        setForcedBringWithdrawBusy,
        setForcedBringWithdrawConfirmOpen,
        setForcedInlineResolved,
        setForcedOutcomePick,
        setJudgeDetailsOpen,
        setLocalDecisionsTick,
        setOptimisticForcedOutcome,
        setOptimisticPersistPatch,
        setOptionalRemainingProceduresOpen,
        setReleaseConfirmBusy,
        setReleaseConfirmOpen,
        setReleaseReason,
        setReleaseReasonOpen,
        setSendingKey,
        setTravelPanelOpen,
        showDossierPresentationCard,
        showEmbeddedSection,
        showForcedBringInSection,
        showInvestigationBlock,
        showJudgeDetentionCard,
        showOptionalRemainingProceduresEntry,
        showTravelBanInMainFlow,
        showTravelBanSection,
        startDetentionFourMonths,
        submitRequest,
        travel,
        travelActive,
        travelAppealFollowupVisible,
        travelBanEnforced,
        travelBanRequestCycleWithdrawn,
        travelBanWithdrawn,
        travelButtonLabel,
        travelCycleActive,
        travelEnforcedSettled,
        travelLaneSettled,
        travelLiftReady,
        travelPanelOpen,
        travelRejectedAppealOpen,
        travelShowInitialSubmit,
        travelShowLiftAction,
        travelSubmitButtonDisabled,
        travelSync,
        wanted,
        warrantCustodyRecorded,
        withdrawInvestigationCourtPath,
        withdrawTravelBanRequestCycle,
    } = usePersonalCoercivePanelModel(props);

    const {
        executionId,
        decisionsReloadEpoch,
        coerciveUiLocked,
        gracePeriodEndedFlag,
        forcedSummonAllowed,
        forcedSummonLockReason,
        executionData,
        debtorPresentEffective,
        debtRemainingIqd,
        persistExecutionMerge,
        pushTimelineEvent,
        nextTimelineId,
        showToast,
        onOpenDecisions,
        onOpenSummonsCenter,
        onGuarantorRequest,
        onOpenGuarantorDetails,
        kasabCoerciveEmphasis,
        kasabRelaxedGates,
        activeDebtorKey,
        primaryDebtorKey,
        isHistoricalMode,
        hideDossierJudgePresentation,
        hideExecutiveDetentionJudgeCard,
        earnerFinancialPersonalCoerciveActive,
        hideExecutorForcedBringActivation,
        activeDebtorIsEmployee,
        embeddedHiddenPath,
    } = props;

    return (
        <div
            className={`${embeddedHiddenPath ? 'space-y-3' : 'space-y-4'}${isHistoricalMode ? ' pointer-events-none select-none opacity-[0.72]' : ''}`}
        >
            <PersonalCoerciveConfirmPortals
                releaseConfirmOpen={releaseConfirmOpen}
                releaseConfirmBusy={releaseConfirmBusy}
                setReleaseConfirmOpen={setReleaseConfirmOpen}
                releaseReason={releaseReason}
                confirmReleaseDetention={confirmReleaseDetention}
                forcedBringWithdrawConfirmOpen={forcedBringWithdrawConfirmOpen}
                forcedBringWithdrawBusy={forcedBringWithdrawBusy}
                setForcedBringWithdrawConfirmOpen={setForcedBringWithdrawConfirmOpen}
                withdrawInvestigationCourtPath={withdrawInvestigationCourtPath}
            />

            {/* 1 — إحضار جبري */}
            <ForcedBringSection
                allDecisionRows={allDecisionRows}
                coerciveUiLocked={coerciveUiLocked}
                exId={exId}
                executionId={executionId}
                findLatestDecisionIdForSubtype={findLatestDecisionIdForSubtype}
                findLatestDecisionRowForSubtype={findLatestDecisionRowForSubtype}
                forcedButtonDisabled={forcedButtonDisabled}
                forcedButtonLabel={forcedButtonLabel}
                forcedByExecutorOrder={forcedByExecutorOrder}
                forcedEffective={forcedEffective}
                forcedFlowStep={forcedFlowStep}
                forcedHasExpandablePanel={forcedHasExpandablePanel}
                forcedOutcomePick={forcedOutcomePick}
                forcedShowStartStrip={forcedShowStartStrip}
                forcedSummonAllowed={forcedSummonAllowed}
                forcedSummonLockReason={forcedSummonLockReason}
                forcedSync={forcedSync}
                guardSummonsGate={guardSummonsGate}
                handleExecutorInlineResolved={handleExecutorInlineResolved}
                handleForcedBringHeaderClick={handleForcedBringHeaderClick}
                hasOpenCardForSubtype={hasOpenCardForSubtype}
                kasabCoerciveEmphasis={kasabCoerciveEmphasis}
                onOpenSummonsCenter={onOpenSummonsCenter}
                recordForcedOutcome={recordForcedOutcome}
                relaxedPersonal={relaxedPersonal}
                renderAppealSyncFollowup={renderAppealSyncFollowup}
                renderInlineGate={renderInlineGate}
                renderRejectedExecutorAppealSection={renderRejectedExecutorAppealSection}
                runForcedBringSubmit={runForcedBringSubmit}
                sendingKey={sendingKey}
                setForcedOutcomePick={setForcedOutcomePick}
                showForcedBringInSection={showForcedBringInSection}
                showToast={showToast}
            />

            {/* 2 — مفاتحة تحقيق */}
            <InvestigationCourtSection
                allDecisionRows={allDecisionRows}
                arrest={arrest}
                arrestSync={arrestSync}
                coerciveUiLocked={coerciveUiLocked}
                exId={exId}
                executionId={executionId}
                findLatestDecisionIdForSubtype={findLatestDecisionIdForSubtype}
                findLatestDecisionRowForSubtype={findLatestDecisionRowForSubtype}
                guardSummonsGate={guardSummonsGate}
                handleExecutorInlineResolved={handleExecutorInlineResolved}
                investigationButtonDisabled={investigationButtonDisabled}
                investigationButtonLabel={investigationButtonLabel}
                investigationFlowStep={investigationFlowStep}
                investigationHasExpandablePanel={investigationHasExpandablePanel}
                markWarrantIssued={markWarrantIssued}
                recordInvestigationDebtorAttended={recordInvestigationDebtorAttended}
                recordSecuredBringAfterWarrant={recordSecuredBringAfterWarrant}
                relaxedPersonal={relaxedPersonal}
                renderAppealSyncFollowup={renderAppealSyncFollowup}
                renderInlineGate={renderInlineGate}
                renderRejectedExecutorAppealSection={renderRejectedExecutorAppealSection}
                runArrestInvestigationSubmit={runArrestInvestigationSubmit}
                setConfirmingKey={setConfirmingKey}
                showEmbeddedSection={showEmbeddedSection}
                showInvestigationBlock={showInvestigationBlock}
            />

            <PersonalCoerciveOptionalRemainingEntry
                showOptionalRemainingProceduresEntry={showOptionalRemainingProceduresEntry}
                coerciveUiLocked={coerciveUiLocked}
                isHistoricalMode={isHistoricalMode}
                setOptionalRemainingProceduresOpen={setOptionalRemainingProceduresOpen}
            />

            {/* 3 — منع سفر */}
            <TravelBanSection
                allDecisionRows={allDecisionRows}
                canSubmitTravelBan={canSubmitTravelBan}
                coerciveUiLocked={coerciveUiLocked}
                debtRemainingIqd={debtRemainingIqd}
                exId={exId}
                executionId={executionId}
                findLatestDecisionIdForSubtype={findLatestDecisionIdForSubtype}
                findLatestDecisionRowForSubtype={findLatestDecisionRowForSubtype}
                guardSummonsGate={guardSummonsGate}
                handleExecutorInlineResolved={handleExecutorInlineResolved}
                isHistoricalMode={isHistoricalMode}
                liftTravelBanEnforcement={liftTravelBanEnforcement}
                renderAppealSyncFollowup={renderAppealSyncFollowup}
                renderInlineGate={renderInlineGate}
                renderRejectedExecutorAppealSection={renderRejectedExecutorAppealSection}
                scopedRequestTitle={scopedRequestTitle}
                setConfirmingKey={setConfirmingKey}
                setSendingKey={setSendingKey}
                setTravelPanelOpen={setTravelPanelOpen}
                showTravelBanInMainFlow={showTravelBanInMainFlow}
                submitRequest={submitRequest}
                travel={travel}
                travelAppealFollowupVisible={travelAppealFollowupVisible}
                travelBanEnforced={travelBanEnforced}
                travelBanRequestCycleWithdrawn={travelBanRequestCycleWithdrawn}
                travelBanWithdrawn={travelBanWithdrawn}
                travelButtonLabel={travelButtonLabel}
                travelCycleActive={travelCycleActive}
                travelEnforcedSettled={travelEnforcedSettled}
                travelPanelOpen={travelPanelOpen}
                travelShowInitialSubmit={travelShowInitialSubmit}
                travelShowLiftAction={travelShowLiftAction}
                travelSubmitButtonDisabled={travelSubmitButtonDisabled}
                travelSync={travelSync}
                withdrawTravelBanRequestCycle={withdrawTravelBanRequestCycle}
            />

            {/* 4أ — طلب عرض الإضبارة (قرار المنفذ فقط) */}
            <DossierPresentationSection
                activateDossierAbsentiaPath={activateDossierAbsentiaPath}
                allDecisionRows={allDecisionRows}
                canActivateDossierAbsentiaPath={canActivateDossierAbsentiaPath}
                coerciveWriteLocked={coerciveWriteLocked}
                debtorNotified={debtorNotified}
                dossier={dossier}
                dossierAbsentiaPathOpen={dossierAbsentiaPathOpen}
                dossierButtonDisabled={dossierButtonDisabled}
                dossierEffective={dossierEffective}
                dossierGoverningRow={dossierGoverningRow}
                dossierHasExpandablePanel={dossierHasExpandablePanel}
                dossierIdle={dossierIdle}
                dossierSync={dossierSync}
                exId={exId}
                executionId={executionId}
                findGoverningDossierDecisionId={findGoverningDossierDecisionId}
                handleDossierHeaderClick={handleDossierHeaderClick}
                handleExecutorInlineResolved={handleExecutorInlineResolved}
                kasabCoerciveEmphasis={kasabCoerciveEmphasis}
                relaxedPersonal={relaxedPersonal}
                renderAppealSyncFollowup={renderAppealSyncFollowup}
                renderInlineGate={renderInlineGate}
                renderRejectedExecutorAppealSection={renderRejectedExecutorAppealSection}
                runDossierPresentationSubmit={runDossierPresentationSubmit}
                showDossierPresentationCard={showDossierPresentationCard}
                showEmbeddedSection={showEmbeddedSection}
            />

            {/* 4ب — قرار قاضي البداءة */}
            <ExecutiveDetentionJudgeSection
                coerciveWriteLocked={coerciveWriteLocked}
                detentionActive={detentionActive}
                detentionPeriodActivePanel={detentionPeriodActivePanel}
                detentionRejectionOpen={detentionRejectionOpen}
                detentionRejectionReason={detentionRejectionReason}
                detentionRejectionSaving={detentionRejectionSaving}
                detentionUntil={detentionUntil}
                dossierAbsentiaPathOpen={dossierAbsentiaPathOpen}
                dossierAwaitingJudge={dossierAwaitingJudge}
                dossierHandedToJudgeStalled={dossierHandedToJudgeStalled}
                dossierPhaseEffective={dossierPhaseEffective}
                dossierShowStartPeriod={dossierShowStartPeriod}
                dossierSync={dossierSync}
                executionData={executionData}
                handleApproveExecutiveDetention={handleApproveExecutiveDetention}
                judgeDetention={judgeDetention}
                judgeDetentionStored={judgeDetentionStored}
                judgeRejectedResubmitVisible={judgeRejectedResubmitVisible}
                judgeSync={judgeSync}
                recordExecutiveDetentionJudgeOutcome={recordExecutiveDetentionJudgeOutcome}
                releaseConfirmBusy={releaseConfirmBusy}
                releaseReason={releaseReason}
                releaseReasonOpen={releaseReasonOpen}
                renderAppealSyncFollowup={renderAppealSyncFollowup}
                renderJudgeRejectedResubmitBlock={renderJudgeRejectedResubmitBlock}
                setDetentionRejectionOpen={setDetentionRejectionOpen}
                setDetentionRejectionReason={setDetentionRejectionReason}
                setDetentionRejectionSaving={setDetentionRejectionSaving}
                setReleaseConfirmOpen={setReleaseConfirmOpen}
                setReleaseReason={setReleaseReason}
                setReleaseReasonOpen={setReleaseReasonOpen}
                showEmbeddedSection={showEmbeddedSection}
                showJudgeDetentionCard={showJudgeDetentionCard}
                showToast={showToast}
                startDetentionFourMonths={startDetentionFourMonths}
            />

            {/* كفيل ضامن */}
            <GuarantorFollowupStrip
                allDecisionRows={allDecisionRows}
                coerciveUiLocked={coerciveUiLocked}
                exId={exId}
                executionId={executionId}
                findLatestGuarantorDecisionId={findLatestGuarantorDecisionId}
                findLatestGuarantorDecisionRow={findLatestGuarantorDecisionRow}
                guarantorAwaitingSave={guarantorAwaitingSave}
                guarantorDec={guarantorDec}
                guarantorFollowupBlock={guarantorFollowupBlock}
                onGuarantorRequest={onGuarantorRequest}
                onOpenDecisions={onOpenDecisions}
                onOpenGuarantorDetails={onOpenGuarantorDetails}
                renderRejectedExecutorAppealSection={renderRejectedExecutorAppealSection}
            />

        </div>
    );
};

