import type { SmartFileLayoutBuildInput } from './viewProps';
import type { useSmartFileModalFlags } from '../hooks/useSmartFileModalFlags';

type ModalFlags = ReturnType<typeof useSmartFileModalFlags>;

/** Portal + chrome modal visibility flags for layout assembly. */
export function buildSmartFileModalLayoutFlags(flags: ModalFlags): SmartFileLayoutBuildInput['flags'] {
    return {
        showExportMenu: flags.showExportMenu,
        setShowExportMenu: flags.setShowExportMenu,
        isTrashOpen: flags.isTrashOpen,
        setIsTrashOpen: flags.setIsTrashOpen,
        setShowEditInfoModal: flags.setShowEditInfoModal,
        isActionsMenuOpen: flags.isActionsMenuOpen,
        setIsActionsMenuOpen: flags.setIsActionsMenuOpen,
        showEditInfoModal: flags.showEditInfoModal,
        showTaskModal: flags.showTaskModal,
        setShowTaskModal: flags.setShowTaskModal,
        showDocModal: flags.showDocModal,
        setShowDocModal: flags.setShowDocModal,
        showNoteModal: flags.showNoteModal,
        setShowNoteModal: flags.setShowNoteModal,
        showPaymentModal: flags.showPaymentModal,
        setShowPaymentModal: flags.setShowPaymentModal,
        showIncidentalModal: flags.showIncidentalModal,
        setShowIncidentalModal: flags.setShowIncidentalModal,
        showFastTrackModal: flags.showFastTrackModal,
        setShowFastTrackModal: flags.setShowFastTrackModal,
        showAttachmentModal: flags.showAttachmentModal,
        setShowAttachmentModal: flags.setShowAttachmentModal,
        showApptModal: flags.showApptModal,
        setShowApptModal: flags.setShowApptModal,
        showPauseModal: flags.showPauseModal,
        setShowPauseModal: flags.setShowPauseModal,
        showInterruptionModal: flags.showInterruptionModal,
        setShowInterruptionModal: flags.setShowInterruptionModal,
        showResumeInterruptionModal: flags.showResumeInterruptionModal,
        setShowResumeInterruptionModal: flags.setShowResumeInterruptionModal,
        showAbandonmentRenewalModal: flags.showAbandonmentRenewalModal,
        setShowAbandonmentRenewalModal: flags.setShowAbandonmentRenewalModal,
        showPauseResumeModal: flags.showPauseResumeModal,
        setShowPauseResumeModal: flags.setShowPauseResumeModal,
        showInterlocutoryModal: flags.showInterlocutoryModal,
        setShowInterlocutoryModal: flags.setShowInterlocutoryModal,
        showObjectionRegistrationModal: flags.showObjectionRegistrationModal,
        setShowObjectionRegistrationModal: flags.setShowObjectionRegistrationModal,
        showObjectionJudgmentModal: flags.showObjectionJudgmentModal,
        setShowObjectionJudgmentModal: flags.setShowObjectionJudgmentModal,
        showAbsentJudgmentNotificationModal: flags.showAbsentJudgmentNotificationModal,
        setShowAbsentJudgmentNotificationModal: flags.setShowAbsentJudgmentNotificationModal,
        showOpponentAbsentObjectionModal: flags.showOpponentAbsentObjectionModal,
        setShowOpponentAbsentObjectionModal: flags.setShowOpponentAbsentObjectionModal,
        showJudgmentModal: flags.showJudgmentModal,
        setShowJudgmentModal: flags.setShowJudgmentModal,
        showAppealModal: flags.showAppealModal,
        setShowAppealModal: flags.setShowAppealModal,
        showAppealTransitionModal: flags.showAppealTransitionModal,
        setShowAppealTransitionModal: flags.setShowAppealTransitionModal,
        showCrossAppealModal: flags.showCrossAppealModal,
        setShowCrossAppealModal: flags.setShowCrossAppealModal,
        showProvisionalOrderModal: flags.showProvisionalOrderModal,
        setShowProvisionalOrderModal: flags.setShowProvisionalOrderModal,
        showNotificationModal: flags.showNotificationModal,
        setShowNotificationModal: flags.setShowNotificationModal,
        showExtraordinaryAppealModal: flags.showExtraordinaryAppealModal,
        setShowExtraordinaryAppealModal: flags.setShowExtraordinaryAppealModal,
        showMaterialErrorModal: flags.showMaterialErrorModal,
        setShowMaterialErrorModal: flags.setShowMaterialErrorModal,
        showJudgeRecusalModal: flags.showJudgeRecusalModal,
        setShowJudgeRecusalModal: flags.setShowJudgeRecusalModal,
        showTransferJurisdictionModal: flags.showTransferJurisdictionModal,
        setShowTransferJurisdictionModal: flags.setShowTransferJurisdictionModal,
        showCaseConsolidationModal: flags.showCaseConsolidationModal,
        setShowCaseConsolidationModal: flags.setShowCaseConsolidationModal,
        showCaseLinkModal: flags.showCaseLinkModal,
        setShowCaseLinkModal: flags.setShowCaseLinkModal,
        showCorrespondenceModal: flags.showCorrespondenceModal,
        setShowCorrespondenceModal: flags.setShowCorrespondenceModal,
        editingEvent: flags.editingEvent,
        setEditingEvent: flags.setEditingEvent,
        editingTask: flags.editingTask,
        setEditingTask: flags.setEditingTask,
        editingIncidental: flags.editingIncidental,
        setEditingIncidental: flags.setEditingIncidental,
        editingFastTrack: flags.editingFastTrack,
        setEditingFastTrack: flags.setEditingFastTrack,
        editingAttachment: flags.editingAttachment,
        setEditingAttachment: flags.setEditingAttachment,
        tempJudgmentData: flags.tempJudgmentData,
        setTempJudgmentData: flags.setTempJudgmentData,
        appealOutcomeTask: flags.appealOutcomeTask,
        setAppealOutcomeTask: flags.setAppealOutcomeTask,
    };
}
