import { LAWSUIT_VAULT_TEST_IDS } from './lawsuitVaultTestIds';

/** Stable selectors for E2E / integration (no visual impact). */
export const CIVIL_LAWSUIT_TEST_IDS = {
    ...LAWSUIT_VAULT_TEST_IDS,
    dossier: 'smart-file-dossier',
    dossierBack: 'smart-file-back',
    dossierExit: 'smart-file-exit',
    caseFlowOpen: 'smart-file-case-flow-open',
    caseFlowPanel: 'smart-file-case-flow-panel',
    caseFlowConfirmDialog: 'smart-file-case-flow-confirm',
    legalActionsSheet: 'smart-file-legal-actions-sheet',
    legalActionsSwipeHandle: 'smart-file-legal-actions-swipe-handle',
    newCaseSave: 'lawyer-new-case-save',
    newCaseMarkClient: 'lawyer-new-case-mark-client',
    taskAdd: 'smart-file-task-add',
    taskModal: 'smart-file-task-modal',
    taskTitle: 'smart-file-task-title',
    taskSubmit: 'smart-file-task-submit',
    taskRow: (id: string) => `smart-file-task-row-${id}`,
    sessionRecordAdd: 'smart-file-session-record-add',
    sessionRecordOpen: 'smart-file-session-record-open',
    civilLawReferenceOpen: 'smart-file-civil-law-reference-open',
    civilLawReferencePanel: 'smart-file-civil-law-reference-panel',
    civilLawReferenceClose: 'smart-file-civil-law-reference-close',
    sessionRecordPanel: 'smart-file-session-record-panel',
    sessionRecordClose: 'smart-file-session-record-close',
    sessionRecordDate: 'smart-file-session-record-date',
    sessionRecordNumber: 'smart-file-session-record-number',
    sessionHearingsRegister: 'smart-file-session-hearings-register',
    sessionHearingRow: (id: string) => `smart-file-session-hearing-row-${id}`,
    sessionLeaveRegister: 'smart-file-session-leave-register',
    sessionOpenRegister: 'smart-file-session-open-register',
    sessionRecordProceedings: 'smart-file-session-record-proceedings',
    sessionRecordJudgeDecisions: 'smart-file-session-record-judge-decisions',
    sessionRecordJudgeTemplateInput: 'smart-file-session-record-judge-template-input',
    sessionRecordJudgeTemplateAdd: 'smart-file-session-record-judge-template-add',
    sessionRecordJudgeTemplateChip: (label: string) =>
        `smart-file-session-record-judge-template-${label.replace(/\s+/g, '-').slice(0, 40)}`,
    sessionRecordJudgeTemplateRemove: (label: string) =>
        `smart-file-session-record-judge-template-remove-${label.replace(/\s+/g, '-').slice(0, 40)}`,
    sessionRecordNextDate: 'smart-file-session-record-next-date',
    sessionRecordManualToggle: 'smart-file-session-record-manual-toggle',
    sessionRecordNextManualToggle: 'smart-file-session-record-next-manual-toggle',
    sessionRecordRequestAddFastTrack: 'smart-file-session-record-add-fast-track',
    requestAddAttachment: 'smart-file-request-add-attachment',
    requestRow: (id: string) => `smart-file-request-row-${id}`,
    sessionRecordRequestRow: (id: string) => `smart-file-session-record-request-row-${id}`,
    requestsHubAdd: 'smart-file-requests-hub-add',
    requestsHubRow: (id: string) => `smart-file-requests-hub-row-${id}`,
    requestsHub: 'smart-file-requests-hub',
    timelineSearch: 'smart-file-timeline-search',
    timelineCategoryChip: (id: string) => `smart-file-timeline-category-${id}`,
    noteTagManualInput: 'smart-file-note-tag-manual-input',
    noteTagManualAdd: 'smart-file-note-tag-manual-add',
    noteTagTemplateChip: (label: string) =>
        `smart-file-note-tag-template-${label.replace(/^#+/, '').replace(/\s+/g, '-').slice(0, 40)}`,
    noteTagTemplateRemove: (label: string) =>
        `smart-file-note-tag-template-remove-${label.replace(/^#+/, '').replace(/\s+/g, '-').slice(0, 40)}`,
    appointmentTagManualInput: 'smart-file-appointment-tag-manual-input',
    appointmentTagManualAdd: 'smart-file-appointment-tag-manual-add',
    appointmentTagTemplateChip: (label: string) =>
        `smart-file-appointment-tag-template-${label.replace(/^#+/, '').replace(/\s+/g, '-').slice(0, 40)}`,
    appointmentTagTemplateRemove: (label: string) =>
        `smart-file-appointment-tag-template-remove-${label.replace(/^#+/, '').replace(/\s+/g, '-').slice(0, 40)}`,
    quickActionAppointment: 'smart-file-quick-appointment',
    quickActionNote: 'smart-file-quick-note',
    quickActionDocument: 'smart-file-quick-document',
    quickActionLegal: 'smart-file-quick-legal',
    appointmentModal: 'smart-file-appointment-modal',
    noteModal: 'smart-file-note-modal',
    documentModal: 'smart-file-document-modal',
    requestsEmpty: 'smart-file-requests-empty',
    requestsTemplateInput: 'smart-file-requests-template-input',
    requestsTemplateAdd: 'smart-file-requests-template-add',
    requestsTemplateChip: (label: string) =>
        `smart-file-requests-template-${label.replace(/\s+/g, '-').slice(0, 40)}`,
    requestsTemplateRemove: (label: string) =>
        `smart-file-requests-template-remove-${label.replace(/\s+/g, '-').slice(0, 40)}`,
    requestsQuickType: (type: string) =>
        `smart-file-requests-quick-${type.replace(/\s+/g, '-').slice(0, 40)}`,
    fastTrackRequestType: 'smart-file-fast-track-request-type',
    fastTrackSubject: 'smart-file-fast-track-subject',
    fastTrackSubmissionDate: 'smart-file-fast-track-submission-date',
    fastTrackSubmit: 'smart-file-fast-track-submit',
    fastTrackStatus: (key: string) => `smart-file-fast-track-status-${key}`,
    judgmentModal: 'smart-judgment-modal',
    judgmentFormHadari: 'smart-judgment-form-hadari',
    judgmentFormGhiabi: 'smart-judgment-form-ghiabi',
    judgmentFormDeemedHadari: 'smart-judgment-form-deemed-hadari',
    judgmentPartyFormList: 'smart-judgment-party-form-list',
    judgmentFormHadariParty: (partyId: string | number) =>
        `smart-judgment-form-hadari-${partyId}`,
    judgmentFormGhiabiParty: (partyId: string | number) =>
        `smart-judgment-form-ghiabi-${partyId}`,
    judgmentFormDeemedHadariParty: (partyId: string | number) =>
        `smart-judgment-form-deemed-hadari-${partyId}`,
    judgmentOperativeBoundParty: (partyId: string | number) =>
        `smart-judgment-operative-bound-${partyId}`,
    judgmentOperativeReleasedParty: (partyId: string | number) =>
        `smart-judgment-operative-released-${partyId}`,
    judgmentDerivedOutcome: 'smart-judgment-derived-outcome',
    judgmentBoundMerit: 'smart-judgment-bound-merit',
    judgmentBoundMeritFull: 'smart-judgment-bound-merit-full',
    judgmentBoundMeritPartial: 'smart-judgment-bound-merit-partial',
    judgmentIntegritySeverable: 'smart-judgment-integrity-severable',
    judgmentIntegrityIndivisible: 'smart-judgment-integrity-indivisible',
    judgmentOutcomePicker: 'smart-judgment-outcome-picker',
    judgmentDate: 'smart-judgment-date',
    judgmentAdjournPleading: 'smart-judgment-adjourn-pleading',
    judgmentEnterDecision: 'smart-judgment-enter-decision',
    pleadingClosePrimary: 'smart-pleading-close-primary',
    art172Stay: 'smart-art172-stay',
    art172StayHint: 'smart-art172-stay-hint',
    art172Resume: 'smart-art172-resume',
    art172StayBadge: 'smart-art172-stay-badge',
    objectionAppealGuidance: 'smart-objection-appeal-guidance',
    remainingOpponentChallenge: 'smart-remaining-opponent-challenge',
    postHopChallengeChrome: 'smart-post-hop-challenge-chrome',
    namedChallengeAction: (challengerId: string | number) =>
        `smart-named-challenge-${challengerId}`,
    postJudgmentPartialTracks: 'smart-post-judgment-partial-tracks',
    postJudgmentOpponentChallenge: 'smart-post-judgment-opponent-challenge',
    crossAppealFooter: 'smart-cross-appeal-footer',
    joinCoObjector: 'smart-join-co-objector',
    joinCoObjectorPicker: 'smart-join-co-objector-picker',
    joinCoObjectorOption: (partyId: string | number) => `smart-join-co-objector-option-${partyId}`,
    unifiedObjectionBanner: 'smart-unified-objection-banner',
    absentJudgmentNotice: 'smart-absent-judgment-notice',
    absentJudgmentNoticePicker: 'smart-absent-judgment-notice-picker',
    absentJudgmentNoticeOption: (partyId: string | number) => `smart-absent-judgment-notice-option-${partyId}`,
    art172Coverage: 'smart-art172-coverage',
    art191ExecutionStay: 'smart-art191-execution-stay',
    partyChallengeLanes: 'smart-party-challenge-lanes',
    partyChallengeLane: (partyId: string | number) => `smart-party-challenge-lane-${partyId}`,
    art210Extension: 'smart-art210-extension',
    independentChallengeSpawn: 'smart-independent-challenge-spawn',
    judgmentCassationGroundsCommon: 'smart-judgment-cassation-grounds-common',
    judgmentCassationGroundsPersonal: 'smart-judgment-cassation-grounds-personal',
} as const;
