/** Stable selectors for E2E / integration (no visual impact). */
export const CIVIL_LAWSUIT_TEST_IDS = {
    hubLawsuits: 'hub-archive-lawsuit',
    workspace: 'lawsuits-workspace',
    tabCivil: 'lawsuits-tab-civil',
    tabUrgent: 'lawsuits-tab-urgent',
    addLawsuit: 'lawsuits-add-new',
    dossier: 'smart-file-dossier',
    dossierBack: 'smart-file-back',
    newCaseSave: 'lawyer-new-case-save',
    taskAdd: 'smart-file-task-add',
    taskModal: 'smart-file-task-modal',
    taskTitle: 'smart-file-task-title',
    taskSubmit: 'smart-file-task-submit',
    taskRow: (id: string) => `smart-file-task-row-${id}`,
    sessionRecordAdd: 'smart-file-session-record-add',
    sessionRecordOpen: 'smart-file-session-record-open',
    civilLawReferenceOpen: 'smart-file-civil-law-reference-open',
    civilLawReferencePanel: 'smart-file-civil-law-reference-panel',
    civilLawReferenceClose: 'smart-file-civil-law-reference-close',
    sessionRecordPanel: 'smart-file-session-record-panel',
    sessionRecordClose: 'smart-file-session-record-close',
    sessionRecordDate: 'smart-file-session-record-date',
    sessionRecordNumber: 'smart-file-session-record-number',
    sessionRecordProceedings: 'smart-file-session-record-proceedings',
    sessionRecordJudgeDecisions: 'smart-file-session-record-judge-decisions',
    sessionRecordJudgeTemplateInput: 'smart-file-session-record-judge-template-input',
    sessionRecordJudgeTemplateAdd: 'smart-file-session-record-judge-template-add',
    sessionRecordJudgeTemplateChip: (label: string) =>
        `smart-file-session-record-judge-template-${label.replace(/\s+/g, '-').slice(0, 40)}`,
    sessionRecordJudgeTemplateRemove: (label: string) =>
        `smart-file-session-record-judge-template-remove-${label.replace(/\s+/g, '-').slice(0, 40)}`,
    sessionRecordNextDate: 'smart-file-session-record-next-date',
    sessionRecordManualToggle: 'smart-file-session-record-manual-toggle',
    sessionRecordNextManualToggle: 'smart-file-session-record-next-manual-toggle',
    sessionRecordRequestAddFastTrack: 'smart-file-session-record-add-fast-track',
    requestAddAttachment: 'smart-file-request-add-attachment',
    requestRow: (id: string) => `smart-file-request-row-${id}`,
    sessionRecordRequestRow: (id: string) => `smart-file-session-record-request-row-${id}`,
    requestsHubAdd: 'smart-file-requests-hub-add',
    requestsHubRow: (id: string) => `smart-file-requests-hub-row-${id}`,
    requestsHub: 'smart-file-requests-hub',
    timelineSearch: 'smart-file-timeline-search',
    timelineCategoryChip: (id: string) => `smart-file-timeline-category-${id}`,
    noteTagManualInput: 'smart-file-note-tag-manual-input',
    noteTagManualAdd: 'smart-file-note-tag-manual-add',
    noteTagTemplateChip: (label: string) =>
        `smart-file-note-tag-template-${label.replace(/^#+/, '').replace(/\s+/g, '-').slice(0, 40)}`,
    noteTagTemplateRemove: (label: string) =>
        `smart-file-note-tag-template-remove-${label.replace(/^#+/, '').replace(/\s+/g, '-').slice(0, 40)}`,
    appointmentTagManualInput: 'smart-file-appointment-tag-manual-input',
    appointmentTagManualAdd: 'smart-file-appointment-tag-manual-add',
    appointmentTagTemplateChip: (label: string) =>
        `smart-file-appointment-tag-template-${label.replace(/^#+/, '').replace(/\s+/g, '-').slice(0, 40)}`,
    appointmentTagTemplateRemove: (label: string) =>
        `smart-file-appointment-tag-template-remove-${label.replace(/^#+/, '').replace(/\s+/g, '-').slice(0, 40)}`,
    quickActionAppointment: 'smart-file-quick-appointment',
    quickActionNote: 'smart-file-quick-note',
    quickActionDocument: 'smart-file-quick-document',
    quickActionLegal: 'smart-file-quick-legal',
    appointmentModal: 'smart-file-appointment-modal',
    noteModal: 'smart-file-note-modal',
    documentModal: 'smart-file-document-modal',
    requestsEmpty: 'smart-file-requests-empty',
    requestsTemplateInput: 'smart-file-requests-template-input',
    requestsTemplateAdd: 'smart-file-requests-template-add',
    requestsTemplateChip: (label: string) =>
        `smart-file-requests-template-${label.replace(/\s+/g, '-').slice(0, 40)}`,
    requestsTemplateRemove: (label: string) =>
        `smart-file-requests-template-remove-${label.replace(/\s+/g, '-').slice(0, 40)}`,
    requestsQuickType: (type: string) =>
        `smart-file-requests-quick-${type.replace(/\s+/g, '-').slice(0, 40)}`,
    lawsuitFile: (id: string | number) => `lawsuit-file-${id}`,
    fastTrackRequestType: 'smart-file-fast-track-request-type',
    fastTrackSubject: 'smart-file-fast-track-subject',
    fastTrackSubmissionDate: 'smart-file-fast-track-submission-date',
    fastTrackSubmit: 'smart-file-fast-track-submit',
    fastTrackStatus: (key: string) => `smart-file-fast-track-status-${key}`,
} as const;
