/** معرّفات مخزن الدعاوى فقط — بلا SmartFile حتى لا تنتفخ شبكة البطاقات. */
export const LAWSUIT_VAULT_TEST_IDS = {
    hubLawsuits: 'hub-archive-lawsuit',
    workspace: 'lawsuits-workspace',
    tabCivil: 'lawsuits-tab-civil',
    tabUrgent: 'lawsuits-tab-urgent',
    addLawsuit: 'lawsuits-add-new',
    jurisdictionPicker: 'lawsuits-jurisdiction-picker',
    lawsuitFilePrefix: 'lawsuit-file',
    lawsuitFile: (id: string | number) => `lawsuit-file-${id}`,
    lawsuitFileArchive: (id: string | number) => `lawsuit-file-${id}-archive`,
    lawsuitFileTrash: (id: string | number) => `lawsuit-file-${id}-trash`,
    lawsuitFileRestore: (id: string | number) => `lawsuit-file-${id}-restore`,
    lawsuitFileRestoreArchive: (id: string | number) => `lawsuit-file-${id}-restore-archive`,
    lawsuitFileSelect: (id: string | number) => `lawsuit-file-${id}-select`,
    trashSelectAll: 'lawsuits-trash-select-all',
    trashPermanentDelete: 'lawsuits-trash-permanent-delete',
    trashConfirmDialog: 'lawsuit-trash-confirm-dialog',
    trashConfirmSubmit: 'lawsuit-trash-confirm-submit',
    permanentDeleteDialog: 'lawsuit-permanent-delete-dialog',
    permanentDeleteConfirm: 'lawsuit-permanent-delete-confirm',
    criminalDeleteDialog: 'lawsuit-criminal-delete-dialog',
    criminalDeleteConfirm: 'lawsuit-criminal-delete-confirm',
} as const;
