import type { Dispatch, SetStateAction } from 'react';
import type { CaseStage, IncidentalCase, Task, TimelineEvent } from '../../LawyerShared';
import type { SmartFileChromeProps } from '../layout/SmartFileChrome';
import type { SmartFileMainPanelProps } from '../layout/SmartFileMainPanel';
import type { SmartFileModalsPortalProps } from '../layout/SmartFileModalsPortal';
import type { SmartFileParentData } from './parentDataInit';
import type { ConsolidationCandidate } from './caseConsolidationLinking';
import type { JudgmentPayload } from './judgmentTypes';

/** Flat scope from SmartFileModalContent — passed once into layout builders. */
export type SmartFileLayoutBuildInput = {
    onClose: () => void;
    file: Record<string, unknown>;
    status: string;
    isViewingArchived: boolean;
    isPaused: boolean;
    pauseReason: string;
    isInterrupted: boolean;
    interruptionData: Record<string, unknown> | null;
    linkedCaseNo: string;
    parentData: SmartFileParentData;
    displayStage: CaseStage;
    displayTimeline: TimelineEvent[];
    currentStage: CaseStage;
    stages: CaseStage[];
    activeStageIndex: number;
    viewingStageIndex: number;
    isPleadingsClosed: boolean | undefined;
    lastJudgmentType: string | undefined;
    isEditingStageName: boolean;
    setIsEditingStageName: (v: boolean) => void;
    tempStageName: string;
    setTempStageName: (v: string) => void;
    onSaveStageName: SmartFileChromeProps['onSaveStageName'];
    onShare: () => void;
    onStageSelect: (stageId: string) => void;
    onTouchStart: SmartFileMainPanelProps['onTouchStart'];
    onTouchMove: SmartFileMainPanelProps['onTouchMove'];
    onTouchEnd: SmartFileMainPanelProps['onTouchEnd'];
    stepperStages: unknown[];
    currentStageId: string;
    deletedEvents: TimelineEvent[];
    handlers: Record<string, (...args: unknown[]) => void>;
    onOpenLinkedFile?: (fileId: number) => void;
    lawsuitFiles?: import('../../LawyerShared').FileData[];
    consolidationCurrentFileId: number;
    consolidationCurrentCaseNo: string;
    consolidationCurrentClientName?: string;
    consolidationCurrentCourt?: string;
    consolidationCurrentStageLabel?: string;
    consolidationCandidates: ConsolidationCandidate[];
    onConsolidationCreateNew?: (data: { consolidationDate: string; notes?: string }) => void;
    onConsolidationMergeExisting?: (data: {
        secondaryFileId: number;
        consolidationDate: string;
        notes?: string;
    }) => void;
    onConsolidationExternalRef?: (data: {
        peerCaseNo: string;
        consolidationDate: string;
        notes?: string;
    }) => void;
    caseLinkCurrentFileId: number;
    caseLinkCurrentCaseNo: string;
    caseLinkCandidates: ConsolidationCandidate[];
    onCaseLinkExisting?: (data: {
        secondaryFileId: number;
        linkDate: string;
        reason?: string;
    }) => void;
    onCaseLinkExternal?: (data: { peerCaseNo: string; linkDate: string; reason?: string }) => void;
    handleCorrespondenceResponse?: SmartFileMainPanelProps['handleCorrespondenceResponse'];
    handleResumeAbandonment: SmartFileMainPanelProps['handleResumeAbandonment'];
    handleResume: SmartFileMainPanelProps['handleResume'];
    handleInterruptionToggle: SmartFileMainPanelProps['handleInterruptionToggle'];
    handleOpenPauseModal: () => void;
    handleOpenPauseResume: () => void;
    handleAbandonment: SmartFileMainPanelProps['handleAbandonment'];
    handleRegisterPetitionVoid: () => void;
    handlePetitionVoidAppeal: SmartFileMainPanelProps['handlePetitionVoidAppeal'];
    handlePetitionVoidOutcome: SmartFileMainPanelProps['handlePetitionVoidOutcome'];
    handlePetitionVoidWaiver: () => void;
    handleToggleNotification: SmartFileMainPanelProps['handleToggleNotification'];
    handleCassationDecision: SmartFileMainPanelProps['handleCassationDecision'];
    handleClosePleadings: SmartFileMainPanelProps['handleClosePleadings'];
    handleReopenPleadings: SmartFileMainPanelProps['handleReopenPleadings'];
    handleOpenDefendantCassationAppeal: () => void;
    handleDefaultObjection: SmartFileMainPanelProps['handleDefaultObjection'];
    handleWaiveObjection: SmartFileMainPanelProps['handleWaiveObjection'];
    handleOpponentAppealWaived: SmartFileMainPanelProps['handleOpponentAppealWaived'];
    handleOtherAppeals: SmartFileMainPanelProps['handleOtherAppeals'];
    handleOpenAbsentJudgmentNotification: () => void;
    handleOpenOpponentAbsentObjection: () => void;
    handleExportPDF: SmartFileMainPanelProps['handleExportPDF'];
    handleResolveIncidentalCase: SmartFileMainPanelProps['handleResolveIncidentalCase'];
    handleUpdateIncidentalEntryDecision?: SmartFileMainPanelProps['handleUpdateIncidentalEntryDecision'];
    handleQuickAction: SmartFileMainPanelProps['handleQuickAction'];
    handleToggleTask: SmartFileMainPanelProps['handleToggleTask'];
    handleAppealBriefFile?: SmartFileMainPanelProps['handleAppealBriefFile'];
    handleAppealBriefOutcome?: SmartFileMainPanelProps['handleAppealBriefOutcome'];
    handleDeleteEvent: SmartFileMainPanelProps['handleDeleteEvent'];
    handleEditEvent: SmartFileMainPanelProps['handleEditEvent'];
    handleAddAction: SmartFileMainPanelProps['handleAddAction'];
    handleSaveFastTrack: SmartFileMainPanelProps['handleSaveFastTrack'];
    handleCancelCrossAppeal: SmartFileMainPanelProps['handleCancelCrossAppeal'];
    handleAddCrossAppeal: SmartFileMainPanelProps['handleAddCrossAppeal'];
    setParentData: Dispatch<SetStateAction<SmartFileParentData>>;
    flags: {
        showExportMenu: boolean;
        setShowExportMenu: (v: boolean) => void;
        isTrashOpen: boolean;
        setIsTrashOpen: (v: boolean) => void;
        setShowEditInfoModal: (v: boolean) => void;
        isActionsMenuOpen: boolean;
        setIsActionsMenuOpen: (v: boolean) => void;
        showEditInfoModal: boolean;
        showTaskModal: boolean;
        setShowTaskModal: (v: boolean) => void;
        showDocModal: boolean;
        setShowDocModal: (v: boolean) => void;
        showNoteModal: boolean;
        setShowNoteModal: (v: boolean) => void;
        showPaymentModal: boolean;
        setShowPaymentModal: (v: boolean) => void;
        showIncidentalModal: boolean;
        setShowIncidentalModal: (v: boolean) => void;
        showFastTrackModal: boolean;
        setShowFastTrackModal: (v: boolean) => void;
        showAttachmentModal: boolean;
        setShowAttachmentModal: (v: boolean) => void;
        showApptModal: boolean;
        setShowApptModal: (v: boolean) => void;
        showPauseModal: boolean;
        setShowPauseModal: (v: boolean) => void;
        showInterruptionModal: boolean;
        setShowInterruptionModal: (v: boolean) => void;
        showResumeInterruptionModal: boolean;
        setShowResumeInterruptionModal: (v: boolean) => void;
        showAbandonmentRenewalModal: boolean;
        setShowAbandonmentRenewalModal: (v: boolean) => void;
        showPauseResumeModal: boolean;
        setShowPauseResumeModal: (v: boolean) => void;
        showInterlocutoryModal: boolean;
        setShowInterlocutoryModal: (v: boolean) => void;
        showObjectionRegistrationModal: boolean;
        setShowObjectionRegistrationModal: (v: boolean) => void;
        showAbsentJudgmentNotificationModal: boolean;
        setShowAbsentJudgmentNotificationModal: (v: boolean) => void;
        showOpponentAbsentObjectionModal: boolean;
        setShowOpponentAbsentObjectionModal: (v: boolean) => void;
        showJudgmentModal: boolean;
        setShowJudgmentModal: (v: boolean) => void;
        showAppealModal: boolean;
        setShowAppealModal: (v: boolean) => void;
        showAppealTransitionModal: boolean;
        setShowAppealTransitionModal: (v: boolean) => void;
        showCrossAppealModal: boolean;
        setShowCrossAppealModal: (v: boolean) => void;
        showProvisionalOrderModal: boolean;
        setShowProvisionalOrderModal: (v: boolean) => void;
        showNotificationModal: boolean;
        setShowNotificationModal: (v: boolean) => void;
        showExtraordinaryAppealModal: boolean | string;
        setShowExtraordinaryAppealModal: (v: boolean | string) => void;
        showMaterialErrorModal: string | null;
        setShowMaterialErrorModal: (v: string | null) => void;
        showJudgeRecusalModal: boolean;
        setShowJudgeRecusalModal: (v: boolean) => void;
        showTransferJurisdictionModal: boolean;
        setShowTransferJurisdictionModal: (v: boolean) => void;
        showCaseConsolidationModal: boolean;
        setShowCaseConsolidationModal: (v: boolean) => void;
        showCaseLinkModal: boolean;
        setShowCaseLinkModal: (v: boolean) => void;
        showCorrespondenceModal: boolean;
        setShowCorrespondenceModal: (v: boolean) => void;
        editingEvent: TimelineEvent | null;
        setEditingEvent: (e: TimelineEvent | null) => void;
        editingTask: Task | null;
        setEditingTask: (t: Task | null) => void;
        editingIncidental: IncidentalCase | null;
        setEditingIncidental: (c: IncidentalCase | null) => void;
        editingFastTrack: Record<string, unknown> | null;
        setEditingFastTrack: (v: Record<string, unknown> | null) => void;
        editingAttachment: Record<string, unknown> | null;
        setEditingAttachment: (v: Record<string, unknown> | null) => void;
        tempJudgmentData: JudgmentPayload | null;
        setTempJudgmentData: (v: JudgmentPayload | null) => void;
        appealOutcomeTask: Task | null;
        setAppealOutcomeTask: (t: Task | null) => void;
    };
};

export type SmartFileLayoutProps = {
    chrome: SmartFileChromeProps;
    mainPanel: SmartFileMainPanelProps;
    modalsPortal: SmartFileModalsPortalProps;
};
