import type { Dispatch, ReactNode, SetStateAction } from 'react';
import type { ChangeEvent } from 'react';
import type { MaritalFurnitureItem } from '@/app/types/maritalFurniture';
import type { VisitationScheduleConfig } from '@/app/types/visitationSchedule';
import type { SpecificDeliveryItem } from '@/app/utils/specificDeliveryItemsUtils';
import type { AlimonyCalculationResult } from '../hooks/useAlimonyCalculator';
import type {
    AbsenteeChecks,
    AdditionalCreditorDraft,
    AdditionalDebtorDraft,
    CreditorDraft,
    DebtorDraft,
    ExecutionTargetOption,
    PartyEntityKind,
} from '../types';
import type { ForeignJudgmentData } from './ForeignJudgmentSection';

type SelectOption = { value: string; label: string };
type AlimonyBeneficiary = 'زوجة فقط' | 'أولاد فقط' | 'زوجة وأولاد';
type AlimonyPastLawSystem = 'قانون الأحوال الشخصية 1959' | 'الفقه الجعفري';

/** حقيبة نموذج الإنشاء — حقول مسمّاة. المصدر: ExecutionCreationView. */
export type ExecutionCreationFormVm = {
    directorate: string;
    setDirectorate: Dispatch<SetStateAction<string>>;
    fileNumber: string;
    setFileNumber: Dispatch<SetStateAction<string>>;
    docType: string;
    docNumber: string;
    setDocNumber: Dispatch<SetStateAction<string>>;
    currentDocTypeLabel: string;
    setDocTypeSheetOpen: Dispatch<SetStateAction<boolean>>;
    visibleClassificationOptions: SelectOption[];
    classification: string;
    handleClassificationChange: (v: string) => void;
    claimTypeOptionsList: SelectOption[];
    currentClaimTypeLabel: string;
    setClaimTypeSheetOpen: Dispatch<SetStateAction<boolean>>;
    effectiveClaimTypes: string[];
    removeActiveClaimType: (value: string) => void;
    claimType: string;
    claimSectionCardClass: string;
    showMultiClaimAggregatePanel: boolean;
    aggregatedClaimTotalDisplay: number;
    hasActiveClaim: (ct: string) => boolean;
    chequeNumber: string;
    setChequeNumber: Dispatch<SetStateAction<string>>;
    shariaDeedNumber: string;
    setShariaDeedNumber: Dispatch<SetStateAction<string>>;
    shariaRegisterNumber: string;
    setShariaRegisterNumber: Dispatch<SetStateAction<string>>;
    shariaIssueDate: string;
    setShariaIssueDate: Dispatch<SetStateAction<string>>;
    shariaIssuingCourt: string;
    setShariaIssuingCourt: Dispatch<SetStateAction<string>>;
    shariaDeedDetails: string;
    setShariaDeedDetails: Dispatch<SetStateAction<string>>;
    formatCurrency: (raw: string) => string;
    handleAmountChange: (e: ChangeEvent<HTMLInputElement>, setter: (val: string) => void) => void;
    totalAmount: string;
    setTotalAmount: Dispatch<SetStateAction<string>>;
    claimAmountsByType: Record<string, string>;
    setClaimAmountsByType: Dispatch<SetStateAction<Record<string, string>>>;
    alimonyBeneficiary: AlimonyBeneficiary;
    setAlimonyBeneficiary: Dispatch<SetStateAction<AlimonyBeneficiary>>;
    alimonyLawsuitDate: string;
    setAlimonyLawsuitDate: Dispatch<SetStateAction<string>>;
    alimonyExecutionDate: string;
    setAlimonyExecutionDate: Dispatch<SetStateAction<string>>;
    alimonyWifeMonthly: string;
    setAlimonyWifeMonthly: Dispatch<SetStateAction<string>>;
    alimonyChildrenMonthly: string;
    setAlimonyChildrenMonthly: Dispatch<SetStateAction<string>>;
    alimonyChildrenCount: string;
    setAlimonyChildrenCount: Dispatch<SetStateAction<string>>;
    calculatedAlimonyNew: AlimonyCalculationResult | null | undefined;
    judgmentDate: string;
    setJudgmentDate: Dispatch<SetStateAction<string>>;
    alimonyIncludesPastCalc: boolean;
    alimonyPastLawSystem: AlimonyPastLawSystem;
    setAlimonyPastLawSystem: Dispatch<SetStateAction<AlimonyPastLawSystem>>;
    alimonyPastStartDate: string;
    setAlimonyPastStartDate: Dispatch<SetStateAction<string>>;
    pastWifeAlimonyAmount: string;
    setPastWifeAlimonyAmount: Dispatch<SetStateAction<string>>;
    dowryReason: 'طلاق' | 'وفاة';
    setDowryReason: Dispatch<SetStateAction<'طلاق' | 'وفاة'>>;
    guardianshipDetails: string;
    setGuardianshipDetails: Dispatch<SetStateAction<string>>;
    evictionPropertyNumber: string;
    setEvictionPropertyNumber: Dispatch<SetStateAction<string>>;
    evictionDistrict: string;
    setEvictionDistrict: Dispatch<SetStateAction<string>>;
    evictionPropertyType: string;
    setEvictionPropertyType: Dispatch<SetStateAction<string>>;
    evictionFullAddress: string;
    setEvictionFullAddress: Dispatch<SetStateAction<string>>;
    evictionPremisesUse: 'commercial' | 'residential';
    setEvictionPremisesUse: Dispatch<SetStateAction<'commercial' | 'residential'>>;
    specificDeliveryItems: SpecificDeliveryItem[];
    setSpecificDeliveryItems: Dispatch<SetStateAction<SpecificDeliveryItem[]>>;
    maritalFurnitureItems: MaritalFurnitureItem[];
    setMaritalFurnitureItems: Dispatch<SetStateAction<MaritalFurnitureItem[]>>;
    dueDate: string;
    setDueDate: Dispatch<SetStateAction<string>>;
    executionTarget: ExecutionTargetOption;
    setExecutionTarget: Dispatch<SetStateAction<ExecutionTargetOption>>;
    isDocumentBlocked: boolean;
    foreignData: ForeignJudgmentData;
    setForeignData: Dispatch<SetStateAction<ForeignJudgmentData>>;
    showLawyerFeesBetweenSections: boolean;
    includeLawyerFees: boolean;
    setIncludeLawyerFees: Dispatch<SetStateAction<boolean>>;
    lawyerFeesAmount: string;
    setLawyerFeesAmount: Dispatch<SetStateAction<string>>;
    showPartiesSection: boolean;
    creditors: CreditorDraft[];
    additionalCreditors: AdditionalCreditorDraft[];
    debtors: DebtorDraft[];
    additionalDebtorsForm: AdditionalDebtorDraft[];
    allowMultipleDebtors: boolean;
    showDebtorSolidarySplit: boolean;
    globalClaimTotalForSplit: number;
    lockedDebtorEntityKind: PartyEntityKind | null;
    debtorManualDebtClaims: Record<string, string>;
    debtorLawyerFeesClaims: Record<string, string>;
    handleDebtorManualDebtChange: (debtorKey: string, raw: string) => void;
    handleDebtorLawyerFeesChange: (debtorKey: string, raw: string) => void;
    addCreditor: () => void;
    removeAdditionalCreditor: (id: string) => void;
    updateAdditionalCreditor: (id: string, field: string, value: string | boolean | number) => void;
    updateCreditor: (id: number, field: string, value: string | boolean | number) => void;
    addIndependentDebtor: () => void;
    addSolidaryDebtor: () => void;
    addAnotherDebtor: () => void;
    removeAdditionalDebtor: (id: string) => void;
    updateAdditionalDebtor: (id: string, field: string, value: string | boolean | number) => void;
    updateDebtor: (id: number, field: string, value: string | boolean | number) => void;
    visitationChildrenNames: string[];
    setVisitationChildrenNames: Dispatch<SetStateAction<string[]>>;
    visitationScheduleDraft: Partial<VisitationScheduleConfig>;
    setVisitationScheduleDraft: Dispatch<SetStateAction<Partial<VisitationScheduleConfig>>>;
    custodyWardNames: string[];
    setCustodyWardNames: Dispatch<SetStateAction<string[]>>;
    handleSubmit: () => void;
    sectionConfirmDialog: ReactNode;
    docTypeSheetOpen: boolean;
    handleDocTypeChange: (v: string) => void;
    claimTypeSheetOpen: boolean;
    shariaExclusiveClaimOptions: SelectOption[];
    showShariaLinkedClaimPanel: boolean;
    setActiveClaimTypes: Dispatch<SetStateAction<string[]>>;
    setLinkedClaimDraft: Dispatch<SetStateAction<string[]>>;
    shariaLinkedClaimOptions: SelectOption[];
    linkedClaimDraft: string[];
    toggleLinkedClaimDraft: (value: string) => void;
    saveLinkedClaimDraft: () => void;
    showChequeValidatorModal: boolean;
    chequeBankName: string;
    chequeIssueDate: string;
    setChequeBankName: Dispatch<SetStateAction<string>>;
    setChequeIssueDate: Dispatch<SetStateAction<string>>;
    setShowChequeValidatorModal: Dispatch<SetStateAction<boolean>>;
    setClaimType: Dispatch<SetStateAction<string>>;
    showAbsenteeModal: boolean;
    absenteeChecks: AbsenteeChecks;
    setAbsenteeChecks: Dispatch<SetStateAction<AbsenteeChecks>>;
    setShowAbsenteeModal: Dispatch<SetStateAction<boolean>>;
    setIsDocumentBlocked: Dispatch<SetStateAction<boolean>>;
    claimUsesMonetaryAmountField: (ct: string) => boolean;
    isShariaLinkedFinancialClaim: (ct: string) => boolean;
};
