/** Stable selectors for E2E / integration (no visual impact). */
export const CRIMINAL_DOSSIER_TEST_IDS = {
    dossier: 'criminal-dashboard-dossier',
    back: 'criminal-dashboard-back',
    exit: 'criminal-dashboard-exit',
    trialHearingDateOpen: 'criminal-trial-hearing-date-open',
    trialHearingDateHint: 'criminal-trial-hearing-date-hint',
    trialHearingDateModal: 'criminal-trial-hearing-date-modal',
    trialHearingDateInput: 'criminal-trial-hearing-date-input',
    trialHearingDateSave: 'criminal-trial-hearing-date-save',
    portal: 'criminal-dashboard-portal',
    archiveTabCriminal: 'archive-tab-criminal',
    caseCard: (id: string) => `criminal-case-${id}`,
    newCaseForm: 'criminal-new-case-form',
    newCaseSave: 'criminal-new-case-save',
    jurisdictionCriminal: 'new-case-jurisdiction-criminal',
    tabRequests: 'criminal-dashboard-tab-requests',
    tabStatements: 'criminal-dashboard-tab-statements',
    statementsPanel: 'criminal-statements-panel',
    requestsPanel: 'criminal-requests-panel',
    trackingPanel: 'criminal-tracking-panel',
    statementsAdd: 'criminal-statements-add',
    statementModal: 'criminal-statement-modal',
    statementGiverType: 'criminal-statement-giver-type',
    statementContent: 'criminal-statement-content',
    statementSave: 'criminal-statement-save',
    statementConfirmSave: 'criminal-statement-confirm-save',
    requestsModal: 'criminal-requests-modal',
    decisionsAddLawyerMotion: 'criminal-decisions-add-lawyer-motion',
    decisionsAddJudicial: 'criminal-decisions-add-judicial',
    requestDate: 'criminal-request-date',
    requestNote: 'criminal-request-note',
    requestSubmit: 'criminal-request-submit',
    judicialTemplateSelect: 'criminal-judicial-template-select',
    judicialCustomName: 'criminal-judicial-custom-name',
    lawyerMotionName: 'criminal-lawyer-motion-name',
    otherEvidenceToggle: 'criminal-other-evidence-toggle',
    otherEvidenceType: 'criminal-other-evidence-type',
    otherEvidenceNotes: 'criminal-other-evidence-notes',
    otherEvidenceSave: 'criminal-other-evidence-save',
    headerTrash: 'criminal-header-trash',
    trashModal: 'criminal-trash-modal',
    trashRestore: 'criminal-trash-restore',
} as const;
