/**
 * Deprecated path — re-exports decisionAppealPeriodEngine.
 * Import path `./decisionAppealLifecycleCore` preserved for remaining consumers.
 */

export type {
    AppealPeriodSnapshot,
    CassationCorrectionDecisionOutcome,
    CassationCorrectionEligibilityInput,
    CassationCorrectionUserRole,
    DecisionAppealabilityCategory,
    DecisionAppealActionKind,
    DecisionAppealBadgeTone,
    DecisionAppealBadgeView,
    DecisionAppealLifecycleFields,
    DecisionAppealStatePhase,
    DecisionCaseType,
    DecisionPresenceType,
} from './decisionAppealPeriodEngine';

export {
    CASSATION_CORRECTION_WINDOW_DAYS,
    ORDINARY_CASSATION_WINDOW_DAYS,
    addCalendarDaysIso,
    buildDefaultAppealFieldsForNewDecision,
    canShowCassationCorrectionButton,
    canShowCassationCorrectionForJudicialDecision,
    computeAppealPeriodSnapshot,
    computeOrdinaryCassationWindow,
    enrichJudicialDecisionAppealFields,
    formatAppealResultLabel,
    hasCassationCorrectionPartyInterest,
    inferDecisionAppealability,
    inferDecisionCaseType,
    inferDecisionPresenceType,
    isCassationCorrectionBlockedByArticle267,
    isCassationIssuedByGeneralAssembly,
    isCassationResultAffirmationUpheld,
    isCassationResultQuashRemand,
    resolveAppealPeriodStartExclusive,
    resolveAppealResultCategory,
    resolveAppealResultRecordedAt,
    resolveCassationCorrectionRemainingDays,
    resolveCassationCorrectionRemainingDaysForAnchor,
    resolveDecisionAppealActions,
    resolveDecisionAppealBadge,
    resolveDecisionAppealLifecycle,
    resolveDecisionAppealStatePhase,
    resolveJudicialCassationCorrectionOutcome,
    resolveJudicialCassationIssuedBy,
    resolveOrdinaryCassationLastDayInclusive,
    resolveStoredAppealResultRaw,
    resolveTotalAppealLegalDays,
    shouldShowCassationAppealFileAction,
} from './decisionAppealPeriodEngine';
