/**
 * Public procedural-request types API — barrel re-exporting split modules.
 * Import path `./proceduralRequestTypes` is preserved for all consumers.
 */

export {
    ARREST_ORDER_TEMPLATE,
    ARREST_SUMMON_TEMPLATE,
    ASSET_SEIZURE_TEMPLATE,
    BAIL_RELEASE_TEMPLATE,
    COMPLAINT_COURT_REFERRAL_TEMPLATE,
    CUSTOM_JUDICIAL_DECISION_TYPE,
    CUSTOM_LAWYER_MOTION_TYPE,
    DEFENDANT_BAIL_TEMPLATE,
    DETENTION_DECISION_TEMPLATE,
    INVESTIGATION_CLOSURE_FINAL_OBJECTIVE_TEMPLATE,
    INVESTIGATION_CLOSURE_FINAL_PERSONAL_TEMPLATE,
    INVESTIGATION_CLOSURE_FINAL_TEMPLATE,
    INVESTIGATION_CLOSURE_TEMPORARY_TEMPLATE,
    INVESTIGATION_MERGE_JUDICIAL_TEMPLATE,
    INVESTIGATION_PURGE_JUDICIAL_TEMPLATES,
    INVESTIGATION_SEVERANCE_JUDICIAL_TEMPLATE,
    JUVENILE_EXCLUSIVE_JUDGE_DECISION_TEMPLATES,
    JUVENILE_JUDGE_DECISION_TEMPLATES,
    JUVENILE_OBSERVATION_HOME_DECISION_TEMPLATE,
    JUVENILE_PROVISIONAL_DELIVERY_DECISION_TEMPLATE,
    JUVENILE_SOCIAL_INQUIRY_REFERRAL_TEMPLATE,
    SUMMON_ORDER_TEMPLATE,
    formatInvestigationPurgeDecisionDisplayTitle,
    formatJudicialTemplateDisplayLabel,
    isInvestigationClosureAppealablePurgeTemplate,
    isInvestigationExpirationJudicialTemplate,
    isInvestigationFinalClosureTemplate,
    isInvestigationMergeJudicialTemplate,
    isInvestigationObjectiveFinalClosureTemplate,
    isInvestigationPurgeDecisionTemplate,
    isInvestigationImmediatePurgeTemplate,
    isInvestigationSeveranceJudicialTemplate,
    isInvestigationSharedOrderTemplate,
    isInvestigationStructuralCassationTemplate,
    isJuvenileExclusiveInvestigationPurgeTemplate,
    isJuvenileJudgeCassationAppealableTemplate,
    isJuvenileJudgeDecisionTemplate,
    isPrivateRightWaiverTemplate,
    normalizeProceduralRequestTemplate,
    purgeDecisionIncludesUnknownDefendants,
} from './proceduralRequestTemplateCore';

export {
    CASSATION_APPEALABLE_PREPARATORY_TEMPLATES,
    JUDICIAL_DECISION_TEMPLATES,
    LAWYER_MOTION_DROPDOWN_TEMPLATES,
    isAssetSeizureTemplate,
    isComplaintCourtReferralTemplate,
    isCustomJudicialTemplate,
    isCustomLawyerMotionTemplate,
    isDecisionCassationAppealable,
    isDefendantBailTemplate,
    isDetentionDecisionTemplate,
    isDetentionRequestTemplate,
    isJudicialDecisionTemplate,
    isJudicialDefendantStatusDocumentationOnly,
    isLawyerMotionTemplate,
    isOrderEnforcementTemplate,
    judicialDecisionModalTemplates,
    lawyerMotionModalTemplates,
    requiresDetentionDateRange,
    resolveOrderEnforcementKindFromTemplate,
    resolveRequestEntryLane,
    resolveRequestTypeTemplateFromStored,
    resolveStoredRequestTypeFields,
} from './proceduralRequestClassify';
