/** شكل سجل القضية المخزّن في IDB (حقول اختيارية حسب مرحلة الإجراء) */
export type PersistedCaseRecord = {
    id?: string;
    type?: string;
    specificActionType?: string;
    hasIntervention?: boolean;
    judgeDecision?: string;
    judgeDecisionDate?: string;
    requiresGuarantee?: boolean;
    judgeDecisionRequiresGuarantee?: boolean;
    guaranteeSubmitted?: boolean;
    guaranteeStatus?: boolean;
    guaranteeAmount?: string;
    guaranteeReceiptNumber?: string;
    notificationDate?: string;
    rejectionNotificationDate?: string;
    deadlineDays?: number;
    grievancePetitionNotificationDate?: string;
    grievanceLegalEndDate?: string;
    grievanceOutcome?: 'filed' | 'expired';
    grievanceOutcomeDraft?: 'filed' | 'expired';
    grievanceDetailsConfirmed?: boolean;
    grievanceFilingDate?: string;
    grievanceFirstHearingDate?: string;
    phase2FirstHearingDate?: string;
    grievanceDecision?: 'confirmed' | 'modified' | 'canceled';
    grievanceDecisionDate?: string;
    cassationOutcome?: 'filed' | 'expired';
    cassationFiledBy?: 'client' | 'opponent';
    cassationFilingDate?: string;
    cassationFileNumber?: string;
    cassationDecision?: 'confirmed' | 'modified' | 'canceled';
    cassationDecisionDate?: string;
    legalState?: string;
    defenderEntryPhase?: number;
    hearings?: unknown[];
    expertModule?: Record<string, unknown>;
    preDecisionClosed?: boolean;
    expectedDecisionDate?: string;
    feeReceiptNumber?: string;
    feeReceiptDate?: string;
    initialNotificationMethod?: string;
    initialNotificationDate?: string;
    events?: unknown[];
    notes?: unknown[];
    attachments?: unknown[];
    followups?: unknown[];
    firstHearingDate?: string;
    [key: string]: unknown;
};
