import { describe, expect, it, vi } from 'vitest';
import { renderHook } from '@testing-library/react';
import { useExecutionDashboardCorePersistHandlerPipeline } from '../useExecutionDashboardCorePersistHandlerPipeline';

describe('useExecutionDashboardCorePersistHandlerPipeline', () => {
    it('wires followup, save, trash, party edit, and effects clusters through the shared persist merge binding', () => {
        const persistExecutionMerge = vi.fn();
        const executionDataRef = { current: { id: 'exec-1' } as Record<string, unknown> };
        const followupOrchestrator = {
            setUnifiedModalTab: vi.fn(),
            openExecutionSeizuresTab: vi.fn(),
            showHeirsNotificationModal: false,
            setShowHeirsNotificationModal: vi.fn(),
        };
        const coercionOrchestrator = {
            debtorArrested: false,
            investigationPathDebtorPresent: false,
            setDebtorArrested: vi.fn(),
            setInvestigationPathDebtorPresent: vi.fn(),
        };

        const input = {
            effectiveDebtors: [],
            financialPrincipalAmount: 0,
            financialLawyerFeesAmount: 0,
            claimType: 'دين',
            isNonFinancialClaim: false,
            debtorBrowserTabsMode: false,
            effectiveFollowupDebtorEntry: null,
            activeWorkspaceDebtorForFollowup: null,
            executionData: { id: 'exec-1' },
            executionId: 'exec-1',
            decisionsReloadEpoch: 0,
            isEvictionExecutionModule: false,
            unifiedCollectionApproved: false,
            notificationCount: 0,
            forcedAttendanceIssued: false,
            coercionOrchestrator,
            isEvictionGraceExpiredNow: false,
            isGracePeriodExpiredNow: false,
            debtorNotificationDate: null,
            manualGraceCalendarExtra: 0,
            lawyerStartedPostNoticeExecution: false,
            noticeVoluntaryPeriodEndOptimistic: false,
            voluntaryEndOptimistic: false,
            isEvictionGraceEffectivelyExpired: false,
            activeCoerciveActions: [],
            activeDebtorNoticeScope: {},
            debtorSummonsMarkerLocal: {},
            monetaryExecutionStrictPathFlag: false,
            isAlimonyClaim: false,
            executionExtras: {},
            unifiedSummonsTargetDebtorKey: null,
            activeDebtorIsDeceased: false,
            primaryDebtorKeyResolved: null,
            debtorNotifiedForEvictionGrace: false,
            remaining: 0,
            daysSinceNoticeCalculated: 0,
            executionFeeInjected: false,
            showToast: vi.fn(),
            statuteStatus: null,
            showStatuteWarning: false,
            setShowStatuteWarning: vi.fn(),
            lastActionDate: null,
            timelineEvents: [],
            caseNotesLog: [],
            caseTasksPending: [],
            financialLedger: {},
            gracePeriodActive: false,
            gracePeriodEnded: false,
            followupOrchestrator,
            file: null,
            currentFileId: 'file-1',
            onUpdate: vi.fn(),
            setTimelineEvents: vi.fn(),
            setCaseNotesLog: vi.fn(),
            setCaseTasksPending: vi.fn(),
            setExecutionReportPrompt: vi.fn(),
            setJudicialCustodianModalCtx: vi.fn(),
            setJudicialCustodianModalOpen: vi.fn(),
            setShowDecisionsModal: vi.fn(),
            setShowUnifiedSummonsModal: vi.fn(),
            setShowNotesModal: vi.fn(),
            setShowDocumentsModal: vi.fn(),
            setShowAppointmentModal: vi.fn(),
            setShowTimelineModal: vi.fn(),
            setShowNotificationModal: vi.fn(),
            setShowCoerciveModal: vi.fn(),
            setShowExecutionFinancialHub: vi.fn(),
            setShowUnifiedExecutionModal: vi.fn(),
            setShowLedgerModal: vi.fn(),
            setShowPaymentCalculator: vi.fn(),
            setShowSettlementCalculator: vi.fn(),
            setShowEvictionExpenseModal: vi.fn(),
            setShowPaymentModal: vi.fn(),
            setShowSeizedAssetsModal: vi.fn(),
            setShowNotesModalDuplicate: vi.fn(),
            persistExecutionMerge,
            executionDataRef,
            decisionsStorageExecutionId: 'exec-1',
            openBreakInventoryCompletion: vi.fn(),
            openJudicialCustodianCompletion: vi.fn(),
            isUnifiedTabActive: false,
            unifiedTabId: '',
            seizureDraftsByDecisionIdRef: { current: {} },
            setExecutionStorageTick: vi.fn(),
            showExecutionTrashModal: false,
            setShowExecutionTrashModal: vi.fn(),
            caseNotesLogRef: { current: [] },
            caseTasksPendingRef: { current: [] },
            setPermanentDeleteTimelineId: vi.fn(),
            viewExecutionData: { id: 'exec-1' },
            isHistoricalMode: false,
            activeSubFileId: null,
            parentDossierId: 'parent-1',
            setSeizureDraftsByDecisionId: vi.fn(),
            seizedAssetsSnapshotRef: { current: [] },
            maritalFurnitureItemsForFollowup: [],
            setActiveCoerciveActions: vi.fn(),
            pushTimelineEvent: vi.fn(),
            pushTimelineEventRef: { current: vi.fn() },
            nextTimelineId: vi.fn(() => 'tl-1'),
            timelineEventsRef: { current: [] },
            isMaritalFurnitureClaim: false,
            setShowUnifiedSummonsModalDuplicate: vi.fn(),
            setUnifiedModalTab: vi.fn(),
            setFollowupExpandProcedureKey: vi.fn(),
            setCaseTasksPendingDuplicate: vi.fn(),
            setTimelineEventsDuplicate: vi.fn(),
            setExecutionReportPromptDuplicate: vi.fn(),
            setJudicialCustodianModalCtxDuplicate: vi.fn(),
            setJudicialCustodianModalOpenDuplicate: vi.fn(),
            setCaseNotesLogDuplicate: vi.fn(),
            executionFileSnapshotRef: { current: { id: 'exec-1' } },
            persistExecutionMergeRef: { current: persistExecutionMerge },
        };

        const { result } = renderHook(() =>
            useExecutionDashboardCorePersistHandlerPipeline(input as never),
        );

        expect(result.current.persistExecutionMerge).toEqual(expect.any(Function));
        expect(result.current.executorApprovalActions).toEqual(expect.any(Object));
        expect(result.current.saveExecutionData).toEqual(expect.any(Function));
        expect(result.current.partyEditWorkflow).toEqual(expect.any(Object));
        expect(result.current.trashAndPinsHandlers).toEqual(expect.any(Object));
        expect(result.current.tryOpenPendingBreakInventoryLedger).toEqual(expect.any(Function));
        expect(result.current.tryOpenPendingCustodianDetails).toEqual(expect.any(Function));
    });
});
