import fs from 'fs';

const corePath = 'src/app/components/lawyer/ExecutionDashboard/hooks/useExecutionDashboardCore.ts';
let core = fs.readFileSync(corePath, 'utf8');

const start = core.indexOf('    const debtorWorkspaceContext = useExecutionDashboardDebtorWorkspaceContext({');
const end = core.indexOf('    const executionExtras = (executionData');
if (start < 0 || end <= start) {
    console.error('followup block not found', start, end);
    process.exit(1);
}

const replacement = `    const followupDebtor = useExecutionDashboardCoreFollowupDebtorPipeline({
        executionData,
        viewExecutionData,
        executionId,
        decisionsStorageExecutionId,
        decisionsReloadEpoch,
        claimType,
        creditors,
        debtors,
        mergedTimelineEvents,
        activeTimelineEvents,
        activeCoerciveActions,
        realEstateSeizureRegistryAssets,
        salarySeizureRegistryAssets,
        movableSeizureRegistryAssets,
        thirdPartySeizureRegistryAssets,
        thirdPartySeizuresUi,
        showToast,
        showUnifiedExecutionModal,
        dossierFileKey,
        executionFileKey,
        setShowDecisionsModal,
        showDecisionsModal,
        setActiveTimelineFilter,
        setShowExtraCreditors,
        setShowExtraDebtors,
        caseTasksPendingRef,
        setCaseTasksPending,
        setTimelineEvents,
        persistExecutionMergeRef,
        setNotificationCount,
        setDebtorSummonsMarkerLocal,
        pushTimelineEventRef,
        nextTimelineId,
        followupOrchestrator,
    });

    const {
        debtorWorkspaceContext,
        effectiveCreditors,
        effectiveDebtors,
        allDebtorsUnified,
        resolveDebtorSolidaryFlag,
        allDebtorsSolidary,
        isSolidaryLiability,
        debtorWorkspaceEntries,
        creditorWorkspaceEntries,
        creditorNamesTextList,
        perDebtorSolidarySplitMode,
        debtorLiabilityGroups,
        liabilityGroupTabsMode,
        multiDebtorMode,
        debtorBrowserTabsMode,
        activeLiabilityGroup,
        activeGroupEntries,
        activeLiabilityGroupId,
        allDebtorRowsForLiability,
        activeDebtorSolidary,
        activeWorkspaceDebtorForFollowup,
        primaryDebtorWorkspaceKey,
        primaryDebtorKeyResolved,
        showFollowupSolidaryDebtorTabs,
        effectiveFollowupDebtorEntry,
        followupAssignmentWorkspaceCtx,
        mergedTimelineEventsDebtorScoped,
        mergedTimelineRadarPreviewLimit,
        assignmentWorkspaceCtx,
        unifiedSummonsTargetDebtorKey,
        activeDebtorNoticeScope,
        scopedNotificationCount,
        scopedSummonsMarker,
        followupActiveDebtorNoticeScope,
        modalActiveDebtorNoticeScope,
        activeDebtorIsEmployee,
        activeDebtorIsDeceased,
        followupModalDebtorIsEmployee,
        followupModalDebtorIsDeceased,
        modalKasabTerminationEmphasis,
        modalResolvedEmployeeSummonsAssignment,
        modalShowEmployeeAssignmentCoerciveBlock,
        employeeAssignmentPhaseForCoercive,
        employeeUnlocksPersonalCoerciveFromAssignment,
        followupModalEntityKind,
        followupModalSpecialization,
        followupModalSpecializationEffective,
        seizedPropertiesForSeizureLog,
        seizedMovablesForSeizureLog,
        seizureLogExecutorDecisions,
        unifiedSeizureLog,
        showUnifiedSeizureLogModal,
        closeUnifiedSeizureLog,
        unifiedSeizureLogTab,
        setUnifiedSeizureLogTab,
        unifiedSeizureLogEntries,
        unifiedSeizureTabCounts,
        hasUnifiedSeizureLogContent,
        openUnifiedSeizureLog,
        thirdPartyFundsDraftById,
        setThirdPartyFundsDraftById,
        clearThirdPartyFundsDraft,
        activeDebtorNameResolved,
        activeDebtorInitialWasEmployee,
        activeTimelineEventsDebtorScoped,
        timelineRadarPreviewLimit,
        kasabTerminationEmphasis,
        activeDebtorEntityKind,
        activeDebtorIsLegalEntity,
        isRepresentingDebtor,
        appealPerspective,
        hideCoerciveTabsForDebtorAgent,
        followupTabAssembly,
        executionDomainContext,
        followupSpecialization,
        followupSpecializationEffective,
        showPersonalCoerciveFollowupTab,
        showSalarySeizureInFollowupModal,
        followupSalarySeizureLabel,
        showEmployeeCompulsoryProceduresBanner,
        activeFollowupDebtorKey,
        personalTabUnlockByDebtor,
        setPersonalTabUnlockByDebtor,
        employeePersonalTabUnlockStorageKey,
        custodyRemovalClaimActive,
        employeeCoerciveDetentionRestricted,
        modalEmployeeCoerciveDetentionRestricted,
        modalShowPersonalCoerciveFollowupTab,
        personalTabLockedForEmployee,
        modalPersonalTabLockedForEmployee,
        followupTabsRestricted,
        followupSectionTabOrder,
        followupModalTabs,
        isFollowupTabActive,
        openFollowupModalPersisted,
        closeFollowupModalPersisted,
        persistFollowupModalViewport,
        goFollowupSectionTabByDelta,
        timelineFilterOptions,
    } = followupDebtor;

`;

core = core.slice(0, start) + replacement + core.slice(end);

const importLine =
    "import { useExecutionDashboardCoreFollowupDebtorPipeline } from './executionDashboardCore/useExecutionDashboardCoreFollowupDebtorPipeline';";
if (!core.includes('useExecutionDashboardCoreFollowupDebtorPipeline')) {
    core = core.replace(
        "import { useExecutionDashboardCoreClaimFinancialLedgerPipeline } from './executionDashboardCore/useExecutionDashboardCoreClaimFinancialLedgerPipeline';",
        importLine + "\nimport { useExecutionDashboardCoreClaimFinancialLedgerPipeline } from './executionDashboardCore/useExecutionDashboardCoreClaimFinancialLedgerPipeline';",
    );
}

fs.writeFileSync(corePath, core, 'utf8');
console.log('patch-slice26 OK, core lines:', core.split('\n').length);
