import fs from 'fs';

const corePath = 'src/app/components/lawyer/ExecutionDashboard/hooks/useExecutionDashboardCore.ts';
let core = fs.readFileSync(corePath, 'utf8');

function replaceBlock(startMarker, endMarker, replacement) {
    const start = core.indexOf(startMarker);
    const end = core.indexOf(endMarker, start);
    if (start < 0 || end <= start) {
        console.error('block not found', { startMarker, endMarker, start, end });
        process.exit(1);
    }
    core = core.slice(0, start) + replacement + core.slice(end);
}

// imports
if (!core.includes('useExecutionDashboardCoreWorkspacePipeline')) {
    const importAnchor = core.includes("import { useExecutionDashboardSeizureLedgerOutcomeEffects }")
        ? "import { useExecutionDashboardSeizureLedgerOutcomeEffects } from './executionDashboardCore/useExecutionDashboardSeizureLedgerOutcomeEffects';"
        : "import { buildExecutionDashboardCoreRuntimeVars } from './executionDashboardCore/buildExecutionDashboardCoreRuntimeVars';";
    if (!core.includes(importAnchor)) {
        core = core.replace(
            'export function useExecutionDashboardCore({',
            `import { useExecutionDashboardCoreWorkspacePipeline } from './executionDashboardCore/useExecutionDashboardCoreWorkspacePipeline';
import { useExecutionDashboardCoreGraceMasterEvictionPipeline } from './executionDashboardCore/useExecutionDashboardCoreGraceMasterEvictionPipeline';
import { useExecutionDashboardCorePersistHandlerPipeline } from './executionDashboardCore/useExecutionDashboardCorePersistHandlerPipeline';
import { buildExecutionDashboardCoreRuntimeVars } from './executionDashboardCore/buildExecutionDashboardCoreRuntimeVars';

export function useExecutionDashboardCore({`,
        );
    } else {
        core = core.replace(
            importAnchor,
            `${importAnchor}
import { useExecutionDashboardCoreWorkspacePipeline } from './executionDashboardCore/useExecutionDashboardCoreWorkspacePipeline';
import { useExecutionDashboardCoreGraceMasterEvictionPipeline } from './executionDashboardCore/useExecutionDashboardCoreGraceMasterEvictionPipeline';
import { useExecutionDashboardCorePersistHandlerPipeline } from './executionDashboardCore/useExecutionDashboardCorePersistHandlerPipeline';
import { buildExecutionDashboardCoreRuntimeVars } from './executionDashboardCore/buildExecutionDashboardCoreRuntimeVars';`,
        );
    }
}

const wsDestructure = `    const workspacePipeline = useExecutionDashboardCoreWorkspacePipeline({
        modals,
        executionData,
        executionDataRef,
        executionFileKey,
        executionDashboardFileId,
        executionId,
        executionStorageTick,
        setExecutionModal,
        showDecisionsModal,
        setShowDecisionsModal,
        setShowNotesModal,
        setShowDocumentsModal,
        setShowAppointmentModal,
        setShowTimelineModal,
        setShowNotificationModal,
        setShowCoerciveModal,
        subFiles,
        activeSubFileId,
        isInabaActive,
        parentDossierId,
        persistExecutionMergeRef,
        pushTimelineEventRef,
        executionFileSnapshotRef,
    });

    const {
        todayYmd,
        noteTitle, setNoteTitle, noteBody, setNoteBody, isTask, setIsTask,
        taskDueDate, setTaskDueDate, taskStatus, setTaskStatus,
        editingTaskId, setEditingTaskId, editingNoteId, setEditingNoteId,
        savedNotesView, setSavedNotesView, showUnifiedExecutionModal,
        followupOrchestrator, timelineAccordionExpanded, setTimelineAccordionExpanded,
        activeTimelineFilter, setActiveTimelineFilter, gracePeriodActive, setGracePeriodActive,
        gracePeriodEnded, setGracePeriodEnded, notificationCount, setNotificationCount,
        notificationPurpose, setNotificationPurpose, voluntaryEndOptimistic, setVoluntaryEndOptimistic,
        noticeVoluntaryPeriodEndOptimistic, setNoticeVoluntaryPeriodEndOptimistic,
        summonsMarkerPopoverOpen, setSummonsMarkerPopoverOpen, executionMemoBadgePopoverOpen,
        setExecutionMemoBadgePopoverOpen, summonsPurposeDraft, setSummonsPurposeDraft,
        forcedAttendanceIssued, setForcedAttendanceIssued, debtorEvaded, setDebtorEvaded,
        arrestWarrantUnlocked, setArrestWarrantUnlocked, creditorAttended, executionPaused,
        setExecutionPaused, showUnifiedSummonsModal, setShowUnifiedSummonsModal, coercionOrchestrator,
        lastActionDate, setLastActionDate, showStatuteWarning, setShowStatuteWarning,
        dossierLifecyclePanel, showExecutionTrashModal, setShowExecutionTrashModal,
        permanentDeleteTimelineId, setPermanentDeleteTimelineId, paidDebt, paidDebtRef,
        paidCourtFees, setPaidCourtFees, paidDirectorateFees, setPaidDirectorateFees,
        paidClientFees, setPaidClientFees, noteText, setNoteText, appointmentPurpose,
        setAppointmentPurpose, appointmentDateOnly, setAppointmentDateOnly, appointmentTimeOptional,
        setAppointmentTimeOptional, editingAppointmentId, setEditingAppointmentId, appointmentContext,
        setAppointmentContext, executorScheduleModalOpen, setExecutorScheduleModalOpen,
        executorScheduleContext, setExecutorScheduleContext, breakInventoryFurnitureModalOpen,
        setBreakInventoryFurnitureModalOpen, breakInventoryFurnitureModalCtx,
        setBreakInventoryFurnitureModalCtx, judicialCustodianModalOpen, setJudicialCustodianModalOpen,
        judicialCustodianModalCtx, setJudicialCustodianModalCtx, executionReportPrompt,
        setExecutionReportPrompt, financialLedger, financialLedgerRef, hasFinancialLedger,
        showLedgerModal, setShowLedgerModal, paymentAmount, setPaymentAmount, paymentDate,
        setPaymentDate, debtorNotificationDate, setDebtorNotificationDate, manualGraceCalendarExtra,
        setManualGraceCalendarExtra, timelineEvents, setTimelineEvents, timelineEventsRef,
        earnerFeeCollectionSm, setEarnerFeeCollectionSm, caseNotesLog, setCaseNotesLog,
        caseNotesLogRef, caseTasksPending, setCaseTasksPending, caseTasksPendingRef,
        evictionGracePinned, setEvictionGracePinned, evictionGraceHidden, setEvictionGraceHidden,
        toggleEvictionGracePinned, gracePinnedKey, graceHiddenKey, activeTimelineEvents,
        showOnlyActiveFileTimeline, setShowOnlyActiveFileTimeline, mergedTimelineEvents,
        completedTaskTitles, savedNotesSplit, activeCaseTasksPendingAll, activeGraceTasks,
        activeCaseTasksPending, trashedTimelineEvents, trashedCaseNotes, trashedCaseTasks,
        dockPinnedNotes, dockPinnedTasks, nextTimelineId, seizedAssets, setSeizedAssets,
        seizedAssetsSnapshotRef, realEstateSeizureAssets, setRealEstateSeizureAssets,
        realEstateSeizureSnapshotRef, thirdPartySeizureAssets, setThirdPartySeizureAssets,
        thirdPartySeizureSnapshotRef, standaloneExecutionMarks, setStandaloneExecutionMarks,
        standaloneExecutionMarksSnapshotRef, getMilestoneTimelineSnapshot, seizureDraftsByDecisionId,
        setSeizureDraftsByDecisionId, seizureDraftsByDecisionIdRef, activeCoerciveActions,
        setActiveCoerciveActions, showCoerciveActionForm, setShowCoerciveActionForm,
        seizureDetailCompletion, setSeizureDetailCompletion, saveCoerciveActionRef,
        focusSeizurePropertyInlineRef, focusSeizureMovableInlineRef, focusSeizureThirdPartyInlineRef,
        focusSeizureNoticeInlineRef, seizureOrchestrator, approvedSeizedAssets,
        movableSeizureRegistryAssets, salarySeizureRegistryAssets, realEstateSeizureRegistryAssets,
        thirdPartySeizureRegistryAssets, salarySeizureTabRows, isPaused, setIsPaused, pauseReason,
        setPauseReason, executionFeeAdded, toastVisible, toastMessage, toastType, toastEpoch,
        showToast, hideToast, showToastRef, decisionsOrchestrator, decisionsReloadEpoch,
        setDecisionsReloadEpoch, decisionsModalBootHubTab, setDecisionsModalBootHubTab,
        decisionsModalBootListTab, setDecisionsModalBootListTab, decisionsModalScrollToDecisionId,
        setDecisionsModalScrollToDecisionId, appealsModalScrollToDecisionId,
        setAppealsModalScrollToDecisionId, clearDecisionsModalBootState, openDecisionsModalWithBoot,
        forcedBringDecisionState, employeeForcedBringAwaitingPersonalOutcome, executionFeeInjected,
        setExecutionFeeInjected, financialOrchestrator, isFinancialCenterExpanded,
        setIsFinancialCenterExpanded, activeFinancialTab, setActiveFinancialTab,
        showExecutionFinancialHub, setShowExecutionFinancialHub, financialHubAutoOpenMode,
        setFinancialHubAutoOpenMode, financialHubSeizedMovableId, setFinancialHubSeizedMovableId,
        financialHubSeizedPropertyId, setFinancialHubSeizedPropertyId, openFinancialHubLedger,
        thirdPartySeizuresUi, setThirdPartySeizuresUi, applyThirdPartySeizuresFromPatch,
    } = workspacePipeline;

`;

replaceBlock(
    '\tconst todayYmd = useTodayYmd();',
    '    // ===========================\n    // OMNIBUS 1:1 DATA BINDING - ZERO DATA LOSS',
    wsDestructure,
);

const graceReplacement = `    const graceMasterPipeline = useExecutionDashboardCoreGraceMasterEvictionPipeline({
        executionData,
        executionId,
        debtorNotificationDate,
        debtors,
        effectiveDebtors,
        isEvictionExecutionModule,
        notificationCount,
        manualGraceCalendarExtra,
        voluntaryEndOptimistic,
        setVoluntaryEndOptimistic,
        noticeVoluntaryPeriodEndOptimistic,
        setNoticeVoluntaryPeriodEndOptimistic,
        debtorBrowserTabsMode,
        effectiveFollowupDebtorEntry,
        activeWorkspaceDebtorForFollowup,
        activeTimelineEventsDebtorScoped,
        coercionOrchestrator,
        claimType,
        isAlimonyClaim,
        monetaryStrictForSummoningEngine,
        forcedAttendanceIssued,
        initiator,
        paidDebt,
        totalOwed,
        parsedCourtFees,
        financialPrincipalAmount,
        paidCourtFees,
        paidDirectorateFees,
        paidClientFees,
        activeDebtorIsEmployee,
        followupSpecializationEffective,
        followupModalSpecializationEffective,
        followupModalDebtorIsEmployee,
        decisionsReloadEpoch,
        isRepresentingDebtor,
        decisionsStorageExecutionId,
        followupSpecialization,
        showPersonalCoerciveFollowupTab,
        showGuarantorInSeizureFollowupTab,
        isPersonalStatusExecutionClaim,
        isAlimonyClaimType,
        custodyRemovalClaimActive,
        employeeCoerciveDetentionRestricted,
        remainingBalanceForSeizure,
        viewExecutionData,
        settlementGuarantorGate,
        activeDebtorIsDeceased,
        assignmentWorkspaceCtx,
        primaryDebtorKeyResolved,
        personalTabLockedForEmployee,
        remaining,
        lastActionDate,
        dossierLifecycleRow,
        executionPaused,
        isPaused,
        pauseReason,
        executionFeeAdded,
        activeDebtorSolidary,
        allDebtorsUnified,
        followupOrchestrator,
        isHistoricalMode,
        debtorNotifiedForEvictionGrace,
        evictionPremisesUseResolved,
        todayYmd,
        timelineEventsRef,
        gracePeriodEnded,
        setGracePeriodEnded,
        setGracePeriodActive,
        showToastRef,
        showToast,
    });

    const {
        graceAndSummoning,
        generalMemoGraceAnchor,
        daysSinceNoticeCalculated,
        daysRemainingInGracePeriod,
        isGracePeriodExpiredNow,
        evictionGraceAnchorDate,
        isEvictionGraceExpiredCalendar,
        isEvictionGraceEffectivelyExpired,
        daysRemainingInEvictionGrace,
        isEvictionGraceExpiredNow,
        forcedSummoningAnalysis,
        shouldCalculateExecutionFee,
        calculatedExecutionFee,
        totalWithExecutionFee,
        remaining,
        isInBreach,
        earnerFinancialPersonalCoerciveActive,
        hideExecutiveDetentionJudgeCard,
        followupSpecializationWithEarnerGate,
        followupModalSpecializationEffectiveWithEarnerGate,
        unifiedCollectionApproved,
        otherPartyCreditorMirrorProps,
        statuteStatus,
        masterState,
        executionStatusRaw,
        executionStatus,
        statusMetadata,
        stayOfExecutionActive,
        coerciveUiState,
        coerciveUiLocked,
        dividedActiveDebtorCleared,
        executionCoerciveButtonDisabled,
        dossierStatusUi,
        coerciveDossierLocked,
        executionActionsGridLocked,
        executionToolsTimelineLockedUi,
        evictionProcedureLocked,
        isDebtorDeceasedForEvictionHeirs,
        creditorDeathMarked,
        debtorDeathMarked,
        creditorDeathMenuLabel,
        debtorDeathMenuLabel,
        heirSubstitutionAllowed,
        ongoingAlimonyClaim,
        alimonyBeneficiaryProfile,
        lawyerFeePayoutApproved,
        notifDateForEvictionVacate,
        residentialVacateDeadlineMaxIso,
        notificationLayerOkEviction,
        isResidentialVacateGraceFinished,
        evictionVacateLayerOk,
        evictionProcedureLockHint,
        evictionGraceBadgeInfo,
        policeAssistanceBadgeInfo,
    } = graceMasterPipeline;

`;

replaceBlock(
    '    const graceAndSummoning = useExecutionDashboardGraceAndSummoning({',
    '    // ===========================\n    // FINANCIAL CENTER ACCORDION & TABS STATE',
    graceReplacement,
);

const persistReplacement = `    const persistHandlerPipeline = useExecutionDashboardCorePersistHandlerPipeline({
        effectiveDebtors,
        financialPrincipalAmount,
        financialLawyerFeesAmount,
        claimType,
        isNonFinancialClaim,
        debtorBrowserTabsMode,
        effectiveFollowupDebtorEntry,
        activeWorkspaceDebtorForFollowup,
        executionData,
        executionId,
        decisionsReloadEpoch,
        isEvictionExecutionModule,
        unifiedCollectionApproved,
        notificationCount,
        forcedAttendanceIssued,
        coercionOrchestrator,
        isEvictionGraceExpiredNow,
        isGracePeriodExpiredNow,
        debtorNotificationDate,
        manualGraceCalendarExtra,
        lawyerStartedPostNoticeExecution,
        noticeVoluntaryPeriodEndOptimistic,
        voluntaryEndOptimistic,
        isEvictionGraceEffectivelyExpired,
        activeCoerciveActions,
        activeDebtorNoticeScope,
        debtorSummonsMarkerLocal,
        monetaryExecutionStrictPathFlag,
        isAlimonyClaim,
        executionExtras,
        unifiedSummonsTargetDebtorKey,
        activeDebtorIsDeceased,
        primaryDebtorKeyResolved,
        debtorNotifiedForEvictionGrace,
        remaining,
        daysSinceNoticeCalculated,
        executionFeeInjected,
        showToast,
        statuteStatus,
        showStatuteWarning,
        setShowStatuteWarning,
        lastActionDate,
        timelineEvents,
        caseNotesLog,
        caseTasksPending,
        financialLedger,
        gracePeriodActive,
        gracePeriodEnded,
        seizedAssets,
        seizureDraftsByDecisionId,
        realEstateSeizureAssets,
        debtorEvaded,
        arrestWarrantUnlocked,
        creditorAttended,
        executionPaused,
        paidDebt,
        paidCourtFees,
        paidDirectorateFees,
        paidClientFees,
        earnerFeeCollectionSm,
        followupOrchestrator,
        file,
        currentFileId,
        isMaritalFurnitureClaim,
        nextTimelineId,
        timelineEventsRef,
        persistExecutionMergeRef,
        executionFileSnapshotRef,
        setShowDecisionsModal,
        setCaseTasksPending,
        setTimelineEvents,
        setExecutionReportPrompt,
        setJudicialCustodianModalCtx,
        setJudicialCustodianModalOpen,
        setCaseNotesLog,
        decisionsStorageExecutionId,
        openBreakInventoryCompletion,
        openJudicialCustodianCompletion,
        isUnifiedTabActive,
        unifiedTabId,
        onUpdate,
        executionDataRef,
        seizureDraftsByDecisionIdRef,
        setExecutionStorageTick,
        showExecutionTrashModal,
        setShowExecutionTrashModal,
        caseNotesLogRef,
        caseTasksPendingRef,
        setPermanentDeleteTimelineId,
        viewExecutionData,
        isHistoricalMode,
        activeSubFileId,
        parentDossierId,
        setSeizureDraftsByDecisionId,
        seizedAssetsSnapshotRef,
        maritalFurnitureItemsForFollowup,
        setActiveCoerciveActions,
    });

    const {
        debtorSummonsProfileBundle,
        debtorOccupation,
        isDebtorGovernmentEmployee,
        isDebtorFreelancer,
        isDebtorRetired,
        debtorSummonsProfile,
        followupDebtorSummonsProfile,
        followupIsDebtorGovernmentEmployee,
        followupIsDebtorRetired,
        showSalaryCaptureForEmployee,
        subsequentNoticeFlow,
        earnerForcedActionUnlocked,
        followupEarnerForcedActionUnlocked,
        baseSubsequentNoticeUnlocked,
        evictionSubsequentNoticeUnlocked,
        subsequentNoticeUnlocked,
        anyExecutorDecisionResolvedForMemoBadge,
        primaryDebtorTaklifActive,
        primaryMemoNoticeBadge,
        primaryDebtorNoticeYmdResolved,
        showDebtorUnservedMemoBadge,
        primaryDebtorAbsenceBadge,
        showDebtorSummonsAttendanceBadge,
        noticeKindGoalStrictBinding,
        employeeAssignmentTabEnabled,
        resolvedEmployeeSummonsAssignment,
        showEmployeeAssignmentCoerciveBlock,
        employeeFinancialSalaryOnlyCoercive,
        monetaryCoerciveLimitedOnly,
        followupEmployeeFinancialSalaryOnlyCoercive,
        followupMonetaryCoerciveLimitedOnly,
        followupGarnishmentAmountPreview,
        saveExecutionData,
        executorApprovalActions,
        pushSeizureAuctionCalendarAppointment,
        pendingExecutorOpeners,
        tryOpenPendingBreakInventoryLedger,
        tryOpenPendingCustodianDetails,
        persistExecutionMergeBinding,
        persistExecutionMerge,
        trashAndPinsHandlers,
        timelineEditDraft,
        setTimelineEditDraft,
        moveTimelineEventToTrash,
        toggleTimelineEventPin,
        requestEditTimelineEvent,
        restoreTimelineEventFromTrash,
        permanentlyDeleteTimelineEvent,
        moveCaseNoteToTrash,
        moveCaseTaskToTrash,
        toggleCaseNotePin,
        toggleCaseTaskPin,
        saveTimelineEditDraft,
        restoreCaseNoteFromTrash,
        permanentlyDeleteCaseNote,
        restoreCaseTaskFromTrash,
        permanentlyDeleteCaseTask,
        partyEditWorkflow,
        editPartyTarget,
        setEditPartyTarget,
        partyEditDraft,
        setPartyEditDraft,
        partyEditHeirDeleteConfirmIdx,
        setPartyEditHeirDeleteConfirmIdx,
        heirsQuickView,
        setHeirsQuickView,
        openEditParty,
        buildPartyHeirsRows,
        openHeirsQuickView,
        savePartyEditDraft,
        removeHeirFromPartyEditDraftAtIndex,
        togglePartyEditHeirClient,
    } = persistHandlerPipeline;

`;

replaceBlock(
    '    const debtorSummonsProfileBundle = useDebtorSummonsProfile(',
    '\n\n\n\n    const specificDeliveryConvertedAmount =',
    persistReplacement,
);

const runtimeReplacement = `    const coreRuntimeVars = buildExecutionDashboardCoreRuntimeVars({
        ...workspacePipeline,
        ...followupDebtor,
        ...claimFinancialLedger,
        ...graceMasterPipeline,
        ...persistHandlerPipeline,
        EVICTION_WORKFLOW_BY_ACTION_ID,
        READY_FOR_COERCIVE,
        specificDeliveryConvertedAmount,
        specificDeliveryFinancialized,
        directorate,
        fileNumber,
        fileYear,
        executionNumber,
        executionYear,
        executionType,
        docType,
        docNumber,
        claimType,
        judgmentDate,
        classification,
        creditors,
        debtors,
        totalAmount,
        debtAmount,
        lawyerFeesAmount,
        executionFee,
        clientFeesAmount,
        courtFees,
        directorateFees,
        monthlyAlimony,
        alimony,
        accumulatedAlimony,
        initiator,
        representedParty,
        daysSinceNotice,
        isAlimonyCase,
        lastPaymentDate,
        shariaDeedNumber,
        shariaRegisterNumber,
        shariaIssueDate,
        shariaIssuingCourt,
        chequeBankName,
        chequeIssueDate,
        chequeNumber,
        status,
        createdAt,
        includesSleepover,
        visitationChildrenNames,
        custodyWardNames,
        evictionPropertyNumber,
        evictionPropertyDistrict,
        evictionPropertyTypeField,
        evictionFullAddressField,
        evictionPremisesUseRaw,
        visitChildNames,
        custodyWardNamesList,
        evictionPremisesUseResolved,
        evictionCaseExpensesSum,
        creditorExtraMinorNames,
        creditorExtraMinorLabel,
        classificationDisplay,
        claimTypeArabicDisplay,
        lawyerStartedPostNoticeExecution,
        judgmentDateDisplay,
        headerFields,
        showJudgmentMeta,
        parentHeaderFields,
        parentClassificationDisplay,
        parentClaimTypeArabicDisplay,
        parentJudgmentDateDisplay,
        parentShowJudgmentMeta,
        currentFileId,
        file,
        executionData,
        executionDataId,
        executionDataRef,
        executionId,
        onUpdate,
        onClose,
        viewExecutionData,
        currentFile,
        activeSubFileId,
        activeTabId,
        setActiveTabId,
        childDossiers,
        subFiles,
        hasChildDossiers,
        linkedDossierToView,
        setLinkedDossierToView,
        dossierFileKey,
        parentDossierId,
        parentExecutionFile,
        decisionsStorageExecutionId,
        showDecisionsModal,
        setShowDecisionsModal,
        setExecutionStorageTick,
        bindHorizontalWheelToScroll,
        buildDebtorNoticePatchForKey,
        getDebtorNoticeStateForKey,
        getLocalTodayYmd,
        gracePeriodStart,
        hasActiveResidentialEvictionGrace,
        isExecutorRowEffectivelyApproved,
        isInabaActive,
        isUnifiedTabActive,
        appendEvictionExecutorRequest,
        appendEvictionProcedure,
        reconcileDossierLifecycle,
        resolveCalendarUserId,
        readExecutorDecisionsArray,
        mergeSimilarRecentTimelineEvent,
        syncRollingCalendarSessions,
        dismissDebtorAbsenceBadge,
        setShowCoerciveModal,
        showCoerciveModal,
        showExtraCreditors,
        showExtraDebtors,
        setShowExtraCreditors,
        setShowExtraDebtors,
        toggleHeaderExpanded,
        isHeaderExpanded,
        useExecutionDashboardStore,
        voiceUserId,
        partyBadgesExecutionId,
        daysRemaining,
        daysRemainingUntilDeadline,
        debtorEmploymentToggleMenuLabel,
        isDebtorRowEmployee,
        publicationNoticeDeadlineYmd,
        inabaCorrespondenceLog,
        inabaTargets,
        guarantorFollowupAwaitingDetailsSave,
        total_execution_expenses,
        parsedLawyerFees,
        parsedClientFees,
        parsedCourtFees,
        parsedDirectorateFees,
        executionAppealBanner,
        executionFeeInjected,
        vacateDeadline,
        residentialGracePeriodSaved,
        evictionGraceHidden,
        evictionGracePinned,
        setEvictionGraceHidden,
        isAssignmentDeadlinePassed,
        debtorSummonsMarkerLocal,
        setDebtorSummonsMarkerLocal,
        getMilestoneTimelineSnapshot,
        openBreakInventoryCompletion,
        openJudicialCustodianCompletion,
        openFinancialHubLedger,
        setShowNotesModal,
        setShowPaymentModal,
        setShowCoerciveActionForm,
        setShowUnifiedSummonsModal,
        setSummonsMarkerPopoverOpen,
        setExecutionMemoBadgePopoverOpen,
        setSummonsPurposeDraft,
        setShowExecutionTrashModal,
        setIsPaused,
        setPauseReason,
        setManualGraceCalendarExtra,
        followupModalDebtorIsDeceased,
        followupModalDebtorIsEmployee,
        modalKasabTerminationEmphasis,
        modalResolvedEmployeeSummonsAssignment,
        modalShowEmployeeAssignmentCoerciveBlock,
        appealPerspective,
        hideCoerciveTabsForDebtorAgent,
        hideExecutiveDetentionJudgeCard,
        shouldShowGuarantorExternalHub,
        kasabTerminationEmphasis,
        activeDebtorIsLegalEntity,
        isHistoricalMode,
        isRepresentingDebtor,
        isPersonalStatusExecutionClaim,
        timelineFilterOptions,
        timelineDebtorMetadata,
        movableSeizureRegistryAssets,
        realEstateSeizureRegistryAssets,
        salarySeizureRegistryAssets,
        thirdPartySeizureRegistryAssets,
        thirdPartySeizureAssets,
        thirdPartySeizuresUi,
        editingNoteId,
        dockPinnedNotes,
        dockPinnedTasks,
        financialStatus,
    });

`;

replaceBlock('    const coreRuntimeVars = {', '    const handlerClusterCore = buildHandlerClusterCoreInput(coreRuntimeVars);', runtimeReplacement);

fs.writeFileSync(corePath, core, 'utf8');
console.log('patch-slice27 applied');
console.log('lines:', core.split('\n').length);
