import React, { useMemo } from 'react';
import { useAuthUser } from '@/app/context/AuthContext';
import type { ActiveOrderFileProps } from './types';
import { formatDateText, formatDateTimeText, formatRequestNumberText } from './utils/formatters';
import { todayYmd } from './utils/ymd';
import { ConfirmDialogPortal } from './components/ConfirmDialogPortal';
import { ActiveOrderFileView } from './layout/ActiveOrderFileView';
import { useOrderFilePersist } from './hooks/useOrderFilePersist';
import { useOrderFileConfirm } from './hooks/useOrderFileConfirm';
import { useOrderFileWorkspace } from './hooks/useOrderFileWorkspace';
import { useOrderFileMetaPartyEdit } from './hooks/useOrderFileMetaPartyEdit';
import { useOrderFileHydrate } from './hooks/useOrderFileHydrate';
import { useOrderFileCasePathway } from './hooks/useOrderFileCasePathway';
import { useOrderFilePartyWorkspace } from './hooks/useOrderFilePartyWorkspace';
import { useOrderFileLifecycleDerived } from './hooks/useOrderFileLifecycleDerived';
import { useOrderFileLifecycleActions } from './hooks/useOrderFileLifecycleActions';
import { useOrderFileLifecycleState } from './hooks/useOrderFileLifecycleState';
import { buildLifecyclePanelProps } from './layout/buildLifecyclePanelProps';
import { useDecisionNotificationSubmit } from './hooks/useDecisionNotificationSubmit';

/**
 * 📂 Dashboard الأمر الولائي - Active State Order File Dashboard
 * 
 * لوحة تحكم شاملة لإدارة دورة حياة الأمر الولائي (Ex Parte Secret Order)
 * تصميم Royal UI متقدم مع نظام إدارة الحالات والإشعارات القانونية
 */

export const Dashboard_Active_Order_File: React.FC<ActiveOrderFileProps> = ({ fileData, onClose, onCaseUpdated }) => {
    const fd = fileData as Record<string, unknown>;
    const authUser = useAuthUser();
    const userId = authUser?.id || 'dev-user-uuid-1';
    const caseId = typeof fd?.id === 'string' ? fd.id : null;
    const defaultDeadlineDays = fd?.type === 'urgent_action' ? 7 : 3;

    const {
        caseData,
        setCaseData,
        fileStatus,
        setFileStatus,
        isSecretMode,
        setIsSecretMode,
        hasIntervention,
        setHasIntervention,
        activeLifecycleStep,
        setActiveLifecycleStep,
        judgeDecision,
        setJudgeDecision,
        executionData,
        setExecutionData,
        grievanceData,
        setGrievanceData,
        phase2FirstHearingDate,
        setPhase2FirstHearingDate,
        grievanceLegalEndDate,
        setGrievanceLegalEndDate,
        grievanceDecisionNotificationConfirmed,
        setGrievanceDecisionNotificationConfirmed,
        grievancePetitionNotificationDate,
        setGrievancePetitionNotificationDate,
        grievancePetitionNotificationConfirmed,
        setGrievancePetitionNotificationConfirmed,
        decisionNotificationModalOpen,
        setDecisionNotificationModalOpen,
        grievanceTimingConfirmed,
        setGrievanceTimingConfirmed,
        grievanceDetailsConfirmed,
        setGrievanceDetailsConfirmed,
        grievanceExpiredConfirmed,
        setGrievanceExpiredConfirmed,
        grievanceDecision,
        setGrievanceDecision,
        cassationData,
        setCassationData,
        cassationDecision,
        setCassationDecision,
        cassationExpiredConfirmed,
        setCassationExpiredConfirmed,
        guaranteeSubmitted,
        setGuaranteeSubmitted,
        guaranteeDetails,
        setGuaranteeDetails,
        hearings,
        setHearings,
        hearingDraft,
        setHearingDraft,
        expertModule,
        setExpertModule,
        preDecisionClosed,
        setPreDecisionClosed,
        setExpectedDecisionDate,
        registrationData,
        setRegistrationData,
        caseEvents,
        setCaseEvents,
        caseNotes,
        setCaseNotes,
        caseAttachments,
        setCaseAttachments,
        caseFollowups,
        setCaseFollowups,
        editJudge,
        setEditJudge,
        editExecution,
        setEditExecution,
        editRejectionNotice,
        setEditRejectionNotice,
        editGrievance,
        setEditGrievance,
        editCassation,
        setEditCassation,
        judgeError,
        setJudgeError,
        executionError,
        setExecutionError,
        rejectionNoticeError,
        setRejectionNoticeError,
        grievanceError,
        setGrievanceError,
        grievanceDecisionError,
        setGrievanceDecisionError,
        cassationError,
        setCassationError,
        cassationDecisionError,
        setCassationDecisionError,
        hearingsError,
        setHearingsError,
        grievanceRef,
        cassationRef,
        grievanceTimingGateRef,
        grievanceOutcomeGateRef,
        grievanceHearingsGateRef,
        grievanceFinalGateRef,
        cassationFilingGateRef,
        cassationDecisionGateRef,
        pendingRegistrationSyncRef,
    } = useOrderFileLifecycleState({ fileData, defaultDeadlineDays });

    const todayYmdValue = todayYmd();
    const requestDateYmd = useMemo(() => {
        const raw = String(caseData?.requestDate ?? '').trim();
        return /^\d{4}-\d{2}-\d{2}$/.test(raw) ? raw : '';
    }, [caseData?.requestDate]);

    const { persistPatch, flushPersistPatch, persistAndMerge, appendCaseEvent } = useOrderFilePersist({
        caseId,
        userId,
        caseEvents,
        setCaseEvents,
        setCaseData,
        onCaseUpdated,
    });
    const { confirmDialog, requestConfirm, resolveConfirm } = useOrderFileConfirm();

    useOrderFileHydrate({
        caseId,
        userId,
        fileData,
        caseData,
        setters: {
            setCaseData,
            setHasIntervention,
            setFileStatus,
            setIsSecretMode,
            setActiveLifecycleStep,
            setJudgeDecision,
            setExecutionData,
            setGrievanceData,
            setGrievanceLegalEndDate,
            setGrievanceDecisionNotificationConfirmed,
            setGrievancePetitionNotificationDate,
            setGrievancePetitionNotificationConfirmed,
            setGrievanceTimingConfirmed,
            setGrievanceDetailsConfirmed,
            setPhase2FirstHearingDate,
            setGrievanceDecision,
            setCassationData,
            setCassationDecision,
            setGuaranteeSubmitted,
            setGuaranteeDetails,
            setHearings,
            setExpertModule,
            setPreDecisionClosed,
            setExpectedDecisionDate,
            setRegistrationData,
            setCaseEvents,
            setCaseNotes,
            setCaseAttachments,
            setCaseFollowups,
        },
    });

    const casePathway = useOrderFileCasePathway({
        caseData,
        fd,
        fileStatus,
        activeLifecycleStep,
        judgeDecision,
        grievanceDecision,
        hearings,
        preDecisionClosed,
    });
    const {
        statusConfig,
        requestTypeText,
        resolvedWorkspaceRequestType,
        isIqrarContext,
        procedureDetailsForPopover,
        partyLabel,
        oppositeRole,
        isUrgentLawsuit,
        isOrderOnPetition,
        isStateOrder,
        isUrgentJustice,
        showGrievanceStep,
        grievanceStepNumber,
        cassationStepNumber,
        showPreDecisionHearings,
        preDecisionTerminateExists,
        computedGrievanceFiledBy,
        computedCassationFiledBy,
    } = casePathway;

    const {
        party1Entries,
        party2Entries,
        isDefendantClient,
        defenderPhase1ReadOnly,
        defenderPhase2ReadOnly,
        khulasaText,
        guaranteeGateActive,
        isFinalityNoGrievance,
        isFinalityTerminatedRequest,
        isFinalized,
        workspaceHeaderTitle,
    } = useOrderFilePartyWorkspace({
        caseData,
        judgeDecision,
        guaranteeSubmitted,
        resolvedWorkspaceRequestType,
        isIqrarContext,
        isStateOrder,
        isOrderOnPetition,
        isUrgentLawsuit,
        isUrgentJustice,
    });

    const {
        partyEditTarget,
        partyEditForm,
        setPartyEditForm,
        isMetaEditOpen,
        metaEditForm,
        setMetaEditForm,
        openPartyEdit,
        closePartyEdit,
        savePartyEdit,
        openMetaEdit,
        closeMetaEdit,
        saveMetaEdit,
    } = useOrderFileMetaPartyEdit({
        caseData,
        party1Entries,
        party2Entries,
        persistAndMerge,
        appendCaseEvent,
    });

    const {
        newEventText,
        setNewEventText,
        newNoteText,
        setNewNoteText,
        newFollowupTitle,
        setNewFollowupTitle,
        newFollowupDate,
        setNewFollowupDate,
        attachmentsError,
        addManualEvent,
        addCaseNote,
        deleteCaseNote,
        addAttachmentFile,
        deleteAttachment,
        addFollowup,
        toggleFollowupCompleted,
        deleteFollowup,
        attachmentInputId,
        caseEventDayGroups,
    } = useOrderFileWorkspace({
        caseId,
        isFinalized,
        requestDateYmd,
        caseEvents,
        caseNotes,
        setCaseNotes,
        caseAttachments,
        setCaseAttachments,
        caseFollowups,
        setCaseFollowups,
        persistAndMerge,
        appendCaseEvent,
    });

    const lifecycleDerived = useOrderFileLifecycleDerived({
        caseData,
        judgeDecision,
        grievanceData,
        grievanceDecision,
        cassationData,
        cassationDecision,
        hearings,
        hearingDraft,
        expertModule,
        phase2FirstHearingDate,
        grievanceLegalEndDate,
        setGrievanceLegalEndDate,
        grievanceTimingConfirmed,
        grievanceDetailsConfirmed,
        grievanceExpiredConfirmed,
        cassationExpiredConfirmed,
        editGrievance,
        requestDateYmd,
        todayYmdValue,
        hasIntervention,
        isFinalized,
        isFinalityNoGrievance,
        defenderPhase2ReadOnly,
        showGrievanceStep,
        isIqrarContext,
        partyLabel,
        computedGrievanceFiledBy,
        computedCassationFiledBy,
        showPreDecisionHearings,
    });

    const lifecycleActions = useOrderFileLifecycleActions({
        caseId,
        caseData,
        setCaseData,
        onCaseUpdated,
        todayYmdValue,
        requestDateYmd,
        isFinalized,
        fileStatus,
        setFileStatus,
        isSecretMode,
        setIsSecretMode,
        hasIntervention,
        setHasIntervention,
        activeLifecycleStep,
        setActiveLifecycleStep,
        judgeDecision,
        setJudgeDecision,
        executionData,
        setExecutionData,
        grievanceData,
        setGrievanceData,
        phase2FirstHearingDate,
        setPhase2FirstHearingDate,
        grievanceLegalEndDate,
        setGrievanceLegalEndDate,
        grievanceTimingConfirmed,
        setGrievanceTimingConfirmed,
        grievanceDetailsConfirmed,
        setGrievanceDetailsConfirmed,
        grievanceExpiredConfirmed,
        setGrievanceExpiredConfirmed,
        grievanceDecision,
        setGrievanceDecision,
        cassationData,
        setCassationData,
        cassationDecision,
        setCassationDecision,
        guaranteeSubmitted,
        setGuaranteeSubmitted,
        guaranteeDetails,
        hearings,
        setHearings,
        setPreDecisionClosed,
        hearingDraft,
        setHearingDraft,
        expertModule,
        setExpertModule,
        registrationData,
        setRegistrationData,
        pendingRegistrationSyncRef,
        editJudge,
        setEditJudge,
        editExecution,
        setEditExecution,
        editRejectionNotice,
        setEditRejectionNotice,
        editGrievance,
        setEditGrievance,
        editCassation,
        setEditCassation,
        setJudgeError,
        setExecutionError,
        setRejectionNoticeError,
        setGrievanceError,
        setGrievanceDecisionError,
        setCassationError,
        setCassationDecisionError,
        setHearingsError,
        persistPatch,
        flushPersistPatch,
        persistAndMerge,
        appendCaseEvent,
        requestConfirm,
        showGrievanceStep,
        showPreDecisionHearings,
        preDecisionTerminateExists,
        isIqrarContext,
        isStateOrder,
        isCaseTerminated: lifecycleDerived.isCaseTerminated,
        hasSessions: lifecycleDerived.hasSessions,
        grievanceLegalEndDateChronologyError: lifecycleDerived.grievanceLegalEndDateChronologyError,
        grievanceExpiredCanClose: lifecycleDerived.grievanceExpiredCanClose,
        grievanceClosingHearingExists: lifecycleDerived.grievanceClosingHearingExists,
        grievanceFilingDateChronologyError: lifecycleDerived.grievanceFilingDateChronologyError,
        grievanceFirstHearingDateChronologyError: lifecycleDerived.grievanceFirstHearingDateChronologyError,
        grievanceDecisionDateChronologyError: lifecycleDerived.grievanceDecisionDateChronologyError,
        judgeDecisionDateChronologyError: lifecycleDerived.judgeDecisionDateChronologyError,
        cassationFilingDateChronologyError: lifecycleDerived.cassationFilingDateChronologyError,
        cassationDecisionDateError: lifecycleDerived.cassationDecisionDateError,
        cassationFilingDetailsComplete: lifecycleDerived.cassationFilingDetailsComplete,
        phase1NewSessionMinYmd: lifecycleDerived.phase1NewSessionMinYmd,
        phase2NewSessionMinYmd: lifecycleDerived.phase2NewSessionMinYmd,
        effectiveJudgeDecisionDate: lifecycleDerived.effectiveJudgeDecisionDate,
        effectiveRejectionNotificationDate: lifecycleDerived.effectiveRejectionNotificationDate,
        grievanceTimingGateReady: lifecycleDerived.grievanceTimingGateReady,
        grievanceFilingMinYmd: lifecycleDerived.grievanceFilingMinYmd,
        grievanceFirstHearingMinYmd: lifecycleDerived.grievanceFirstHearingMinYmd,
        oppositeRole,
        partyLabel,
        computedGrievanceFiledBy,
        computedCassationFiledBy,
        phase2ActiveDate: lifecycleDerived.phase2ActiveDate,
        grievanceWizardInputsLocked: lifecycleDerived.grievanceWizardInputsLocked,
        grievanceProceedingsClosed: lifecycleDerived.grievanceProceedingsClosed,
        cassationExpiredCanClose: lifecycleDerived.cassationExpiredCanClose,
        cassationExpiredConfirmed,
        defaultDeadlineDays,
        setGrievanceDecisionNotificationConfirmed,
        setGrievancePetitionNotificationDate,
        setGrievancePetitionNotificationConfirmed,
    });

    const lifecyclePanelProps = buildLifecyclePanelProps({
        pathway: casePathway,
        derived: lifecycleDerived,
        actions: lifecycleActions,
        activeLifecycleStep,
        caseData,
        cassationData,
        cassationDecision,
        cassationDecisionError,
        cassationDecisionGateRef,
        cassationError,
        cassationExpiredConfirmed,
        cassationFilingGateRef,
        cassationRef,
        defenderPhase1ReadOnly,
        defenderPhase2ReadOnly,
        editCassation,
        editGrievance,
        editJudge,
        fileStatus,
        grievanceData,
        grievanceDecision,
        grievanceDecisionError,
        grievanceDecisionNotificationConfirmed,
        grievanceError,
        grievanceExpiredConfirmed,
        grievanceFinalGateRef,
        grievanceHearingsGateRef,
        grievanceLegalEndDate,
        grievanceOutcomeGateRef,
        grievanceRef,
        grievanceTimingConfirmed,
        guaranteeDetails,
        guaranteeGateActive,
        guaranteeSubmitted,
        hasIntervention,
        hearingDraft,
        hearingsError,
        isDefendantClient,
        isFinalityNoGrievance,
        isFinalityTerminatedRequest,
        isFinalized,
        judgeDecision,
        judgeError,
        phase2FirstHearingDate,
        setActiveLifecycleStep,
        setCassationData,
        setCassationDecision,
        setCassationExpiredConfirmed,
        setDecisionNotificationModalOpen,
        setEditCassation,
        setEditGrievance,
        setGrievanceData,
        setGrievanceDecision,
        setGrievanceDetailsConfirmed,
        setGrievanceExpiredConfirmed,
        setGrievanceLegalEndDate,
        setGuaranteeDetails,
        setGuaranteeSubmitted,
        setHearingDraft,
        setJudgeDecision,
        setPhase2FirstHearingDate,
    });

    const submitDecisionNotification = useDecisionNotificationSubmit({
        judgeDecision,
        showGrievanceStep: casePathway.showGrievanceStep,
        setGrievanceData,
        setGrievanceDecisionNotificationConfirmed,
        setGrievanceLegalEndDate,
        persistAndMerge,
        appendCaseEvent,
    });

    const confirmPortal = (
        <ConfirmDialogPortal
            open={confirmDialog.open}
            message={confirmDialog.message}
            onCancel={() => resolveConfirm(false)}
            onConfirm={() => resolveConfirm(true)}
        />
    );

    return (
        <ActiveOrderFileView
            onClose={onClose}
            confirmPortal={confirmPortal}
            lifecyclePanelProps={lifecyclePanelProps}
            decisionNotificationModal={{
                isOpen: decisionNotificationModalOpen,
                onClose: () => setDecisionNotificationModalOpen(false),
                caseName: String(caseData?.specificActionType ?? caseData?.actionPath ?? requestTypeText ?? '').trim() || '—',
                minActionDate: lifecycleDerived.decisionNotificationQuickLogMinYmd || undefined,
                onSubmit: ({ actionDate }) => {
                    setDecisionNotificationModalOpen(false);
                    submitDecisionNotification(actionDate);
                },
            }}
            metaEdit={{
                open: isMetaEditOpen,
                isIqrarContext,
                khulasaText,
                metaEditForm,
                setMetaEditForm,
                onClose: closeMetaEdit,
                onSave: saveMetaEdit,
            }}
            partyEdit={{
                partyEditTarget,
                partyEditForm,
                setPartyEditForm,
                onClose: closePartyEdit,
                onSave: savePartyEdit,
            }}
            header={{
                workspaceHeaderTitle,
                requestNumberText: caseData?.requestNumber
                    ? formatRequestNumberText(caseData.requestNumber, caseData?.requestDate)
                    : '',
                procedureDetailsForPopover,
                courtName: String(caseData?.courtName ?? ''),
                isFinalized,
                isIqrarContext,
                statusConfig,
                nextHearingDate: String(lifecycleDerived.nextHearingDate ?? ''),
                reportDueSoon: lifecycleDerived.reportDueSoon,
                formatDateText,
                onOpenMetaEdit: openMetaEdit,
            }}
            archive={
                isFinalized
                    ? {
                          isIqrarContext,
                          archiveSummaryText: lifecycleDerived.archiveSummaryText,
                          archivedAt: (caseData as any)?.archivedAt,
                          formatDateTimeText,
                      }
                    : undefined
            }
            parties={{
                party1Entries,
                party2Entries,
                procedureType: String(caseData?.specificActionType ?? ''),
                isFinalized,
                onEditParty: openPartyEdit,
            }}
            adminWorkspace={{
                isIqrarContext,
                isFinalized,
                newFollowupTitle,
                setNewFollowupTitle,
                newFollowupDate,
                setNewFollowupDate,
                requestDateYmd,
                addFollowup,
                caseFollowups,
                todayYmdValue,
                toggleFollowupCompleted,
                deleteFollowup,
                caseEvents,
                newEventText,
                setNewEventText,
                addManualEvent,
                caseEventDayGroups,
                newNoteText,
                setNewNoteText,
                addCaseNote,
                caseNotes,
                deleteCaseNote,
                attachmentsError,
                attachmentInputId,
                addAttachmentFile,
                caseAttachments,
                deleteAttachment,
            }}
        />
    );
};