import { buildLifecyclePanelProps } from '../layout/buildLifecyclePanelProps';
import { useOrderFileLifecycleDerived } from './useOrderFileLifecycleDerived';
import { useOrderFileLifecycleActions } from './useOrderFileLifecycleActions';
import { useDecisionNotificationSubmit } from './useDecisionNotificationSubmit';
import type { useOrderFileLifecycleState } from './useOrderFileLifecycleState';
import type { useActiveOrderFileWorkspaceCluster } from './useActiveOrderFileWorkspaceCluster';

type LifecycleState = ReturnType<typeof useOrderFileLifecycleState>;
type WorkspaceCluster = ReturnType<typeof useActiveOrderFileWorkspaceCluster>;

export type ActiveOrderFileLifecycleClusterInput = {
    caseId: string | null;
    lifecycleState: LifecycleState;
    workspace: WorkspaceCluster;
    defaultDeadlineDays: number;
    onCaseUpdated: ((patch: Record<string, unknown>) => void) | undefined;
};

export function useActiveOrderFileLifecycleCluster(input: ActiveOrderFileLifecycleClusterInput) {
    const { caseId, lifecycleState, workspace, defaultDeadlineDays, onCaseUpdated } = input;
    const { casePathway, partyWorkspaceBundle, todayYmdValue, requestDateYmd, persistPatch, flushPersistPatch, persistAndMerge, appendCaseEvent, requestConfirm, caseData } =
        workspace;

    const {
        setCaseData,
        fileStatus,
        setFileStatus,
        isSecretMode,
        setIsSecretMode,
        hasIntervention,
        setHasIntervention,
        activeLifecycleStep,
        setActiveLifecycleStep,
        judgeDecision,
        setJudgeDecision,
        executionData,
        setExecutionData,
        grievanceData,
        setGrievanceData,
        phase2FirstHearingDate,
        setPhase2FirstHearingDate,
        grievanceLegalEndDate,
        setGrievanceLegalEndDate,
        grievanceDecisionNotificationConfirmed,
        setGrievanceDecisionNotificationConfirmed,
        grievancePetitionNotificationDate,
        setGrievancePetitionNotificationDate,
        grievancePetitionNotificationConfirmed,
        setGrievancePetitionNotificationConfirmed,
        grievanceTimingConfirmed,
        setGrievanceTimingConfirmed,
        grievanceDetailsConfirmed,
        setGrievanceDetailsConfirmed,
        grievanceExpiredConfirmed,
        setGrievanceExpiredConfirmed,
        grievanceDecision,
        setGrievanceDecision,
        cassationData,
        setCassationData,
        cassationDecision,
        setCassationDecision,
        cassationExpiredConfirmed,
        setCassationExpiredConfirmed,
        guaranteeSubmitted,
        setGuaranteeSubmitted,
        guaranteeDetails,
        setGuaranteeDetails,
        hearings,
        setHearings,
        hearingDraft,
        setHearingDraft,
        expertModule,
        setExpertModule,
        preDecisionClosed,
        setPreDecisionClosed,
        registrationData,
        setRegistrationData,
        pendingRegistrationSyncRef,
        editJudge,
        setEditJudge,
        editExecution,
        setEditExecution,
        editRejectionNotice,
        setEditRejectionNotice,
        editGrievance,
        setEditGrievance,
        editCassation,
        setEditCassation,
        setJudgeError,
        setExecutionError,
        setRejectionNoticeError,
        setGrievanceError,
        setGrievanceDecisionError,
        setCassationError,
        setCassationDecisionError,
        setHearingsError,
        grievanceRef,
        cassationRef,
        grievanceTimingGateRef,
        grievanceOutcomeGateRef,
        grievanceHearingsGateRef,
        grievanceFinalGateRef,
        cassationFilingGateRef,
        cassationDecisionGateRef,
        decisionNotificationModalOpen,
        setDecisionNotificationModalOpen,
    } = lifecycleState;

    const {
        oppositeRole,
        partyLabel,
        showGrievanceStep,
        showPreDecisionHearings,
        preDecisionTerminateExists,
        isIqrarContext,
        isStateOrder,
        computedGrievanceFiledBy,
        computedCassationFiledBy,
    } = casePathway;

    const {
        defenderPhase1ReadOnly,
        defenderPhase2ReadOnly,
        guaranteeGateActive,
        isFinalityNoGrievance,
        isFinalityTerminatedRequest,
        isFinalized,
        isDefendantClient,
    } = partyWorkspaceBundle;

    const lifecycleDerived = useOrderFileLifecycleDerived({
        caseData,
        judgeDecision,
        grievanceData,
        grievanceDecision,
        cassationData,
        cassationDecision,
        hearings,
        hearingDraft,
        expertModule,
        phase2FirstHearingDate,
        grievanceLegalEndDate,
        setGrievanceLegalEndDate,
        grievanceTimingConfirmed,
        grievanceDetailsConfirmed,
        grievanceExpiredConfirmed,
        cassationExpiredConfirmed,
        editGrievance,
        requestDateYmd,
        todayYmdValue,
        hasIntervention,
        isFinalized,
        isFinalityNoGrievance,
        defenderPhase2ReadOnly,
        showGrievanceStep,
        isIqrarContext,
        partyLabel,
        computedGrievanceFiledBy,
        computedCassationFiledBy,
        showPreDecisionHearings,
        fileStatus,
    });

    const lifecycleActions = useOrderFileLifecycleActions({
        caseId,
        caseData,
        setCaseData,
        onCaseUpdated,
        todayYmdValue,
        requestDateYmd,
        isFinalized,
        fileStatus,
        setFileStatus,
        isSecretMode,
        setIsSecretMode,
        hasIntervention,
        setHasIntervention,
        activeLifecycleStep,
        setActiveLifecycleStep,
        judgeDecision,
        setJudgeDecision,
        executionData,
        setExecutionData,
        grievanceData,
        setGrievanceData,
        phase2FirstHearingDate,
        setPhase2FirstHearingDate,
        grievanceLegalEndDate,
        setGrievanceLegalEndDate,
        grievanceTimingConfirmed,
        setGrievanceTimingConfirmed,
        grievanceDetailsConfirmed,
        setGrievanceDetailsConfirmed,
        grievanceExpiredConfirmed,
        setGrievanceExpiredConfirmed,
        grievanceDecision,
        setGrievanceDecision,
        cassationData,
        setCassationData,
        cassationDecision,
        setCassationDecision,
        guaranteeSubmitted,
        setGuaranteeSubmitted,
        guaranteeDetails,
        hearings,
        setHearings,
        setPreDecisionClosed,
        hearingDraft,
        setHearingDraft,
        expertModule,
        setExpertModule,
        registrationData,
        setRegistrationData,
        pendingRegistrationSyncRef,
        editJudge,
        setEditJudge,
        editExecution,
        setEditExecution,
        editRejectionNotice,
        setEditRejectionNotice,
        editGrievance,
        setEditGrievance,
        editCassation,
        setEditCassation,
        setJudgeError,
        setExecutionError,
        setRejectionNoticeError,
        setGrievanceError,
        setGrievanceDecisionError,
        setCassationError,
        setCassationDecisionError,
        setHearingsError,
        persistPatch,
        flushPersistPatch,
        persistAndMerge,
        appendCaseEvent,
        requestConfirm,
        showGrievanceStep,
        showPreDecisionHearings,
        preDecisionTerminateExists,
        isIqrarContext,
        isStateOrder,
        isCaseTerminated: lifecycleDerived.isCaseTerminated,
        hasSessions: lifecycleDerived.hasSessions,
        grievanceLegalEndDateChronologyError: lifecycleDerived.grievanceLegalEndDateChronologyError,
        grievanceExpiredCanClose: lifecycleDerived.grievanceExpiredCanClose,
        grievanceClosingHearingExists: lifecycleDerived.grievanceClosingHearingExists,
        grievanceFilingDateChronologyError: lifecycleDerived.grievanceFilingDateChronologyError,
        grievanceFirstHearingDateChronologyError: lifecycleDerived.grievanceFirstHearingDateChronologyError,
        grievanceDecisionDateChronologyError: lifecycleDerived.grievanceDecisionDateChronologyError,
        judgeDecisionDateChronologyError: lifecycleDerived.judgeDecisionDateChronologyError,
        cassationFilingDateChronologyError: lifecycleDerived.cassationFilingDateChronologyError,
        cassationDecisionDateError: lifecycleDerived.cassationDecisionDateError,
        cassationFilingDetailsComplete: lifecycleDerived.cassationFilingDetailsComplete,
        phase1NewSessionMinYmd: lifecycleDerived.phase1NewSessionMinYmd,
        phase2NewSessionMinYmd: lifecycleDerived.phase2NewSessionMinYmd,
        effectiveJudgeDecisionDate: lifecycleDerived.effectiveJudgeDecisionDate,
        effectiveRejectionNotificationDate: lifecycleDerived.effectiveRejectionNotificationDate,
        grievanceTimingGateReady: lifecycleDerived.grievanceTimingGateReady,
        grievanceFilingMinYmd: lifecycleDerived.grievanceFilingMinYmd,
        grievanceFirstHearingMinYmd: lifecycleDerived.grievanceFirstHearingMinYmd,
        oppositeRole,
        partyLabel,
        computedGrievanceFiledBy,
        computedCassationFiledBy,
        phase2ActiveDate: lifecycleDerived.phase2ActiveDate,
        grievanceWizardInputsLocked: lifecycleDerived.grievanceWizardInputsLocked,
        grievanceProceedingsClosed: lifecycleDerived.grievanceProceedingsClosed,
        cassationExpiredCanClose: lifecycleDerived.cassationExpiredCanClose,
        cassationExpiredConfirmed,
        defaultDeadlineDays,
        setGrievanceDecisionNotificationConfirmed,
        setGrievancePetitionNotificationDate,
        setGrievancePetitionNotificationConfirmed,
    });

    const lifecyclePanelProps = buildLifecyclePanelProps({
        pathway: casePathway,
        derived: lifecycleDerived,
        actions: lifecycleActions,
        activeLifecycleStep,
        caseData,
        cassationData,
        cassationDecision,
        cassationDecisionError: lifecycleState.cassationDecisionError,
        cassationDecisionGateRef,
        cassationError: lifecycleState.cassationError,
        cassationExpiredConfirmed,
        cassationFilingGateRef,
        cassationRef,
        defenderPhase1ReadOnly,
        defenderPhase2ReadOnly,
        editCassation,
        editGrievance,
        editJudge,
        fileStatus,
        grievanceData,
        grievanceDecision,
        grievanceDecisionError: lifecycleState.grievanceDecisionError,
        grievanceDecisionNotificationConfirmed,
        grievanceError: lifecycleState.grievanceError,
        grievanceExpiredConfirmed,
        grievanceFinalGateRef,
        grievanceHearingsGateRef,
        grievanceLegalEndDate,
        grievanceOutcomeGateRef,
        grievanceRef,
        grievanceTimingConfirmed,
        guaranteeDetails,
        guaranteeGateActive,
        guaranteeSubmitted,
        hasIntervention,
        hearingDraft,
        hearingsError: lifecycleState.hearingsError,
        isDefendantClient,
        isFinalityNoGrievance,
        isFinalityTerminatedRequest,
        isFinalized,
        judgeDecision,
        judgeError: lifecycleState.judgeError,
        phase2FirstHearingDate,
        setActiveLifecycleStep,
        setCassationData,
        setCassationDecision,
        setCassationExpiredConfirmed,
        setDecisionNotificationModalOpen,
        setEditCassation,
        setEditGrievance,
        setGrievanceData,
        setGrievanceDecision,
        setGrievanceDetailsConfirmed,
        setGrievanceExpiredConfirmed,
        setGrievanceLegalEndDate,
        setGuaranteeDetails,
        setGuaranteeSubmitted,
        setHearingDraft,
        setJudgeDecision,
        setPhase2FirstHearingDate,
    });

    const submitDecisionNotification = useDecisionNotificationSubmit({
        judgeDecision,
        showGrievanceStep: casePathway.showGrievanceStep,
        setGrievanceData,
        setGrievanceDecisionNotificationConfirmed,
        setGrievanceLegalEndDate,
        persistAndMerge,
        appendCaseEvent,
    });

    return {
        lifecycleDerived,
        lifecycleActions,
        lifecyclePanelProps,
        submitDecisionNotification,
        decisionNotificationModalOpen,
        setDecisionNotificationModalOpen,
    };
}
