import type { RefObject } from 'react';

import type { CommunityPost, RepositoryDocument } from '@/app/services/lawyer-cloud';
import type { ForumParticipant } from '@/app/services/forum/forumMentionUtils';

export type CommunityScreenOverlaysProps = {
    activePostForComments: CommunityPost | null;
    currentUserId: string | null;
    isAdmin: boolean;
    followingIds: Set<string>;
    userStats: Record<string, { followerCount: number; postCount: number }>;
    mutedIds: Set<string>;
    forumMentionCandidates: ForumParticipant[];
    onCloseComments: () => void;
    onAddComment: (postId: string, content: string, parentId?: string) => Promise<boolean>;
    onToggleBestAnswer: (postId: string, commentId: string) => void;
    onDeleteComment: (postId: string, commentId: string) => void;
    onEditComment: (postId: string, commentId: string, content: string) => void;
    onFollow: (userId: string) => void;
    onToggleCommentUpvote?: (commentId: string) => void;
    onReportComment?: (commentId: string) => void;
    onMuteUser: (userId: string) => void;
    onOpenProfile: (userId: string, displayName?: string) => void;
    isSearchOpen: boolean;
    searchQuery: string;
    onSearchQueryChange: (value: string) => void;
    filterHasPdf: boolean;
    onFilterHasPdfChange: (value: boolean) => void;
    filterHasImage: boolean;
    onFilterHasImageChange: (value: boolean) => void;
    selectedTag: string | null;
    onSelectedTagChange: (value: string | null) => void;
    allSearchTags: string[];
    filteredPosts: CommunityPost[];
    filteredRepositoryDocs: RepositoryDocument[];
    onCloseSearch: () => void;
    onOpenPost: (postId: string) => void;
    onOpenDocument: (doc: RepositoryDocument) => void;
    isAddQuestionOpen: boolean;
    newPostText: string;
    onNewPostTextChange: (value: string) => void;
    newTagText: string;
    onNewTagTextChange: (value: string) => void;
    newIsAnonymous: boolean;
    onNewIsAnonymousChange: (value: boolean) => void;
    newIsUrgent: boolean;
    onNewIsUrgentChange: (value: boolean) => void;
    newAttachment: CommunityPost['attachment'];
    onRemoveAttachment: () => void;
    submittingPost: boolean;
    isRecordingVoice: boolean;
    voiceRecordingSec: number;
    imageInputRef: RefObject<HTMLInputElement | null>;
    docInputRef: RefObject<HTMLInputElement | null>;
    onToggleVoiceRecording: () => void;
    onImageUpload: (file: File) => void;
    onDocUpload: (file: File) => void;
    onSubmitPost: () => void;
    onCloseAddQuestion: () => void;
    isCreateGroupOpen: boolean;
    newGroupName: string;
    newGroupDesc: string;
    submittingGroup: boolean;
    onNewGroupNameChange: (value: string) => void;
    onNewGroupDescChange: (value: string) => void;
    onSubmitCreateGroup: () => void;
    onCloseCreateGroup: () => void;
    editingPostId: string | null;
    editingText: string;
    onEditingTextChange: (value: string) => void;
    onSaveEdit: () => void;
    onCancelEdit: () => void;
    savingEdit: boolean;
    pendingDeletePostId: string | null;
    pendingDeletePost: CommunityPost | null;
    deletingPost: boolean;
    onConfirmDeletePost: () => void;
    onCancelDeletePost: () => void;
    profileView: { userId: string; displayName?: string } | null;
    onCloseProfile: () => void;
    followBusyUserId: string | null;
};
