import type { MutableRefObject } from 'react';

import type { CommunityPost } from '@/app/services/lawyer-cloud';
import type { ForumGroup } from '@/app/services/forum/forumGroupTypes';
import type { RepositorySortKey } from '@/app/components/lawyer/CommunityScreen/repositoryListFilters';
import type { CommunitySection } from '@/app/components/lawyer/CommunityScreen/communitySectionState';
import type { ForumFollowRecord } from '@/app/services/forum/forumFollowTypes';

export type CommunityScreenBodyProps = {
    onBack?: () => void;
    forumSurfaceOpen?: boolean;
    activeSection: CommunitySection;
    onSectionChange: (section: CommunitySection) => void;
    onSearchOpen: () => void;
    onNavigateToPost: (postId: string) => void;
    currentUserId: string | null;
    selectedFilterIndex: number;
    onFilterSelect: (index: number) => void;
    repositorySearchTerm: string;
    onRepositorySearchTermChange: (value: string) => void;
    repositorySortBy: RepositorySortKey;
    onRepositorySortChange: (value: RepositorySortKey) => void;
    repositorySelectedType: string;
    onRepositoryTypeChange: (value: string) => void;
    repositorySelectedTag: string | null;
    onRepositoryTagChange: (value: string | null) => void;
    followingRecords: ForumFollowRecord[];
    onOpenFollowing: () => void;
    forumFeedScope: 'all' | 'following';
    onForumFeedScopeChange: (scope: 'all' | 'following') => void;
    forumStreamConnected: boolean;
    onAppBarDropdownChange: (open: boolean) => void;
    closeAppBarDropdownsRef: MutableRefObject<(() => void) | null>;
    showFollowingPanel: boolean;
    onCloseFollowingPanel: () => void;
    followerRecords: Array<{ followerId: string; createdAt: string }>;
    followingAuthorNames: Record<string, string>;
    onUnfollow: (id: string) => void;
    onFollowBack: (id: string) => void;
    onUpdateFollowPrefs: (
        id: string,
        prefs: Partial<Pick<ForumFollowRecord, 'notifyPosts' | 'notifyComments' | 'notifyReplies'>>,
    ) => void;
    onOpenFollowingFeed: () => void;
    onOpenProfile: (userId: string, displayName?: string) => void;
    loadingPosts: boolean;
    hasMore: boolean;
    loadingMore: boolean;
    visiblePosts: CommunityPost[];
    isAdmin: boolean;
    onToggleUpvote: (postId: string) => void;
    onCommentClick: (postId: string) => void;
    onDelete: (postId: string) => void;
    onEdit: (postId: string) => void;
    onReport: (postId: string) => void;
    onShare: (postId: string) => void;
    onLoadMore: () => void;
    onTogglePin: (postId: string) => void;
    onFollow: (userId: string) => void;
    followingIds: Set<string>;
    bookmarkedIds: Set<string>;
    onToggleBookmark: (postId: string) => void;
    onCopyPostText: (postId: string) => void;
    onSaveToVault: (postId: string) => void;
    onSaveToDevice: (postId: string) => void;
    onToggleLock: (postId: string) => void;
    onMuteUser: (userId: string) => void;
    userStats: Record<string, { followerCount: number; postCount: number }>;
    threadFollowingIds: Set<string>;
    onToggleThreadFollow: (postId: string) => void;
    activeGroupId: string | null;
    activeGroup: ForumGroup | null;
    onLeaveGroup: () => void;
    leavingGroup: boolean;
    groupPostsLoading: boolean;
    groupPostsHasMore: boolean;
    groupPostsLoadingMore: boolean;
    groupVisiblePosts: CommunityPost[];
    onLoadMoreGroupPosts: () => void;
    onBackFromGroup: () => void;
    groups: ForumGroup[];
    groupsLoading: boolean;
    groupsSearchQuery: string;
    onGroupsSearchQueryChange: (value: string) => void;
    onJoinGroup: (groupId: string) => void;
    onOpenGroup: (groupId: string) => void;
    onCreateGroupClick: () => void;
    joiningGroupId: string | null;
    onOpenAddQuestion: () => void;
    canPublishPost: boolean;
};
