import { buildLawyerDashboardTabBundle } from '@/app/hooks/lawyerDashboard/buildLawyerDashboardTabBundle';
import { buildLawyerDashboardTabStackMask } from '@/app/hooks/lawyerDashboard/buildLawyerDashboardTabStackMask';
import { shouldMaskLawyerDashboardTabStack, isLawyerDashboardTabMounted } from '@/app/hooks/lawyerDashboard/lawyerDashboardTabStack';
import { isRealSignedIn, resolveShellAuthUserId } from '@/app/services/auth/shellAuth';
import { buildLawyerDashboardShellProps } from '@/app/hooks/lawyerDashboard/buildLawyerDashboardShellProps';
import { buildLawyerDashboardOverlaysBundleProps } from '@/app/hooks/lawyerDashboard/buildLawyerDashboardOverlaysBundleProps';
import { buildLawyerDashboardSurface } from '@/app/hooks/lawyerDashboard/lawyerDashboardSurfaceUtils';
import type { LawyerDashboardCoreViewModel } from '@/app/hooks/lawyerDashboard/useLawyerDashboardCore.types';
import type { useLawyerDashboardCoreOrchestration } from '@/app/hooks/lawyerDashboard/useLawyerDashboardCoreOrchestration';

type Orchestration = ReturnType<typeof useLawyerDashboardCoreOrchestration>;

export type AssembleLawyerDashboardReadyViewParams = Orchestration & {
    onLogout: () => void;
    onAppNavigate?: (target: 'privacy' | 'support' | 'settings') => void;
    onNavigateToCase?: (caseId: string) => void;
    backgroundRuntimeEnabled: boolean;
};

export function assembleLawyerDashboardReadyView({
    onLogout,
    onAppNavigate,
    onNavigateToCase,
    backgroundRuntimeEnabled,
    user,
    authUser,
    settings,
    theme,
    shapeClass,
    pushAllowed,
    syncNotesOn,
    syncFilesOn,
    syncExecutionOn,
    appLock,
    notifications,
    profileTab,
    dashboardSettings,
    dashboardTransactions,
    dashboardRepository,
    dashboardCommunity,
    dashboardHome,
    appAlerts,
    archiveAndSync,
    overlays,
    workspace,
    navigation,
    calendarUserId,
    clusterScanSources,
    onClusterScanSources,
    criminalCasesForCluster,
    criminalBridge,
    globalSearchNav,
    quantumPendingForField,
    pendingFieldTasksCount,
    storeCases,
    hydrateCasesFromLawsuitFiles,
    dashboardExecutionFiles,
    deferredFeatureSurfacesProps,
}: AssembleLawyerDashboardReadyViewParams): Extract<LawyerDashboardCoreViewModel, { status: 'ready' }> {
    const { wallpaperSrc, hasWallpaper, dashboardBg, dashboardSurfaceStyle } = buildLawyerDashboardSurface({
        appearance: settings.appearance,
        themeBg: theme.bg,
    });

    const overlaysBundle = buildLawyerDashboardOverlaysBundleProps({
        onLogout,
        onAppNavigate,
        onNavigateToCase,
        user,
        authUser,
        shapeClass,
        theme,
        files: workspace.files,
        executionFiles: workspace.executionFiles,
        globalNotes: workspace.globalNotes,
        searchNotifications: notifications.searchNotifications,
        criminalCasesForCluster,
        overlays,
        criminalBridge,
        workspace,
        nav: {
            setActiveTab: overlays.setActiveTab,
            refreshAppAlerts: appAlerts.refreshAppAlerts,
            handleGlobalSearchNavigate: globalSearchNav.handleGlobalSearchNavigate,
            closeGlobalSearch: globalSearchNav.closeGlobalSearch,
        },
    });

    const { headerProps, homeTabProps, scheduleTabProps } = buildLawyerDashboardTabBundle({
        user,
        authUserId: authUser?.id,
        calendarUserId,
        clusterScanSources,
        calendarSearchFocus: overlays.calendarSearchFocus,
        onClearCalendarSearchFocus: overlays.clearCalendarSearchFocus,
        scheduleTabSessionKey: overlays.scheduleTabSessionKey,
        backToHomeFromSchedule: overlays.backToHomeFromSchedule,
        activeTab: overlays.activeTab,
        activeFile: workspace.activeFile,
        archiveType: archiveAndSync.archiveType,
        isCriminalDossierOpen: overlays.isCriminalDossierOpen,
        showSettings: dashboardSettings.showSettings,
        homeLayoutEditMode: dashboardHome.homeLayoutEditMode,
        enterHomeLayoutEdit: dashboardHome.enterHomeLayoutEdit,
        exitHomeLayoutEdit: dashboardHome.exitHomeLayoutEdit,
        homeTabSessionKey: dashboardHome.homeTabSessionKey,
        homeDockChromeSessionKey: dashboardHome.homeDockChromeSessionKey,
        isNewCaseModalOpen: workspace.isNewCaseModalOpen,
        isNotepadOpen: dashboardRepository.isRepositoryOpen,
        showCommunity: dashboardCommunity.showCommunity,
        showLawsuitsWorkspace: overlays.showLawsuitsWorkspace,
        lawsuitsWorkspaceTab: overlays.lawsuitsWorkspaceTab,
        showTransactions: dashboardTransactions.showTransactions,
        showTasksManager: overlays.showTasksManager,
        fieldTasksSheetOpen: overlays.fieldTasksSheetOpen,
        showDocs: dashboardRepository.isRepositoryOpen,
        showGlobalSearch: overlays.showGlobalSearch,
        showNotifications: notifications.showNotifications,
        notificationsUnreadCount: notifications.notificationsUnreadCount,
        pendingFieldTasksCount,
        visibleAppAlerts: appAlerts.visibleAppAlerts,
        appAlertsLoading: appAlerts.appAlertsLoading,
        appAlertsError: appAlerts.appAlertsError,
        theme,
        shapeClass,
        files: workspace.files,
        executionFiles: workspace.executionFiles,
        setActiveTab: overlays.setActiveTab,
        openProfileTab: overlays.openProfileTab,
        primeProfileTabMount: profileTab.primeProfileTabMount,
        openSettings: overlays.openSettings,
        primeSettingsShellMount: dashboardSettings.primeSettingsShellMount,
        openGlobalSearch: overlays.openGlobalSearch,
        primeGlobalSearchShellMount: overlays.primeGlobalSearchShellMount,
        openNotifications: notifications.openNotifications,
        primeNotificationPanelMount: notifications.primeNotificationPanelMount,
        navigateWorkspaceRoute: navigation.navigateWorkspaceRoute,
        openSecretaryAlert: navigation.openSecretaryAlert,
        dismissAppAlert: appAlerts.dismissAppAlert,
        handleAlertResolved: appAlerts.handleAlertResolved,
        setArchiveType: archiveAndSync.setArchiveType,
        armExecutionArchiveHost: overlays.armExecutionArchiveHost,
        openNormalNewCaseModal: workspace.openNormalNewCaseModal,
        openCommunityTab: dashboardCommunity.openCommunityTab,
        setLawsuitsDossierSection: overlays.setLawsuitsDossierSection,
        setLawsuitsWorkspaceTab: overlays.setLawsuitsWorkspaceTab,
        setShowLawsuitsWorkspace: overlays.setShowLawsuitsWorkspace,
        closeTransactionsHub: dashboardTransactions.closeTransactionsHub,
        openTransactionsHub: dashboardTransactions.openTransactionsHub,
        primeTransactionsHubMount: dashboardTransactions.primeTransactionsHubMount,
        closeHubShellOverlays: overlays.closeHubShellOverlays,
        openFieldTasksSheet: overlays.openFieldTasksSheet,
        primeFieldTasksShellMount: overlays.primeFieldTasksShellMount,
        openScheduleTab: overlays.openScheduleTab,
        primeScheduleTabMount: overlays.primeScheduleTabMount,
        openVaultModal: dashboardRepository.openVaultModal,
        primeVaultShellMount: dashboardRepository.primeVaultShellMount,
        openNotepad: dashboardRepository.openNotepad,
        openRepository: dashboardRepository.openRepository,
        closeNotepad: dashboardRepository.closeRepository,
        primeNotepadShellMount: dashboardRepository.primeNotepadShellMount,
        handleSaveNote: workspace.handleSaveNote,
        setActiveFile: workspace.setActiveFile,
        openCriminalCase: overlays.openCriminalCase,
        openUrgentInLawsuitsWorkspace: overlays.openUrgentInLawsuitsWorkspace,
        setTransactionsFocusId: dashboardTransactions.setTransactionsFocusId,
    });

    const tabStackMask = buildLawyerDashboardTabStackMask({
        overlays,
        archiveAndSync,
        dashboardTransactions,
        dashboardRepository,
        dashboardSettings,
        dashboardCommunity,
        workspace,
    } as AssembleLawyerDashboardReadyViewParams);
    const tabStackHidden = shouldMaskLawyerDashboardTabStack(tabStackMask);

    return {
        status: 'ready',
        shellProps: buildLawyerDashboardShellProps({
            dashboardSurfaceStyle,
            statusBarColor: hasWallpaper ? theme.bg : dashboardBg,
            wallpaperSrc,
            hasWallpaper,
            appearance: settings.appearance,
            backgroundRuntimeEnabled,
            user,
            calendarUserId,
            syncNotesOn,
            syncFilesOn,
            syncExecutionOn,
            pushAllowed,
            files: workspace.files,
            executionFiles: workspace.executionFiles,
            criminalCasesForCluster,
            globalNotes: workspace.globalNotes,
            fieldTasks: quantumPendingForField,
            onAlerts: appAlerts.handleAlertsFromBackground,
            onNotesSynced: (merged) => workspace.mergeNotesStores(merged),
            onLawsuitFilesSynced: (merged) => workspace.setFiles(merged),
            mergeNotesStores: workspace.mergeNotesStores,
            syncExecutionFilesNowRef: archiveAndSync.syncExecutionFilesNowRef,
            syncLawsuitFilesNowRef: archiveAndSync.syncLawsuitFilesNowRef,
            syncNotesNowRef: archiveAndSync.syncNotesNowRef,
            refreshAppAlertsRef: appAlerts.refreshAppAlertsRef,
            appLocked: appLock.locked,
            appUnlocking: appLock.unlocking,
            requiresBiometricToUnlock: appLock.requiresBiometricToUnlock,
            unlockWithBiometric: appLock.unlockWithBiometric,
            unlockContinue: appLock.unlockContinue,
            onLogout,
        }),
        notificationPanel: {
            isOpen: notifications.showNotifications,
            hostMounted: notifications.notificationHostMounted,
            panelSessionKey: notifications.notificationPanelSessionKey,
            userId: (() => {
                const uid = resolveShellAuthUserId(authUser?.id, user?.id);
                return isRealSignedIn(uid) ? uid! : '';
            })(),
            onClose: notifications.closeNotifications,
            onOpenPanel: notifications.openNotifications,
            onNavigate: navigation.handleNotificationRouting,
        },
        headerProps,
        homeTabProps: {
            ...homeTabProps,
            visible: isLawyerDashboardTabMounted(homeTabProps.visible, tabStackMask),
        },
        scheduleTabProps: {
            ...scheduleTabProps,
            active: isLawyerDashboardTabMounted(scheduleTabProps.visible, tabStackMask),
        },
        scheduleHostMounted: overlays.scheduleHostMounted ?? false,
        profileHostMounted: profileTab.profileHostMounted ?? false,
        profileTab: {
            visible: overlays.activeTab === 'profile',
            sessionKey: profileTab.profileTabSessionKey,
            perfOpenEpoch: profileTab.profileOpenEpoch,
            onBack: profileTab.closeProfileTab,
        },
        tabStackHidden,
        overlaysBundle,
        postInteractiveRuntimeProps: {
            onClusterScanSources,
            enabled: backgroundRuntimeEnabled,
            userId: user?.id,
            authUserId: authUser?.id,
            files: workspace.files,
            executionFiles: (dashboardExecutionFiles ?? workspace.executionFiles) as import('@/app/components/lawyer/LawyerDashboardParts/types').ExecutionFile[],
            globalNotes: workspace.globalNotes,
            quantumTasks: quantumPendingForField,
            criminalCasesForCluster,
            backgroundRuntimeEnabled,
            user,
            authUser,
            searchNotifications: notifications.searchNotifications,
            searchIndexVersion: overlays.searchIndexVersion ?? 0,
            showLawsuitsWorkspace: overlays.showLawsuitsWorkspace,
            lawsuitsDossierSection: overlays.lawsuitsDossierSection,
            storeCases,
            hydrateCasesFromLawsuitFiles,
            refreshAppAlerts: appAlerts.refreshAppAlerts,
            reloadLawsuitFiles: workspace.reloadLawsuitFiles,
            reloadExecutionFiles: workspace.reloadExecutionFiles,
            setGlobalNotes: workspace.setGlobalNotes,
            setActiveFile: workspace.setActiveFile,
            setArchiveType: archiveAndSync.setArchiveType,
            setLawsuitsDossierSection: overlays.setLawsuitsDossierSection,
            setLawsuitsWorkspaceTab: overlays.setLawsuitsWorkspaceTab,
            setShowLawsuitsWorkspace: overlays.setShowLawsuitsWorkspace,
        },
        deferredFeatureSurfacesProps,
    };
}
