import type { ExecutionDashboardPhoneBodyDeferredScope } from './ExecutionDashboardPhoneBodyDeferredScope';

const DEFERRED_SCOPE_KEYS = [
    'activeDebtorIsDeceased',
    'activeFinancialTab',
    'accumulatedAlimony',
    'appealPerspective',
    'appendGuarantorFollowupRequest',
    'archiveAndClearGuarantor',
    'persistGuarantorFollowupDetails',
    'assignmentWorkspaceCtx',
    'beginThirdPartyReceiveStep',
    'calculatedExecutionFee',
    'cancelThirdPartyReceiveStep',
    'claimType',
    'clearActiveSalarySeizurePath',
    'confirmThirdPartyReceive',
    'decisionsReloadEpoch',
    'decisionsStorageExecutionId',
    'executionData',
    'executionId',
    'executionStatus',
    'executionToolsTimelineLockedUi',
    'evictionAssetsTabUnlocked',
    'evictionCaseExpenses',
    'evictionCaseExpensesTotalForFinancial',
    'evictionGraceHidden',
    'evictionGracePinned',
    'evictionLawyerFeesInTotals',
    'financialHubAutoOpenMode',
    'financialHubSeizedMovableId',
    'financialHubSeizedPropertyId',
    'financialLedger',
    'financialLawyerFeesAmount',
    'financialPrincipalAmount',
    'financialStatus',
    'focusSeizureMovableInlineCompletion',
    'focusSeizurePropertyInlineCompletion',
    'followupSalarySeizureLabel',
    'followupSpecialization',
    'getLocalTodayYmd',
    'guarantorFollowupAwaitingDetailsSave',
    'handleCoerciveAction',
    'handleEvictionLawyerFeeRequest',
    'handleEvictionLedgerActivated',
    'handleFundsLedgerPayment',
    'handleGuarantorRequestFromFollowup',
    'isAlimonyClaim',
    'isEvictionExecutionModule',
    'isFinancialCenterExpanded',
    'isMaritalFurnitureClaim',
    'isNonFinancialClaim',
    'isPaused',
    'isRepresentingDebtor',
    'isVisitationClaim',
    'judicialCustodiansResolved',
    'lawyerFeePayoutApproved',
    'monthlyAlimony',
    'movableSeizureRegistryAssets',
    'movableSeizureRequestModalOpen',
    'movableSeizureSubjectDraft',
    'nextTimelineId',
    'paidClientFees',
    'paidCourtFees',
    'paidDebt',
    'paidDirectorateFees',
    'parsedClientFees',
    'parsedCourtFees',
    'parsedDirectorateFees',
    'patchSalarySeizureAssetDetails',
    'persistExecutionMerge',
    'pushSeizureAuctionCalendarAppointment',
    'pushTimelineEvent',
    'realEstateSeizureRegistryAssets',
    'releaseSeizureAssetRow',
    'remaining',
    'salarySeizureRegistryAssets',
    'salarySeizureTabRows',
    'seizureMatrixLedgerParamsRef',
    'setActiveFinancialTab',
    'setCaseTasksPending',
    'setEvictionGraceHidden',
    'setFinancialHubAutoOpenMode',
    'setFinancialHubSeizedMovableId',
    'setFinancialHubSeizedPropertyId',
    'setIsFinancialCenterExpanded',
    'setJudicialCustodianModalCtx',
    'setJudicialCustodianModalOpen',
    'setMovableSeizureRequestModalOpen',
    'setMovableSeizureSubjectDraft',
    'setPropertySeizureRequestModalOpen',
    'setPropertySeizureSubjectDraft',
    'setShowExecutionFinancialHub',
    'setThirdPartySeizuresUi',
    'setTimelineEvents',
    'setUnifiedLedgerRevision',
    'showExecutionFinancialHub',
    'showToast',
    'standaloneExecutionMarks',
    'statusMetadata',
    'submitMovableSeizureRequest',
    'submitPropertySeizureRequest',
    'thirdPartySeizureRegistryAssets',
    'thirdPartySeizuresUi',
    'timelineDebtorMetadata',
    'todayYmd',
    'totalOwed',
    'totalWithExecutionFee',
    'total_execution_expenses',
    'updateThirdPartyReceiveDraft',
    'viewExecutionData',
    'visitChildNames',
    'propertySeizureRequestModalOpen',
    'propertySeizureSubjectDraft',
    'graceHiddenKey',
    'shouldCalculateExecutionFee',
    'daysSinceNoticeCalculated',
    'gracePeriodEnded',
    'initiator',
] as const satisfies readonly (keyof ExecutionDashboardPhoneBodyDeferredScope)[];

export function buildPhoneBodyDeferredScope(
    source: Record<string, unknown>,
): ExecutionDashboardPhoneBodyDeferredScope {
    const out = {} as ExecutionDashboardPhoneBodyDeferredScope;
    for (const key of DEFERRED_SCOPE_KEYS) {
        (out as Record<string, unknown>)[key] = source[key];
    }
    const noop = () => {};
    if (typeof out.focusSeizurePropertyInlineCompletion !== 'function') {
        out.focusSeizurePropertyInlineCompletion = noop;
    }
    if (typeof out.focusSeizureMovableInlineCompletion !== 'function') {
        out.focusSeizureMovableInlineCompletion = noop;
    }
    return out;
}

