/** شريحة مكتوبة لمفاتيح مصدر قسم المدينين — بلا حقيبة عمياء عند النسخ. */

export const EXECUTION_PHONE_BODY_DEBTORS_SCOPE_KEYS = [
    'executionId',
    'executionData',
    'heirsDetailsIncludeClient',
    'onOpenUnifiedSummonsHub',
    'setSummonsContextDebtorKey',
    'setSummonsHubInitialMainTab',
    'setShowUnifiedSummonsModal',
    'activeCoerciveActions',
    'activeDebtorHeirsForNotification',
    'activeDebtorIsDeceased',
    'activeNoticeState',
    'activeTimelineEvents',
    'activeTimelineEventsDebtorScoped',
    'buildDebtorSummonsMarkerPatchForKey',
    'buildEmployeeAssignmentPatchForDebtorKey',
    'buildPartyHeirsRows',
    'buildPublicationNoticePatchForDebtorKey',
    'claimType',
    'clearDebtorSummonsMarker',
    'completeEvictionResidentialGrace',
    'completePoliceAssistance',
    'computeTaklifDeadlineYmd',
    'daysRemainingUntilDeadline',
    'debtorArrested',
    'debtorAttendedVoluntarily',
    'debtorBrowserTabsMode',
    'liabilityGroupTabsMode',
    'debtorLiabilityGroups',
    'debtorDeathMenuLabel',
    'debtorEmploymentToggleMenuLabel',
    'debtorForcedToAttend',
    'debtorSummonsMarkerLocal',
    'debtorSummonsProfile',
    'debtorWorkspaceChipStripRef',
    'debtorWorkspaceEntries',
    'decisionsReloadEpoch',
    'decisionsStorageExecutionId',
    'dismissDebtorAbsenceBadge',
    'effectiveDebtors',
    'evictionGraceBadgeInfo',
    'evictionGracePinned',
    'executionAppealBanner',
    'executionDebtorTabIndex',
    'executionMemoBadgePopoverOpen',
    'executionToolsTimelineLockedUi',
    'forcedAttendanceIssued',
    'forcedPathAttendanceSecured',
    'getDebtorSummonsMarkerForKey',
    'getDebtorSummonsProfile',
    'getEmployeeAssignmentForDebtorKey',
    'getExecutionPartyDisplayName',
    'getPersonalCoerciveSubtypeOutcome',
    'getPublicationNoticeForDebtorKey',
    'handleDebtorDeathMenuAction',
    'isAssignmentDeadlinePassed',
    'isDebtorGovernmentEmployee',
    'isDebtorRowEmployee',
    'isEvictionExecutionModule',
    'isHistoricalMode',
    'isNonFinancialClaim',
    'isRepresentingDebtor',
    'multiDebtorMode',
    'nextTimelineId',
    'openEvictionResidentialGraceModal',
    'openHeirsNotificationCenter',
    'openHeirsQuickView',
    'openPoliceAssistanceFromBadge',
    'financialLawyerFeesAmount',
    'partyBadgesExecutionId',
    'persistExecutionMerge',
    'persistGuarantorFollowupDetails',
    'policeAssistanceBadgeInfo',
    'primaryDebtorAbsenceBadge',
    'primaryDebtorKeyResolved',
    'primaryMemoNoticeBadge',
    'financialPrincipalAmount',
    'publicationNoticeDeadlineYmd',
    'pushTimelineEvent',
    'realEstateSeizureAssets',
    'saveSummonsMarkerPurposeEdit',
    'seizedAssets',
    'setDebtorSummonsMarkerLocal',
    'setEvictionGraceDecisionId',
    'setExecutionDebtorTabIndex',
    'setExecutionMemoBadgePopoverOpen',
    'setShowExtraDebtors',
    'setSummonsMarkerPopoverOpen',
    'setSummonsPurposeDraft',
    'showDebtorSummonsAttendanceBadge',
    'showDebtorUnservedMemoBadge',
    'showExtraDebtors',
    'showToast',
    'followupSpecialization',
    'standaloneExecutionMarks',
    'summonsMarkerPopoverOpen',
    'summonsPurposeDraft',
    'thirdPartySeizureAssets',
    'thirdPartySeizuresUi',
    'timelineDebtorMetadata',
    'toggleEvictionGracePinned',
    'viewExecutionData',
    'voluntaryAttendanceCount',
    'noticeVoluntaryPeriodEndOptimistic',
    'voluntaryEndOptimistic',
] as const;

export type ExecutionPhoneBodyDebtorsScopeKey =
    (typeof EXECUTION_PHONE_BODY_DEBTORS_SCOPE_KEYS)[number];

export type ExecutionPhoneBodyDebtorsScope = Record<ExecutionPhoneBodyDebtorsScopeKey, unknown>;

export function pickExecutionPhoneBodyDebtorsScope(
    source: Record<string, unknown>,
): ExecutionPhoneBodyDebtorsScope {
    const out = {} as ExecutionPhoneBodyDebtorsScope;
    for (const key of EXECUTION_PHONE_BODY_DEBTORS_SCOPE_KEYS) {
        out[key] = source[key];
    }
    return out;
}
