import type { MutableRefObject } from 'react';
import type { ExecutionDossierPaintFile } from '@/app/components/lawyer/dashboard/ExecutionDossierInstantFrame';
import type { HandlerClusterBridgeInput } from '../hooks/executionDashboardCore/handlerClusterContextShared';
import type { ExecutionDashboardCoreHandlerClusterInput } from '../hooks/executionDashboardCore/executionDashboardCoreHandlerClusterTypes';
import type { FollowupAdminSpecialHandlerClusterInput } from '../hooks/executionDashboardCore/followupAdminSpecialHandlerClusterInput';
import type { FollowupOtherPartyHandlerClusterInput } from '../hooks/executionDashboardCore/followupOtherPartyHandlerClusterInput';

export type ExecutionDashboardChunkHostProps = {
    /** فهرس الإضبارة لهيكل الانتظار — بلا دفتر موحّد */
    paintFile?: ExecutionDossierPaintFile | null;
    onExitToHome?: () => void;
    phoneBodyReady: boolean;
    shellOverlaysReady: boolean;
    phoneBodyScopeRef: MutableRefObject<Record<string, unknown>>;
    shellOverlayScopeRef: MutableRefObject<Record<string, unknown>>;
    shellOverlayScopeSnapshot: Record<string, unknown>;
    followupModalSnapshot: Record<string, unknown>;
    phoneBodyFingerprint: string;
    shellOverlayFingerprint: string;
    showUnifiedExecutionModal: boolean;
    unifiedModalTab?: string | null;
    loadLightHandlerCluster: boolean;
    loadFollowupHeavyHandlerCluster: boolean;
    loadFollowupAdminSpecialHandlerCluster: boolean;
    loadFollowupDossierControlsHandlerCluster: boolean;
    loadFollowupOtherPartyHandlerCluster: boolean;
    loadSeizureHeavyHandlerCluster: boolean;
    loadSeizureRequestsHandlerCluster: boolean;
    loadSeizureLogHandlerCluster: boolean;
    loadCoerciveHeavyHandlerCluster: boolean;
    loadPublicationNoticeHandlerCluster: boolean;
    loadDossierSupportHandlerCluster: boolean;
    loadPartyDeathHandlerCluster: boolean;
    lightHandlerClusterInput: ExecutionDashboardCoreHandlerClusterInput;
    followupAdminSpecialHandlerClusterInput: FollowupAdminSpecialHandlerClusterInput;
    followupDossierControlsHandlerClusterInput: HandlerClusterBridgeInput;
    followupOtherPartyHandlerClusterInput: FollowupOtherPartyHandlerClusterInput;
    seizureHeavyHandlerClusterInput: HandlerClusterBridgeInput;
    coerciveHeavyHandlerClusterInput: HandlerClusterBridgeInput;
    publicationNoticeHandlerClusterInput: HandlerClusterBridgeInput;
    dossierSupportHandlerClusterInput: HandlerClusterBridgeInput;
    partyDeathHandlerClusterInput: HandlerClusterBridgeInput;
    handlerClusterMountKey: string;
    onLightHandlerClusterReady: (cluster: Record<string, unknown>) => void;
    onFollowupAdminSpecialHandlerClusterReady: (cluster: Record<string, unknown>) => void;
    onFollowupDossierControlsHandlerClusterReady: (cluster: Record<string, unknown>) => void;
    onFollowupOtherPartyHandlerClusterReady: (cluster: Record<string, unknown>) => void;
    onSeizureHeavyHandlerClusterReady: (cluster: Record<string, unknown>) => void;
    onCoerciveHeavyHandlerClusterReady: (cluster: Record<string, unknown>) => void;
    onDossierSupportHandlerClusterReady: (cluster: Record<string, unknown>) => void;
    onPartyDeathHandlerClusterReady: (cluster: Record<string, unknown>) => void;
};
